---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: 'Si votre configuration inclut des agrégats sans mise en miroir, vous devez connaître les problèmes d"accès potentiels après les opérations de basculement.' 
---
= En savoir plus sur les agrégats non mis en miroir dans les configurations IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre configuration inclut des agrégats sans mise en miroir, vous devez connaître les problèmes d'accès potentiels après les opérations de basculement.



== Agrégats non mis en miroir et espaces de noms hiérarchiques

Si vous utilisez des espaces de noms hiérarchiques, vous devez configurer le chemin de jonction de sorte que tous les volumes de ce chemin soient sur des agrégats en miroir uniquement ou sur des agrégats non mis en miroir uniquement. La configuration d'agrégats non mis en miroir et en miroir dans le chemin de jonction peut empêcher l'accès aux agrégats non mis en miroir après le basculement.



== Agrégats non mis en miroir et maintenance nécessitant une coupure de courant

Si vous effectuez une commutation négociée pour la maintenance qui nécessite une coupure de courant à l'échelle du site, vous devez d'abord mettre hors ligne manuellement tous les agrégats non mis en miroir appartenant au site sinistré.

Si vous ne mettez pas hors ligne les agrégats non mis en miroir appartenant au site sinistré, les nœuds du site survivant risquent de tomber en panne en raison de paniques multidisques. Cela peut se produire si des agrégats non mis en miroir commutés sont hors ligne ou manquants en raison d'une perte de connectivité au stockage du site sinistré suite à une coupure de courant ou à une perte de ISL.



== Agrégats non mis en miroir, volumes de métadonnées CRS et volumes racine SVM de données

Le volume des métadonnées du service de réplication de la configuration (CRS) et les volumes root du SVM de données doivent se trouver sur un agrégat en miroir. Vous ne pouvez pas déplacer ces volumes vers un agrégat non mis en miroir. S'ils se trouvent sur un agrégat non mis en miroir, les opérations de commutation et de retour négociées sont rejetées et le  `metrocluster check` la commande renvoie un avertissement.



== Agrégats et SVM non miroirs

Vous devez configurer les SVM uniquement sur des agrégats en miroir ou non. La configuration de SVM sur une combinaison d'agrégats en miroir et non en miroir peut entraîner une commutation de plus de 120 secondes. Cela peut entraîner une interruption de données si les agrégats non en miroir ne sont pas mis en ligne.



== Agrégats non mis en miroir et SAN

Avant ONTAP 9.9.1, un LUN ne devait pas être situé sur un agrégat non mis en miroir. La configuration d'une LUN sur un agrégat non mis en miroir peut entraîner un basculement supérieur à 120 secondes et une panne de données.



== Ajouter des étagères de stockage pour les agrégats non miroirs

Si vous ajoutez des étagères et souhaitez les utiliser pour des agrégats non mis en miroir dans une configuration IP MetroCluster , vous devez procéder comme suit :

. Avant de démarrer la procédure d'ajout des tiroirs, exécutez la commande suivante :
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`

. Vérifiez que l'assignation automatique des disques est désactivée :
+
`disk option show`

. Suivez les étapes de la procédure pour ajouter les étagères.
. Attribuez manuellement tous les disques du nouveau tiroir au nœud qui sera propriétaire de l'agrégat ou des agrégats sans miroir.
. Créez les agrégats :
+
`storage aggregate create`

. Après avoir terminé la procédure, exécutez la commande suivante :
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`

. Vérifiez que l'assignation automatique des disques est activée :
+
`disk option show`


