---
permalink: install-ip/concept-risks-limitations-automatic-switchover.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, forced 
summary:  
---
= Risques et limitations liés à l'utilisation du basculement automatique forcé de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.12.1, vous pouvez activer la fonctionnalité de basculement forcé automatique MetroCluster dans une configuration IP MetroCluster. Cette fonction est une extension de la fonction de basculement non planifié assisté par un médiateur (MAUSO).

Le basculement en cas de détection d'une défaillance de site se produit automatiquement lorsque vous activez la fonctionnalité de basculement forcé automatique MetroCluster. Cette fonction peut être utilisée en complément de la fonctionnalité de basculement automatique MetroCluster IP.

Lorsque vous laissez une configuration IP MetroCluster fonctionner en mode de basculement forcé automatique, les problèmes connus suivants peuvent entraîner la perte de données :

* La mémoire non volatile des contrôleurs de stockage n'est pas mise en miroir sur le partenaire de reprise après incident à distance sur le site partenaire.



CAUTION: Vous pouvez rencontrer des scénarios qui ne sont pas mentionnés. NetApp n'est pas responsable de la corruption des données, de la perte de données ou des autres dommages susceptibles d'apparaître liés à l'activation de la fonction de basculement automatique forcé de MetroCluster. N'utilisez pas la fonctionnalité de basculement automatique forcé de MetroCluster si les risques et les limitations ne sont pas acceptables.
