---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: Les différentes configurations MetroCluster présentent des différences clés au niveau des composants requis. 
---
= Différences entre le médiateur ONTAP et le logiciel MetroCluster Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.7, vous pouvez utiliser le basculement automatique non planifié assisté par médiateur ONTAP dans la configuration IP MetroCluster ou le logiciel MetroCluster Tiebreaker. Il n'est pas nécessaire d'utiliser le logiciel MAUSO ou Tiebreaker ; cependant, si vous choisissez de ne pas utiliser l'un de ces services, vous devez le faire link:../disaster-recovery/concept_dr_workflow.html["effectuer une récupération manuelle"] en cas d'incident.

Les différentes configurations MetroCluster effectuent un basculement automatique dans plusieurs cas :

* *Configurations FC MetroCluster utilisant la capacité AUSO (non présentes dans les configurations IP MetroCluster)*
+
Dans ces configurations, AUSO est lancé en cas de défaillance des contrôleurs, mais le stockage (et les ponts, le cas échéant) reste opérationnel.

* *Configurations IP MetroCluster utilisant ONTAP Mediator (ONTAP 9.7 et versions ultérieures)*
+
Dans ces configurations, MAUSO est lancé dans les mêmes circonstances que AUSO, comme décrit ci-dessus, ainsi qu'après une panne complète du site (contrôleurs, stockage et commutateurs).

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Découvrez comment le médiateur ONTAP prend en charge le basculement automatique non planifié"].

* *Configurations IP ou FC MetroCluster utilisant le logiciel disjoncteur d'attache en mode actif*
+
Dans ces configurations, il procède au basculement non planifié après une défaillance complète du site.

+
Avant d'utiliser le logiciel disjoncteur d'attache, passez en revue link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation et configuration du logiciel MetroCluster Tiebreaker"]





== Interopérabilité du médiateur ONTAP avec d'autres applications et appareils

Vous ne pouvez pas utiliser d'applications ou d'appliances tierces pouvant déclencher un basculement en combinaison avec le médiateur ONTAP. En outre, la surveillance d'une configuration MetroCluster avec le logiciel MetroCluster Tiebreaker n'est pas prise en charge avec le programme ONTAP Mediator.
