---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: 'À partir d"ONTAP 9.7, ONTAP Mediator peut aider la configuration IP MetroCluster à effectuer un basculement automatique non planifié en fournissant un référentiel physiquement séparé pour les informations d"état.' 
---
= Préparez-vous à installer ONTAP Mediator dans une configuration IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Votre environnement doit répondre à certaines exigences.

Les exigences suivantes s'appliquent à un seul groupe de reprise d'activité (DR Group). En savoir plus sur link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["Groupes de reprise sur incident"].

* Si vous prévoyez de mettre à jour votre version Linux, faites-le avant d'installer la version la plus récente d'ONTAP Mediator.
* Les logiciels ONTAP Mediator et MetroCluster Tiebreaker ne doivent pas être utilisés tous les deux avec la même configuration MetroCluster.
* ONTAP Mediator doit être installé sur un hôte Linux à un emplacement distinct des sites MetroCluster.
+
La connectivité entre le médiateur ONTAP et chaque site doit être composée de deux domaines de panne distincts.

* ONTAP Mediator peut prendre en charge jusqu'à cinq configurations MetroCluster simultanément.
* Le basculement non planifié automatique est pris en charge dans ONTAP 9.7 et versions ultérieures.
* IPv6 n'est pas pris en charge par le médiateur ONTAP.




== Configuration réseau requise pour l'utilisation d'ONTAP Mediator dans une configuration MetroCluster

Pour installer ONTAP Mediator dans une configuration MetroCluster, vous devez vous assurer que la configuration répond à plusieurs exigences réseau.

* Latence
+
Latence maximale inférieure à 75 ms (RTT).

+
La gigue ne doit pas dépasser 5 ms.

* MTU
+
La taille de MTU doit être d'au moins 1400.

* Perte de paquets
+
Pour le trafic ICMP (Internet Control message Protocol) et TCP, la perte de paquets doit être inférieure à 0.01 %.

* La bande passante
+
Le lien entre ONTAP Mediator et un groupe DR doit avoir au moins 20 Mbps de bande passante.

* Connectivité indépendante
+
Une connectivité indépendante entre chaque site et le médiateur ONTAP est requise. Une défaillance sur un site ne doit pas interrompre la connectivité IP entre les deux autres sites non affectés.





== Exigences de l'hôte pour ONTAP Mediator dans une configuration MetroCluster

Vous devez vous assurer que la configuration répond à plusieurs exigences d'hôte.

* Le médiateur ONTAP doit être installé sur un site externe qui est physiquement séparé des deux clusters ONTAP.
* Le médiateur ONTAP prend en charge un nombre maximum de cinq configurations MetroCluster.
* Le médiateur ONTAP ne nécessite pas plus que la configuration minimale requise par le système d'exploitation hôte pour le processeur et la mémoire (RAM).
* Outre les exigences minimales du système d'exploitation hôte, 30 Go d'espace disque utilisable supplémentaires doivent être disponibles.
+
** Chaque groupe de reprise après incident nécessite jusqu'à 200 Mo d'espace disque.






== Exigences relatives au pare-feu pour le médiateur ONTAP

ONTAP Mediator utilise un certain nombre de ports pour communiquer avec des services spécifiques.

Si vous utilisez un pare-feu tiers :

* L'accès HTTPS doit être activé.
* Il doit être configuré de manière à autoriser l'accès sur les ports 31784 et 3260.
+
Lors de l'utilisation du pare-feu Red Hat ou CentOS par défaut, le pare-feu est automatiquement configuré lors de l'installation de Mediator.



Le tableau suivant répertorie les ports que vous devez autoriser dans votre pare-feu :

[NOTE]
====
* Le port iSCSI n'est requis que dans une configuration IP MetroCluster.
* Le port 22/tcp n'est pas nécessaire pour un fonctionnement normal, mais vous pouvez l'activer temporairement pour la maintenance et le désactiver une fois la session de maintenance terminée.


====
|===


| Port/services | Source | Direction | Destination | Objectif 


 a| 
22/tcp
 a| 
Hôte de gestion
 a| 
Entrant
 a| 
Médiateur de ONTAP
 a| 
Gestion du médiateur SSH/ONTAP



 a| 
31784/tcp
 a| 
LIF de gestion de cluster et de gestion de nœud
 a| 
Entrant
 a| 
Serveur web du médiateur ONTAP
 a| 
API REST (HTTPS)



 a| 
3260/tcp
 a| 
LIF de gestion des nœuds
 a| 
Bidirectionnel
 a| 
Cibles iSCSI du médiateur ONTAP
 a| 
Connexion de données iSCSI pour les boîtes aux lettres

|===


== Directives pour la mise à niveau d'ONTAP Mediator dans une configuration MetroCluster

Si vous mettez à niveau ONTAP Mediator, vous devez respecter les exigences de version Linux et suivre les instructions pour la mise à niveau.

* ONTAP Mediator peut être mis à niveau d'une version immédiatement antérieure à la version actuelle.
* Toutes les versions de Mediator sont prises en charge sur les configurations IP de MetroCluster exécutant ONTAP 9.7 ou version ultérieure.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installer ou mettre à niveau ONTAP Mediator"^]



== Après la mise à niveau

Une fois la mise à niveau du Mediator et du système d'exploitation terminée, vous devez émettre le `storage iscsi-initiator show` Commande pour confirmer que les connexions du médiateur sont en cours.
