---
permalink: install-ip/mcc-compliant-netapp-validated-switches.html 
sidebar: sidebar 
keywords: isls, ip, layer 2, layer 3, shared switch 
summary: Cette section fournit les informations nécessaires pour vérifier que votre configuration MetroCluster et le réseau répondent à toutes les exigences. 
---
= Commutateurs validés par NetApp et compatibles MetroCluster
:allow-uri-read: 


Tous les switchs utilisés dans votre configuration, y compris les switchs Back-end, doivent être certifiés NetApp ou compatibles MetroCluster.



== Commutateurs validés NetApp

Un commutateur est validé par NetApp s'il répond aux exigences suivantes :

* Le switch est fourni par NetApp dans le cadre de la configuration IP MetroCluster
* Le commutateur est répertorié dans le link:https://hwu.netapp.com/["NetApp Hardware Universe"^] Comme commutateur pris en charge sous _MetroCluster-over-IP-connections_
* Le commutateur n'est utilisé que pour connecter des contrôleurs IP MetroCluster et, dans certaines configurations, des tiroirs disques NS224
* Le commutateur est configuré à l'aide du fichier RCF (Reference Configuration File) fourni par NetApp


Tout switch qui ne répond pas à ces exigences n'est *pas* un switch validé par NetApp.



== Commutateurs compatibles MetroCluster

Un commutateur conforme à MetroCluster n'est pas validé par NetApp, mais peut être utilisé dans une configuration MetroCluster IP si elle répond à certaines exigences et directives de configuration.


NOTE: NetApp ne fournit pas de services de support pour la résolution de problèmes ni la configuration pour un switch non validé conforme à MetroCluster.
