---
permalink: install-ip/concept_configure_the_mcc_software_in_ontap.html 
sidebar: sidebar 
keywords: metrocluster, configuration, ontap, node-level, configuration, node, site, relationship, configuring, configure, 
summary: Vous devez installer chaque nœud dans la configuration MetroCluster de ONTAP, y compris les configurations au niveau des nœuds et la configuration des nœuds en deux sites. Vous devez également implémenter la relation MetroCluster entre les deux sites. 
---
= Configuration du logiciel MetroCluster dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer chaque nœud dans la configuration MetroCluster de ONTAP, y compris les configurations au niveau des nœuds et la configuration des nœuds en deux sites. Vous devez également implémenter la relation MetroCluster entre les deux sites.

Si un module de contrôleur tombe en panne pendant la configuration, reportez-vous à la section link:../disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html#controller-module-failure-scenarios-during-metrocluster-installation["Scénarios de panne du module de contrôleur lors de l'installation de MetroCluster"].

image::../media/workflow_mcc_ip_high_level_node_and_cluster_configuration_software.svg[workflow mcc ip haut niveau, logiciel de configuration de cluster et de nœud]
