---
permalink: install-ip/concept-network-speeds-and-switchport-modes.html 
sidebar: sidebar 
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed, switch port mode 
summary: Si vous utilisez des commutateurs compatibles MetroCluster, vous devez connaître les vitesses réseau spécifiques à la plate-forme et les conditions requises pour le mode des ports de commutation. 
---
= Vitesses réseau et modes de port de commutation spécifiques à la plate-forme ONTAP pour les commutateurs compatibles MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez des commutateurs compatibles MetroCluster, vous devez connaître les vitesses réseau spécifiques à la plate-forme et les conditions requises pour le mode des ports de commutation.

Le tableau suivant indique les vitesses réseau spécifiques à la plateforme et les modes de port de commutation pour les switchs compatibles MetroCluster. Vous devez configurer le mode de port du commutateur conformément au tableau.

[NOTE]
====
* Des valeurs manquantes indiquent que la plateforme ne peut pas être utilisée avec un switch compatible MetroCluster.
* Les systèmes AFF A30, AFF C30, AFF C60 et FAS50 nécessitent un adaptateur QSFP-SFP sur la carte du contrôleur pour prendre en charge une vitesse réseau de 25 Gbit/s.


====
[cols="1,2,2"]
|===
| Plateforme | Vitesse du réseau (Gbps) | Mode de port du commutateur 


 a| 
FAS9500

AFF A900

ASA A900
 a| 
100Gbps

40 Gbit/s lors de la mise à niveau du PCM depuis FAS9000 ou AFF A700
 a| 
Mode trunk



 a| 
AFF C800

ASA C800

AFF A800

ASA A800
 a| 
40Gbps ou 100Gbps
 a| 
Mode d'accès



 a| 
FAS9000

AFF A700
 a| 
40Gbps
 a| 
Mode d'accès



 a| 
FAS8300

AFF C400

ASA C400

AFF A400

ASA A400
 a| 
40Gbps ou 100Gbps
 a| 
Mode trunk



 a| 
AFF A320
 a| 
40Gbps ou 100Gbps
 a| 
Mode d'accès



 a| 
FAS8200

AFF A300
 a| 
25Gbps
 a| 
Mode d'accès



 a| 
FAS500f

AFF C250

ASA C250

AFF A250

ASA A250
 a| 
-
 a| 
-



 a| 
FAS2750

AVEC AFF A220
 a| 
-
 a| 
-



 a| 
AFF A150

ASA A150
 a| 
-
 a| 
-



 a| 
AFF A20
 a| 
25Gbps
 a| 
Mode trunk



 a| 
AFF A30
 a| 
25Gbps ou 100Gbps
 a| 
Mode trunk



 a| 
AFF C30
 a| 
25Gbps ou 100Gbps
 a| 
Mode trunk



 a| 
AFF C60
 a| 
25Gbps ou 100Gbps
 a| 
Mode trunk



 a| 
FAS50
 a| 
25Gbps ou 100Gbps
 a| 
Mode trunk



 a| 
AFF A50
 a| 
100Gbps
 a| 
Mode trunk



 a| 
AFF A70
 a| 
100Gbps
 a| 
Mode trunk



 a| 
AFF A90
 a| 
100Gbps
 a| 
Mode trunk



 a| 
AFF A1K
 a| 
100Gbps
 a| 
Mode trunk



 a| 
AFF C80
 a| 
100Gbps
 a| 
Mode trunk



 a| 
FAS70
 a| 
100Gbps
 a| 
Mode trunk



 a| 
FAS90
 a| 
100Gbps
 a| 
Mode trunk

|===