---
permalink: install-ip/overview-isl-requirements.html 
sidebar: sidebar 
keywords: isls, ip, layer 2, layer 3, shared switch 
summary: Découvrez les informations requises pour vérifier que votre configuration MetroCluster et le réseau répondent à toutes les exigences ISL. 
---
= Présentation des exigences ISL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifiez que votre réseau et votre configuration IP MetroCluster sont conformes à toutes les exigences de liaison inter-commutateurs (ISL). Même si certaines exigences ne s'appliquent pas à votre configuration, vous devez toujours connaître toutes les exigences ISL pour mieux comprendre la configuration globale.

Le tableau suivant présente les sujets traités dans cette section.

[cols="25,75"]
|===
| Titre | Description 


| link:mcc-compliant-netapp-validated-switches.html["Commutateurs validés par NetApp et compatibles MetroCluster"] | Décrit les exigences relatives au commutateur.

S'applique à tous les switchs utilisés dans les configurations MetroCluster, y compris aux switchs Back-end. 


| link:concept-requirements-isls.html["Considérations relatives aux liens ISL"] | Décrit les exigences ISL.

S'applique à toutes les configurations MetroCluster, indépendamment de la topologie réseau et que vous utilisiez des switchs validés par NetApp ou des switchs compatibles MetroCluster. 


| link:concept-considerations-layer-2-layer-3.html["Considérations relatives au déploiement de MetroCluster dans des réseaux partagés de couche 2 ou 3"] | Décrit la configuration requise pour les réseaux partagés de couche 2 ou 3.

S'applique à toutes les configurations, à l'exception des configurations MetroCluster utilisant des switchs validés par NetApp et des liens ISL directement connectés. 


| link:concept-requirement-and-limitations-mcc-compliant-switches.html["Considérations relatives à l'utilisation de commutateurs compatibles MetroCluster"] | Décrit la configuration requise pour les switchs compatibles MetroCluster.

S'applique à toutes les configurations MetroCluster qui n'utilisent pas de switchs validés par NetApp. 


| link:concept-example-network-topologies.html["Exemples de topologies réseau MetroCluster"] | Le fournit des exemples de topologies réseau MetroCluster différentes.

S'applique à toutes les configurations MetroCluster. 
|===