---
sidebar: sidebar 
permalink: install-ip/set-up-mcc-peering-system-manager.html 
keywords: metrocluster, peer, peering, pair, pairing, configuration, config, mcc, HA 
summary: Depuis ONTAP 9.8, vous pouvez gérer les opérations de site IP MetroCluster avec System Manager. Cela implique la configuration de deux clusters et le peering de cluster. 
---
= Configurer le peering IP MetroCluster avec ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.8, vous pouvez gérer les opérations de configuration IP de MetroCluster avec System Manager. Une fois que deux clusters sont configurés, vous configurez le peering entre eux.

.Avant de commencer
Configurez deux clusters. Voir la link:set-up-mcc-site-system-manager.html["Configurez un site IP MetroCluster"]procédure.

Différentes étapes sont réalisées par différents administrateurs système sur les sites géographiques de chaque cluster. Pour expliquer ce processus, les clusters sont appelés « grappe de sites A » et « grappe de sites B ».



== Effectuez le processus de peering à partir du site A.

Ce processus est exécuté par un administrateur système sur le site A.

.Étapes
. Connectez-vous au site A cluster.
. Dans System Manager, sélectionnez *Dashboard* dans la colonne de navigation de gauche pour afficher la vue d'ensemble du cluster.
+
Le tableau de bord affiche les détails de ce cluster (site A). Dans la section *MetroCluster*, site Un cluster est affiché sur la gauche.

. Cliquez sur *attacher le cluster partenaire*.
. Entrez les détails des interfaces réseau permettant aux nœuds du cluster site A de communiquer avec les nœuds du cluster site B.
. Cliquez sur *Enregistrer et continuer*.
. Dans la fenêtre *joindre un cluster partenaire*, sélectionnez *Je n'ai pas de phrase de passe*. Ceci vous permet de générer une phrase de passe.
. Copiez le mot de passe généré et partagez-le avec l'administrateur système du site B.
. Sélectionnez *Fermer*.




== Effectuez le processus de peering à partir du site B.

Ce processus est effectué par un administrateur système sur le site B.

.Étapes
. Connectez-vous au cluster site B.
. Dans System Manager, sélectionnez *Dashboard* pour afficher la vue d'ensemble du cluster.
+
Le tableau de bord affiche les détails de ce cluster (site B). Dans la section MetroCluster, le cluster du site B est indiqué sur la gauche.

. Cliquez sur *Attach Partner Cluster* pour démarrer le processus de peering.
. Entrez les détails des interfaces réseau permettant aux nœuds du cluster site B de communiquer avec les nœuds du cluster site A.
. Cliquez sur *Enregistrer et continuer*.
. Dans la fenêtre *joindre un cluster partenaire*, sélectionnez *J'ai une phrase de passe*. Vous pouvez ainsi saisir la phrase de passe que vous avez reçue de l'administrateur système du site A.
. Sélectionnez *Peer* pour terminer le processus de peering.


.Et la suite ?
Une fois le processus de peering terminé, vous configurez les clusters. Voir link:configure-mcc-site-system-manager.html["Configurez un site IP MetroCluster"].
