---
permalink: install-ip/switch-move-cluster-lifs.html 
sidebar: sidebar 
keywords: ip, switch, configuring, configure, factory defaults, cisco, MACsec encryption, 9336C, 9336, forward error correction, fec 
summary: 'Lorsque vous mettez à jour le micrologiciel du commutateur ou le fichier de configuration (RCF), vous déplacez les LIF du cluster vers le commutateur partenaire pour permettre des opérations de cluster non perturbatrices pendant la mise à niveau.' 
---
= Déplacez les LIF du cluster avant un remplacement de commutateur IP MetroCluster, une modification de RCF ou une mise à jour du firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous remplacez un commutateur IP MetroCluster ou modifiez le micrologiciel du commutateur ou le fichier de configuration de référence (RCF), vous devez déplacer les LIF du cluster vers le commutateur partenaire pour permettre des opérations de cluster non perturbatrices.

.Description de la tâche
* Vous devez effectuer cette tâche avant de mettre à niveau ou de rétrograder le micrologiciel du commutateur, de remplacer le RCF du commutateur ou de remplacer un commutateur IP.
+

NOTE: Si vous configurez les commutateurs pour la première fois, vous pouvez ignorer cette tâche sauf si vous effectuez un remplacement de commutateur.

* Cette tâche nécessite d'utiliser à la fois les commandes ONTAP et les commandes de commutateur ; les commandes ONTAP sont utilisées sauf indication contraire.
* Dans les exemples utilisés dans cette procédure, vous mettez à niveau IP_switch_A_1, vous devez donc migrer les LIF du cluster vers IP_switch_A_2.
* Les exemples de sortie de commande dans cette procédure montrent les détails pour un commutateur Cisco. Le résultat peut varier selon le modèle et le fournisseur de votre commutateur.


.Étapes
. Afficher les ports du cluster connectés aux commutateurs du cluster sur chaque nœud :
+
`network device-discovery show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node_A_2/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/18      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/18      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/2       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/2       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/10      N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/10      N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/5       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/6       N9K-C9372PX
node_A_2/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:02)
                                             Eth121/1/1        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:a0)
                                             Ethernet1/18      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:48)
                                             Ethernet1/18      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:28)
                                             Ethernet1/10      -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:80)
                                             Ethernet1/10      -
            e9a    local_network_switch (88:f0:31:86:fe:a8)
                                             Ethernet1/5       -
            e9b    local_network_switch (88:f0:31:86:fe:a9)
                                             Ethernet1/6       -
node_A_1/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/17      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/17      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/1       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/1       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/9       N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/9       N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/3       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/4       N9K-C9372PX
node_A_1/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:03)
                                             Eth121/1/2        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:9c)
                                             Ethernet1/17      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:44)
                                             Ethernet1/17      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:24)
                                             Ethernet1/9       -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:7c)
                                             Ethernet1/9       -
            e9a    local_network_switch (88:f0:31:86:fe:a6)
                                             Ethernet1/3       -
            e9b    local_network_switch (88:f0:31:86:fe:a7)
                                             Ethernet1/4       -
30 entries were displayed.
----
====
. Vérifiez l'état administratif et opérationnel de chaque port du cluster.
+
.. Vérifiez que tous les ports du cluster sont opérationnels et en bon état :
+
`network port show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network port show -role cluster

Node: node_A_1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false

Node: node_A_2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false
4 entries were displayed.
----
====
.. Vérifiez que toutes les interfaces du cluster (LIF) sont sur le port d'attache :
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.

cluster_A::*>
----
====
.. Vérifiez que le cluster affiche les informations pour les deux commutateurs du cluster :
+
`system switch ethernet show -is-monitoring-enabled-operational true`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> system switch ethernet show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
IP_switch_A_1               cluster-network    10.231.7.251     N9K-C9336C-FX2
     Serial Number: FDO26020KLJ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

IP_switch_A_2               cluster-network    10.231.7.252     N9K-C9336C-FX2
     Serial Number: FDO26020KGL
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

2 entries were displayed.

cluster_A::*>
----
====


. Désactivez la restauration automatique des LIF du cluster. Les LIF du cluster basculent vers le commutateur du cluster partenaire et y restent pendant que vous effectuez la procédure de mise à niveau sur le commutateur ciblé :
+

NOTE: Si vous mettez à niveau le deuxième fabric, vous pouvez ignorer cette étape et passer à <<shut-down-ports,Étape 4>>.

+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert false

Warning: Disabling the auto-revert feature of the cluster logical interface may
         effect the availability of your cluster network. Are you sure you want
         to continue? {y|n}: y

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.
----
====
. [[shut-down-ports]]Sur le commutateur de cluster IP_switch_A1, désactivez les ports connectés aux ports de cluster des nœuds.
+
[role="tabbed-block"]
====
.Cisco
--
[listing]
----
IP_switch_A_1(config)# sh int eth1/1,eth1/2 brief

--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch
#
--------------------------------------------------------------------------------
Eth1/1          101     eth  access up      none                      40G(D) --
Eth1/2          101     eth  access up      none                      40G(D) --
IP_switch_A_1(config)#
IP_switch_A_1(config)# int eth1/1,eth1/2
IP_switch_A_1(config-if-range)# shut
IP_switch_A_1(config-if-range)#
----
--
.Broadcom
--
[listing]
----
IP_switch_A1(config)# interface eth1/1/1-2,eth1/7-8
IP_switch_A1(config-if-range)# shutdown
----
--
.NVIDIA
--
.. Afficher les interfaces du cluster :
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ nv show interface
Interface    Admin Status  Oper Status  Speed  MTU    Type      Remote Host     Remote Port  Summary
-----------  ------------  -----------  -----  -----  --------  --------------  -----------  ---------
swp1         up            up           100G   9216   swp       cluster1         e1a
----
.. Arrêtez le port d'interface du cluster :
+
[listing]
----
sudo python3 <RCF_name> runCmd swp1 state down
----


--
====
. [[verify_cluster_lif_migration]] Vérifiez que les LIF du cluster ont migré vers les ports hébergés sur le commutateur de cluster IP_switch_A2. Cela peut prendre quelques secondes.
+
`network interface show -role cluster`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4b     false
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4b     false
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.
----
====
. Vérifiez que le cluster fonctionne correctement :
+
`cluster show`

+
.Afficher un exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node_A_1             true    true          false
node_A_2             true    true          false
2 entries were displayed.
----
====


.Une fois que vous avez terminé
Une fois les LIF du cluster transférées vers le commutateur partenaire, vous pouvez suivre les procédures de configuration standard de votre fournisseur de commutateur pour effectuer la mise à niveau vers la version cible du firmware ou du RCF :

* link:../install-ip/task_switch_config_broadcom.html["Configurez les commutateurs IP Broadcom"]
* link:../install-ip/task_switch_config_cisco.html["Configuration des commutateurs IP Cisco"]
* link:../install-ip/task_switch_config_nvidia.html["Configurez les commutateurs IP NVIDIA"]



NOTE: Après avoir configuré les commutateurs dans la première structure, vous devez répéter les étapes pour déplacer les LIF du cluster sur la deuxième structure.
