---
permalink: install-ip/task_sw_config_restore_defaults.html 
sidebar: sidebar 
keywords: metrocluster, controller, restore defaults 
summary: Vous devez réinitialiser et restaurer les valeurs par défaut des modules de contrôleur pour garantir une configuration propre. 
---
= Restauration des valeurs par défaut du système sur un module de contrôleur
:allow-uri-read: 


[role="lead"]
Réinitialisez et restaurez les valeurs par défaut sur les modules de contrôleur.

. Dans l'invite DU CHARGEUR, valeurs par défaut des variables environnementales : `set-defaults`
. Démarrez le nœud sur le menu de démarrage : `boot_ontap menu`
+
Une fois que vous avez exécuté cette commande, attendez que le menu de démarrage s'affiche.

. Effacez la configuration des nœuds :
+
--
** Si vous utilisez des systèmes configurés pour ADP, sélectionnez option `9a` dans le menu de démarrage, puis répondez `no` lorsque vous y êtes invité.
+

NOTE: Ce processus est perturbateur.

+
L'écran suivant affiche l'invite du menu de démarrage :

+
[listing]
----

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 9a
...

########## WARNING: AGGREGATES WILL BE DESTROYED ##########
This is a disruptive operation that applies to all the disks
that are attached and visible to this node.

Before proceeding further, make sure that:

The aggregates visible from this node do not contain
data that needs to be preserved.
This option (9a) has been executed or will be executed
on the HA partner node (and DR/DR-AUX partner nodes if
applicable), prior to reinitializing any system in the
HA-pair or MetroCluster configuration.
The HA partner node (and DR/DR-AUX partner nodes if
applicable) is currently waiting at the boot menu.
Do you want to abort this operation (yes/no)? no
----


--
+
** Si votre système n'est pas configuré pour ADP, tapez `wipeconfig` À l'invite du menu de démarrage, puis appuyez sur entrée.
+
L'écran suivant affiche l'invite du menu de démarrage :

+
[listing]
----

Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  wipeconfig
This option deletes critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?: yes
Rebooting to finish wipeconfig request.
----



