---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: 'Si vous n"avez pas reçu l"équipement déjà installé dans les armoires, vous devez installer les composants en rack.' 
---
= Montez les composants matériels de configuration IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous n'avez pas reçu l'équipement déjà installé dans les armoires, vous devez installer les composants en rack.

.Description de la tâche
Cette tâche doit être effectuée sur les deux sites MetroCluster.

.Étapes
. Planifiez le positionnement des composants MetroCluster.
+
L'espace rack dépend du modèle de plateforme des modules de contrôleur, des types de switchs et du nombre de piles de tiroirs disques dans votre configuration.

. Mettez-vous à la terre.
. Installez les modules de contrôleur sur le rack ou l'armoire.
+
Suivez les étapes pour _Installer le matériel_ sous les instructions _Installer et configurer_ pour votre modèle de plate-forme dans lelink:https://docs.netapp.com/us-en/ontap-systems/index.html["Documentation des systèmes matériels ONTAP"^] .

. Installez les commutateurs IP sur le rack ou l'armoire.
. Installez les tiroirs disques, mettez-les sous tension, puis définissez les ID de tiroir.
+
** Vous devez mettre chaque tiroir disque hors tension puis sous tension.
** Il est vivement recommandé d'utiliser des ID de tiroir unique pour chaque tiroir disque SAS dans chaque groupe MetroCluster DR afin de faciliter le dépannage.


+

IMPORTANT: Ne câisez pas les tiroirs disques destinés à contenir actuellement des agrégats non mis en miroir. Vous devez patienter jusqu'à la fin de la configuration de MetroCluster et déployer les tiroirs destinés aux agrégats sans mise en miroir après l'utilisation de `metrocluster modify -enable-unmirrored-aggr-deployment true` commande.


