---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Vous pouvez supprimer le médiateur ONTAP de la configuration IP MetroCluster. 
---
= Annuler la configuration du médiateur ONTAP à partir de la configuration IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déconfigurer ONTAP Mediator à partir de la configuration IP MetroCluster.

.Avant de commencer
Vous devez avoir installé et configuré avec succès ONTAP Mediator sur un emplacement réseau accessible par les deux sites MetroCluster.

.Étapes
. Annulez la configuration d'ONTAP Mediator à l'aide de la commande suivante :
+
`metrocluster configuration-settings mediator remove`

+
Vous êtes invité à entrer le nom d'utilisateur et le mot de passe du compte d'utilisateur admin du Mediator ONTAP.

+

NOTE: Si le médiateur ONTAP est en panne, le  `metrocluster configuration-settings mediator remove` La commande vous invite toujours à saisir le nom d'utilisateur et le mot de passe du compte d'utilisateur administrateur ONTAP Mediator et supprime ONTAP Mediator de la configuration MetroCluster.

+
.. Vérifier s'il y a des disques cassés en utilisant la commande suivante :
+
`disk show -broken`

+
*Exemple*

+
....
There are no entries matching your query.
....


. Confirmez que ONTAP Mediator a été supprimé de la configuration MetroCluster en exécutant les commandes suivantes sur les deux clusters :
+
.. `metrocluster configuration-settings mediator show`
+
*Exemple*

+
[listing]
----
This table is currently empty.
----
.. `storage iscsi-initiator show -label mediator`
+
*Exemple*

+
[listing]
----
There are no entries matching your query.
----



