---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Vous pouvez supprimer le médiateur ONTAP de la configuration IP MetroCluster. 
---
= Supprimer le médiateur ONTAP d'une configuration IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déconfigurer ONTAP Mediator à partir de la configuration IP MetroCluster.

.Avant de commencer
Vous devez avoir installé et configuré avec succès ONTAP Mediator sur un emplacement réseau accessible par les deux sites MetroCluster.

.Étapes
. Annulez la configuration d'ONTAP Mediator à l'aide de la commande suivante :
+
`metrocluster configuration-settings mediator remove`

+
Vous êtes invité à entrer le nom d'utilisateur et le mot de passe du compte d'utilisateur admin du Mediator ONTAP.

+

NOTE: Si le médiateur ONTAP est en panne, le  `metrocluster configuration-settings mediator remove` La commande vous invite toujours à saisir le nom d'utilisateur et le mot de passe du compte d'utilisateur administrateur ONTAP Mediator et supprime ONTAP Mediator de la configuration MetroCluster.

+
.. Vérifier s'il y a des disques cassés en utilisant la commande suivante :
+
`disk show -broken`

+
*Exemple*

+
....
There are no entries matching your query.
....


. Si vous utilisez un ONTAP Mediator qui utilise HTTPS pour la communication, supprimez les certificats d'autorité de certification après avoir supprimé l'ONTAP Mediator :
+
.. Afficher les certificats d'autorité de certification installés :
+
`security certificate show -common-name ONTAPMediatorCA`

.. Supprimez les certificats racine et intermédiaires installés :
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. Vérifiez que ONTAP Mediator a bien été supprimé de la MetroCluster configuration en exécutant la commande suivante sur les deux clusters :
+
.. `metrocluster configuration-settings mediator show`
+
*Exemple*

+
[listing]
----
This table is currently empty.
----



