---
permalink: install-ip/task_config_switch_health.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, snmp, health, monitoring 
summary: 'Vous pouvez configurer les commutateurs IP pour qu"ils utilisent SNMPv3 pour la surveillance de l"état de santé.' 
---
= Configurer les commutateurs MetroCluster IP pour le contrôle de l'état
:allow-uri-read: 


[role="lead"]
Dans les configurations MetroCluster IP, vous pouvez configurer SNMPv3 pour surveiller l'état des commutateurs IP.



== Étape 1 : configurer l'utilisateur SNMPv3 sur les commutateurs IP MetroCluster

Procédez comme suit pour configurer l'utilisateur SNMPv3 sur les commutateurs IP MetroCluster.


IMPORTANT: Vous devez utiliser les protocoles d'authentification et de confidentialité dans les commandes. L'utilisation de l'authentification sans confidentialité n'est pas prise en charge.

[role="tabbed-block"]
====
.Pour les commutateurs IP Broadcom
--
.Étapes
. Si le groupe d'utilisateurs 'network-admin' n'existe pas déjà, créez-le :
+
`(IP_switch_1) (Config)# snmp-server group network-admin v3 auth read "Default"`

. Vérifiez que le groupe 'network-admin' a été créé :
+
`(IP_switch_1) (Config)# show snmp group`

. Configurez l'utilisateur SNMPv3 sur les commutateurs IP Broadcom :
+
[listing]
----
(IP_switch_1)# config
(IP_switch_1) (Config)# snmp-server user <user_name> network-admin auth-sha priv-aes128
----
+
Entrez le mot de passe d'authentification lorsque vous y êtes invité.

+
[listing]
----
#snmp-server user admin1 network-admin auth-sha priv-aes128

Enter Authentication Password:
----


--
.Pour les commutateurs IP Cisco
--
.Étapes
. Exécutez les commandes suivantes pour configurer l'utilisateur SNMPv3 sur un commutateur IP Cisco :
+
[listing]
----
IP_switch_A_1 # configure terminal
IP_switch_A_1 (config) # snmp-server user <user_name>  auth [md5/sha/sha-256] <auth_password> priv (aes-128) <priv_password>
----
. Vérifiez que l'utilisateur SNMPv3 est configuré sur le commutateur :
+
`IP_switch_A_1(config) # show snmp user <user_name>`

+
L'exemple de résultat suivant indique que l'utilisateur `admin` Est configuré pour SNMPv3 :

+
[listing]
----
IP_switch_A_1(config)# show snmp user admin
User                Auth      Priv(enforce) Groups              acl_filter

____                ____      _____________ ______              __________

admin               md5       aes-128(no)   network-admin
----


--
====


== Étape 2 : configurer l'utilisateur SNMPv3 dans ONTAP

Procédez comme suit pour configurer l'utilisateur SNMPv3 dans ONTAP.

. Configurez l'utilisateur SNMPv3 dans ONTAP :
+
`security login create -user-or-group-name <user_name> -application snmp -authentication-method usm -remote-switch-ipaddress <ip_address>`

. Configurer la surveillance de l'état du commutateur pour surveiller le commutateur à l'aide du nouvel utilisateur SNMPv3 :
+
`system switch ethernet modify -device <device_id> -snmp-version SNMPv3 -community-or-username <user_name>`

. Vérifiez que le numéro de série du périphérique qui sera surveillé avec l'utilisateur SNMPv3 nouvellement créé est correct :
+
.. Afficher la période d'interrogation du contrôle de l'état du commutateur :
+
`system switch ethernet polling-interval show`

.. Exécutez la commande suivante une fois le délai d'interrogation écoulé :
+
`system switch ethernet show-all -instance -device <device_serial_number>`





.Une fois que vous avez terminé
Si vous le souhaitez, suivez link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-log-collection.html["Configurer la collecte des journaux"^]les étapes à .
