---
permalink: install-ip/task_cable_other_connections.html 
sidebar: sidebar 
keywords: cabling, cable, component, peering, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure 
summary: Vous devez câbler les ports du module de contrôleur utilisés pour le peering de cluster, la gestion et la connectivité des données. 
---
= Câblage des ports de peering, de données et de gestion des contrôleurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez câbler les ports du module de contrôleur utilisés pour le peering de cluster, la gestion et la connectivité des données.

Cette tâche doit être effectuée sur chaque module de contrôleur de la configuration MetroCluster.

Au moins deux ports sur chaque module de contrôleur doivent être utilisés pour le peering de cluster.

La bande passante minimale recommandée pour les ports et la connectivité réseau est de 1 GbE.

. Identifier et câbler au moins deux ports pour peering de cluster et vérifier qu'ils disposent d'une connectivité réseau avec le cluster partenaire.
+
Le peering de cluster peut être effectué sur des ports dédiés ou sur des ports data. L'utilisation de ports dédiés fournit un débit plus élevé pour le trafic de peering de cluster.

+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html["Configuration cluster et SVM peering express"]

. Reliez les ports de gestion et de données du contrôleur aux réseaux de gestion et de données du site local.
+
Suivez les instructions d'installation de votre plate-forme sur le https://docs.netapp.com/us-en/ontap-systems/["Documentation des systèmes matériels ONTAP"^].


