---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, remove, unconfigure, requirements, mediator requirements 
summary: Vous pouvez supprimer le service médiateur ONTAP de la configuration IP de MetroCluster. 
---
= Déconfigurez le service Mediator ONTAP à partir de la configuration IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déconfigurer le service Mediator ONTAP à partir de la configuration IP de MetroCluster.

.Avant de commencer
Vous devez avoir installé et configuré avec succès le médiateur ONTAP sur un emplacement réseau pouvant être atteint par les deux sites MetroCluster.

.Étapes
. Déconfigurez le service Mediator ONTAP à l'aide de la commande suivante :
+
`metrocluster configuration-settings mediator remove`

+
Vous êtes invité à entrer le nom d'utilisateur et le mot de passe du compte d'utilisateur admin du Mediator ONTAP.

+

NOTE: Si le médiateur ONTAP est arrêté, le `metrocluster configuration-settings mediator remove` La commande vous invite toujours à saisir le nom d'utilisateur et le mot de passe du compte utilisateur admin du Mediator ONTAP et supprime le service ONTAP Mediator de la configuration MetroCluster.

+
.. Vérifier s'il y a des disques cassés en utilisant la commande suivante :
+
`disk show -broken`

+
*Exemple*

+
....
There are no entries matching your query.
....


. Vérifiez que le service médiateur ONTAP a été supprimé de la configuration MetroCluster en exécutant les commandes suivantes sur les deux clusters :
+
.. `metrocluster configuration-settings mediator show`
+
*Exemple*

+
[listing]
----
This table is currently empty.
----
.. `storage iscsi-initiator show -label mediator`
+
*Exemple*

+
[listing]
----
There are no entries matching your query.
----



