---
permalink: disaster-recovery/task_reassign_roots_mcfc.html 
sidebar: sidebar 
keywords: reassign, ownership, nvram, system, id, replaced 
summary: 'Si l"un des modules de contrôleur ou des deux cartes NVRAM ont été remplacés sur le site de reprise sur incident, vous devez réaffecter les disques appartenant aux agrégats racine aux modules de contrôleur de remplacement.' 
---
= Réaffectation de la propriété de disque des agrégats racine aux modules de contrôleur de remplacement (configurations MetroCluster FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si l'un des modules de contrôleur ou des deux cartes NVRAM ont été remplacés sur le site de secours, l'ID système a changé et vous devez réaffecter les disques appartenant aux agrégats racine aux modules de contrôleur de remplacement.

.Description de la tâche
Étant donné que les nœuds sont en mode de basculement et que la réparation a été effectuée, seuls les disques contenant les agrégats racine du pool 1 du site de secours sont réaffectés dans cette section. À ce stade, ils sont les seuls disques qui appartiennent encore à l'ancien ID système.

Cette section présente des exemples de configurations à deux et quatre nœuds. Pour les configurations à deux nœuds, vous pouvez ignorer les références au second nœud de chaque site. Dans le cas de configurations à 8 nœuds, il faut tenir compte des nœuds supplémentaires sur le second groupe DR. Les exemples illustrent les hypothèses suivantes :

* Le site A est le site sur incident.
+
** Le noeud_A_1 a été remplacé.
** Le noeud_A_2 a été remplacé.
+
Présenter uniquement dans les configurations MetroCluster à quatre nœuds.



* Le site B est le site survivant.
+
** Le nœud_B_1 fonctionne correctement.
** Le nœud_B_2 fonctionne correctement.
+
Présenter uniquement dans les configurations MetroCluster à quatre nœuds.





Les anciens et nouveaux ID système ont été identifiés dans link:task_replace_hardware_and_boot_new_controllers.html#determining-the-system-ids-and-vlan-ids-of-the-old-controller-modules["Détermination des ID système des modules de contrôleur de remplacement"].

Les exemples de cette procédure utilisent des contrôleurs avec les ID système suivants :

|===


| Nombre de nœuds | Nœud | ID système d'origine | Nouvel ID système 


.4+| Quatre  a| 
Nœud_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
Nœud_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
Nœud_B_1
 a| 
4068741254
 a| 
inchangé



 a| 
Nœud_B_2
 a| 
4068741256
 a| 
inchangé



 a| 
Deux
 a| 
Nœud_A_1
 a| 
4068741258
 a| 
1574774970

|===
.Étapes
. Avec le nœud de remplacement en mode Maintenance, réallouer les disques de l'agrégat racine :
+
`disk reassign -s old-system-ID -d new-system-ID`

+
[listing]
----
*> disk reassign -s 4068741258 -d 1574774970
----
. Afficher les disques pour confirmer le changement de propriété des disques agrégat racine pool1 du site de secours vers le nœud de remplacement :
+
`disk show`

+
Le résultat peut afficher plus ou moins de disques, selon le nombre de disques présents dans l'agrégat racine et si l'un de ces disques est défectueux et a été remplacé. Si les disques ont été remplacés, pool0 disques n'apparaîtra pas dans la sortie.

+
Les disques des agrégats racines pool1 du site de secours doivent maintenant être affectés au nœud de remplacement.

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK             OWNER                POOL   SERIAL NUMBER   HOME                DR HOME
------------       -------------        -----  -------------   -------------       -------------
sw_A_1:6.126L19    node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L3     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L7     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_B_1:6.126L8     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L24    node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L2     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)

*> aggr status
         Aggr State           Status
 node_A_1_root online          raid_dp, aggr
                               mirror degraded
                               64-bit
*>
----
. Afficher l'état de l'agrégat :
+
`aggr status`

+
Le résultat peut afficher plus ou moins de disques, selon le nombre de disques présents dans l'agrégat racine et si l'un de ces disques est défectueux et a été remplacé. Si des disques ont été remplacés, pool0 disques n'apparaîtra pas dans la sortie.

+
[listing]
----
*> aggr status
          Aggr State           Status
  node_A_1_root online          raid_dp, aggr
                                mirror degraded
                                64-bit
*>
----
. Supprimez le contenu des disques de la boîte aux lettres :
+
`mailbox destroy local`

. Si l'agrégat n'est pas en ligne, le mettre en ligne :
+
`aggr online aggr_name`

. Arrêtez le nœud pour afficher l'invite DU CHARGEUR :
+
`halt`


