---
permalink: disaster-recovery/task_reassign_pool1_disastersite_mcip.html 
sidebar: sidebar 
keywords: metrocluster, disaster, site, replacement, controller, module, reassign, ownership 
summary: Si les modules du contrôleur ou les cartes NVRAM ont été remplacés sur le site de reprise sur incident, vous devez réaffecter les disques appartenant aux agrégats racine aux modules de contrôleur de remplacement. 
---
= Réaffectation de la propriété du disque pour les disques du pool 1 sur le site de secours (configurations MetroCluster IP)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si l'un des modules de contrôleur ou des deux cartes NVRAM ont été remplacés sur le site de secours, l'ID système a changé et vous devez réaffecter les disques appartenant aux agrégats racine aux modules de contrôleur de remplacement.

.Description de la tâche
Étant donné que les nœuds sont en mode basculement, seuls les disques contenant les agrégats racine de pool1 du site de sinistre sont réaffectés dans cette tâche. À ce stade, ils sont les seuls disques qui appartiennent encore à l'ancien ID système.

Cette tâche est effectuée sur les nœuds de remplacement sur le site d'incident.

Cette tâche est effectuée en mode Maintenance.

Les exemples illustrent les hypothèses suivantes :

* Le site A est le site sur incident.
* Le noeud_A_1 a été remplacé.
* Le noeud_A_2 a été remplacé.
* Le site B est le site survivant.
* Le nœud_B_1 fonctionne correctement.
* Le nœud_B_2 fonctionne correctement.


Les anciens et nouveaux ID système ont été identifiés dans link:../disaster-recovery/task_replace_hardware_and_boot_new_controllers.html["Remplacement du matériel et démarrage des nouveaux contrôleurs"].

Les exemples de cette procédure utilisent des contrôleurs avec les ID système suivants :

|===


| Nœud | ID système d'origine | Nouvel ID système 


 a| 
Nœud_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
Nœud_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
Nœud_B_1
 a| 
4068741254
 a| 
inchangé



 a| 
Nœud_B_2
 a| 
4068741256
 a| 
inchangé

|===
.Étapes
. Avec le nœud de remplacement en mode Maintenance, réaffectez les disques de l'agrégat racine à l'aide de la commande correcte, selon que votre système est configuré avec ADP et votre version ONTAP.
+
Vous pouvez procéder à la réaffectation lorsque vous y êtes invité.

+
|===


| Si le système utilise ADP... | Utiliser cette commande pour la réaffectation des disques... 


 a| 
Oui (ONTAP 9.8)
 a| 
`disk reassign -s old-system-ID -d new-system-ID -r dr-partner-system-ID`



 a| 
Oui (ONTAP 9.7.x et versions antérieures)
 a| 
`disk reassign -s old-system-ID -d new-system-ID -p old-partner-system-ID`



 a| 
Non
 a| 
`disk reassign -s old-system-ID -d new-system-ID`

|===
+
L'exemple suivant montre la réaffectation de disques sur un système non ADP :

+
[listing]
----
*> disk reassign -s 4068741256 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537037643.
Do you want to continue (y/n)? y
disk reassign parameters: new_home_owner_id 537070473 , new_home_owner_name
Disk 0m.i0.3L14 will be reassigned.
Disk 0m.i0.1L6 will be reassigned.
Disk 0m.i0.1L8 will be reassigned.
Number of disks to be reassigned: 3
----
. Détruire le contenu des disques de la boîte aux lettres :
+
`mailbox destroy local`

+
Vous pouvez poursuivre l'opération de destruction lorsque vous y êtes invité.

+
L'exemple suivant montre le résultat de la commande local de destruction de boîte aux lettres :

+
[listing]
----
*> mailbox destroy local
Destroying mailboxes forces a node to create new empty mailboxes,
which clears any takeover state, removes all knowledge
of out-of-date plexes of mirrored volumes, and will prevent
management services from going online in 2-node cluster
HA configurations.
Are you sure you want to destroy the local mailboxes? y
...............Mailboxes destroyed.
*>
----
. Si les disques ont été remplacés, des plexes locaux en panne doivent être supprimés.
+
.. Afficher le statut de l'agrégat :
+
`aggr status`

+
Dans l'exemple suivant, le plex node_A_1_aggr0/plex0 a échoué.

+
[listing]
----
*> aggr status
Aug 18 15:00:07 [node_B_1:raid.vol.mirror.degraded:ALERT]: Aggregate node_A_1_aggr0 is
   mirrored and one plex has failed. It is no longer protected by mirroring.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex0
   clean(-1), online(0)
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex2
   clean(0), online(1)
Aug 18 15:00:07 [node_B_1:raid.mirror.vote.noRecord1Plex:error]: WARNING: Only one plex
   in aggregate node_A_1_aggr0 is available. Aggregate might contain stale data.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: volobj_mark_sb_recovery_aggrs: tree:
   node_A_1_aggr0 vol_state:1 mcc_dr_opstate: unknown
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (VOL):
   raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (MIRROR):
   raid state change UNINITD -> DEGRADED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex0
   (PLEX): raid state change UNINITD -> FAILED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2
   (PLEX): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2/rg0
   (GROUP): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Topology updated for aggregate node_A_1_aggr0
   to plex plex2
*>
----
.. Supprimer le plex en échec :
+
`aggr destroy plex-id`

+
[listing]
----
*> aggr destroy node_A_1_aggr0/plex0
----


. Arrêtez le nœud pour afficher l'invite DU CHARGEUR :
+
`halt`

. Répétez cette procédure sur l'autre nœud du site de secours.

