---
permalink: disaster-recovery/task_config_switches_mcip.html 
sidebar: sidebar 
keywords: metrocluster, ip, configuration, switchback, operation 
summary: Vous devez configurer tous les commutateurs IP remplacés. 
---
= Configuration des commutateurs IP (configurations MetroCluster IP)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer tous les commutateurs IP remplacés.

.Description de la tâche
Cette tâche s'applique uniquement aux configurations IP de MetroCluster.

Cela doit être effectué sur les deux commutateurs. Vérifiez après la configuration du premier commutateur que l'accès au stockage sur le site survivant n'est pas affecté.


NOTE: Si l'accès au stockage sur le site survivant ne doit pas continuer à utiliser le deuxième commutateur.

.Étapes
. Reportez-vous à la section link:../install-ip/concept_considerations_differences.html["Installation et configuration IP de MetroCluster : différences entre les configurations ONTAP MetroCluster"] pour les procédures de câblage et de configuration d'un commutateur de remplacement.
+
Vous pouvez utiliser les procédures des sections suivantes :

+
** Câblage des commutateurs IP
** Configuration des commutateurs IP


. Si les liens ISL étaient désactivés sur le site survivant, activez les liens ISL et vérifiez que ces liens sont en ligne.
+
.. Activer les interfaces ISL sur le premier switch :
+
`no shutdown`

+
Les exemples suivants montrent les commandes d'un commutateur IP Broadcom ou d'un commutateur IP Cisco.

+
|===


| Changer de fournisseur | Commandes 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_1)> enable
(IP_switch_A_1)# configure
(IP_switch_A_1)(Config)# interface 0/13-0/16
(IP_switch_A_1)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_1)(Interface 0/13-0/16 )# exit
(IP_switch_A_1)(Config)# exit
----


 a| 
Cisco
 a| 
[listing]
----
IP_switch_A_1# conf t
IP_switch_A_1(config)# int eth1/15-eth1/20
IP_switch_A_1(config)# no shutdown
IP_switch_A_1(config)# copy running startup
IP_switch_A_1(config)# show interface brief
----
|===
.. Activez les interfaces ISL sur le commutateur partenaire :
+
`no shutdown`

+
Les exemples suivants montrent les commandes d'un commutateur IP Broadcom ou d'un commutateur IP Cisco.

+
|===


| Changer de fournisseur | Commandes 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_2)> enable
(IP_switch_A_2)# configure
(IP_switch_A_2)(Config)# interface 0/13-0/16
(IP_switch_A_2)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_2)(Interface 0/13-0/16 )# exit
(IP_switch_A_2)(Config)# exit
----


 a| 
Cisco
 a| 
[listing]
----
IP_switch_A_2# conf t
IP_switch_A_2(config)# int eth1/15-eth1/20
IP_switch_A_2(config)# no shutdown
IP_switch_A_2(config)# copy running startup
IP_switch_A_2(config)# show interface brief
----
|===
.. Vérifiez que les interfaces sont activées :
+
`show interface brief`

+
L'exemple suivant montre la sortie d'un commutateur Cisco.

+
[listing]
----
IP_switch_A_2(config)# show interface brief

--------------------------------------------------------
Port VRF Status IP Address Speed MTU
--------------------------------------------------------
mt0 -- up 10.10.99.10 100 1500
--------------------------------------------------------
Ethernet    VLAN Type Mode    Status Reason Speed   Port
Interface                                           Ch
#
--------------------------------------------------------
.
.
.
Eth1/15    10   eth   access  up     none   40G(D)  --
Eth1/16    10   eth   access  up     none   40G(D)  --
Eth1/17    10   eth   access  down   none   auto(D) --
Eth1/18    10   eth   access  down   none   auto(D) --
Eth1/19    10   eth   access  down   none   auto(D) --
Eth1/20    10   eth   access  down   none   auto(D) --
.
.
.
IP_switch_A_2#
----



