---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: MetroCluster
    url: "/index.html"
  - title: Notes de version
    url: "/releasenotes.html"
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: Comprendre les fonctionnalités de protection des données et de reprise
      après incident d'MetroCluster
    entries:
    - title: Comment MetroCluster protège les données et assure la reprise après incident
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: Mentions légales
    url: "/legal_notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Installez MetroCluster IP
      url: "/install-ip/index.html"
    - title: Installation de Fabric-Attached MetroCluster
      url: "/install-fc/index.html"
    - title: Installer Stretch MetroCluster
      url: "/install-stretch/index.html"
    - title: Installer le disjoncteur d'attache
      url: "/tiebreaker/concept_overview_of_the_tiebreaker_software.html"
    - title: Installer un médiateur (MetroCluster IP uniquement)
      url: "/install-ip/concept_mediator_requirements.html"
  - title: Maintenance
    links:
    - title: Commutateurs FC
      summary: Maintenance et remplacement des commutateurs FC dans les configurations
        MetroCluster FC
      url: "/maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html"
    - title: Commutateurs IP
      summary: Maintenance et remplacement des commutateurs IP dans les configurations
        MetroCluster IP
      url: "/maintain/task_replace_an_ip_switch.html"
    - title: Ponts ATTO
      summary: Maintenance et remplacement de ponts FC-SAS ATTO dans les configurations
        FC MetroCluster
      url: "/maintain/concept_using_fibrebridge_7600n_bridges_in_mcc_configurations.html"
    - title: Tiroirs disques
      summary: Remplacement des tiroirs disques par ajout à chaud et sans interruption
        des configurations MetroCluster FC.
      url: "/maintain/index.html"
  - title: Fichiers RCF
    links:
    - title: Fichiers RCF MetroCluster
      summary: Générer ou télécharger des fichiers RCF pour vos commutateurs MetroCluster.
      url: https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/docsandkb-tab
  - title: En savoir plus >>
    links:
    - title: Architecture et conception de la solution NetApp MetroCluster | TR-4705
      summary: Étudier la solution MetroCluster FC.
      url: https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf
    - title: Architecture et conception de la solution IP de MetroCluster | TR-4689
      summary: Comprendre la solution MetroCluster IP.
      url: https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf
  - title: Mettre à niveau, développer et convertir
    links:
    - title: Mise à niveau et actualisation du matériel
      summary: Mettre à niveau les contrôleurs dans une configuration MetroCluster.
      url: "/upgrade/concept_choosing_an_upgrade_method_mcc.html"
    - title: Développez un MetroCluster à deux nœuds
      summary: Ajoutez des contrôleurs aux configurations MetroCluster pour créer
        une configuration à quatre ou huit nœuds.
      url: "/upgrade/task_expand_a_two_node_mcc_fc_configuration_to_a_four_node_fc_configuration_supertask.html"
    - title: Développez un MetroCluster à quatre nœuds
      summary: Ajoutez des contrôleurs aux configurations MetroCluster pour créer
        une configuration à huit nœuds.
      url: "/upgrade/task_expand_a_four_node_mcc_fc_configuration_to_an_eight_node_configuration.html"
    - title: Conversion de FC MetroCluster en IP MetroCluster
      summary: Effectuer la transition d'une configuration IP MetroCluster existante
        vers une configuration IP MetroCluster.
      url: "/transition/concept_choosing_your_transition_procedure_mcc_transition.html"
    - title: Mettre à niveau les fichiers RCF IP MetroCluster
      summary: Mettre à niveau les fichiers RCF des switchs dans les configurations
        MetroCluster IP.
      url: "/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html"
  - title: Firmware du pont ATTO
    links:
    - title: FiberBridge 7600N
      summary: Téléchargez le micrologiciel pour un pont 7600.
      url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+7600N
    - title: FibreBridge 7500N
      summary: Téléchargez le micrologiciel pour un pont 7500.
      url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+7500N
    - title: FibreBridge 6500N
      summary: Téléchargez le micrologiciel pour un pont 6500.
      url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+6500N
  - title: Ressources supplémentaires
    links:
    - title: NetApp Config Advisor
      summary: Vérifiez la configuration et le câblage.
      url: https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor
    - title: NetApp Hardware Universe
      summary: Vérifiez que votre matériel est pris en charge.
      url: https://hwu.netapp.com/
    - title: Base de connaissances du support NetApp
      summary: Recherchez des réponses à vos questions de support.
      url: https://kb.netapp.com/
