---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation MetroCluster
    url: "/index.html"
  - section: releasenotes
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: Comprendre les fonctionnalités de protection des données et de reprise
      après incident d'MetroCluster
    entries:
    - title: Comment MetroCluster protège les données et assure la reprise après incident
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
