---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: 'À partir de ONTAP 9.13.1, vous pouvez effectuer la transition sans interruption des charges de travail et des données d"une configuration MetroCluster FC à huit nœuds existante vers une nouvelle configuration IP MetroCluster.' 
---
= Transition sans interruption d'une configuration MetroCluster FC vers une configuration MetroCluster IP (ONTAP 9.8 et versions ultérieures)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer des transitions de charges de travail et de données sans interruption depuis une configuration MetroCluster FC existante vers une nouvelle configuration MetroCluster IP.

À partir de ONTAP 9.13.1, cette procédure est prise en charge dans les configurations MetroCluster IP dans lesquelles le MetroCluster et les tiroirs disques sont connectés aux mêmes commutateurs IP (une configuration de commutateur de stockage partagé).

À partir d' ONTAP 9.13.1, vous pouvez effectuer une transition sans interruption des charges de travail et des données d'une configuration MetroCluster FC à huit nœuds existante vers une nouvelle configuration MetroCluster IP à huit nœuds.  Vous utilisez cette procédure pour faire basculer un groupe FC DR à quatre nœuds, supprimer le groupe FC DR vide, puis répéter la procédure pour le deuxième groupe FC DR. 

À partir d' ONTAP 9.8, vous pouvez effectuer une transition sans interruption des charges de travail et des données d'une configuration MetroCluster FC à quatre nœuds existante vers une nouvelle configuration MetroCluster IP à quatre nœuds.  Une fois la transition terminée, vous pouvez étendre votre configuration à huit nœuds MetroCluster IP si nécessaire. Voirlink:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["Développez une configuration MetroCluster IP"] .

* Cette procédure ne génère aucune interruption.
+
La configuration MetroCluster peut continuer à transmettre des données pendant l'opération.

* Cette procédure s'applique uniquement aux configurations FC MetroCluster à quatre et huit nœuds.
+
Si vous disposez d'une configuration FC MetroCluster à deux nœuds, reportez-vous à la section link:concept_choosing_your_transition_procedure_mcc_transition.html["Choix de la procédure de transition"].

* Cette procédure décrit les étapes nécessaires à la transition d'un groupe de reprise après incident FC à quatre nœuds. Si vous disposez d'une configuration à huit nœuds (deux groupes DR FC), vous devez répéter l'intégralité de la procédure pour chaque groupe DR FC.
+

NOTE: Lorsque vous ajoutez ou supprimez un groupe DR dans le cadre de cette procédure, vous devez vérifier que la suppression ou l'ajout du groupe DR a réussi avant d'ajouter ou de supprimer un autre groupe DR.

* Vous devez répondre à toutes les exigences et suivre toutes les étapes de la procédure.




== Scénarios de transition pris en charge par cette procédure

Consultez le tableau suivant pour en savoir plus sur les scénarios de transition pris en charge par cette procédure.


NOTE: Dans tous les scénarios de transition, vous ne pouvez ajouter ou supprimer qu'un seul groupe de reprise après sinistre à la fois. Après l'ajout ou la suppression réussie du groupe de reprise après sinistre, vous devez vérifier que le MetroCluster est sain et fonctionne normalement avant de poursuivre.

[cols="2*"]
|===
| Pour ce scénario de transition... | Effectuez les opérations suivantes... 


 a| 
Configuration FC à quatre nœuds vers configuration IP à quatre nœuds
 a| 
Suivez cette procédure à la lettre.



 a| 
Configuration FC à quatre nœuds vers configuration IP à huit nœuds
 a| 
Nécessite l'ajout d'un groupe IP DR MetroCluster. Après avoir ajouté le premier groupe IP DR MetroCluster, vérifiez l'état général du cluster et répétez les étapes pour le deuxième groupe IP DR MetroCluster.



 a| 
Configuration FC à huit nœuds vers configuration IP à quatre nœuds
 a| 
Suivez scrupuleusement cette procédure. Durant la transition, la configuration MetroCluster passera de huit à douze nœuds. Une fois la transition terminée et tous les nœuds FC MetroCluster déconnectés, la configuration finale sera une configuration IP MetroCluster à quatre nœuds.



 a| 
Configuration FC à huit nœuds vers IP à huit nœuds
 a| 
Cette transition nécessite l'ajout d'un groupe IP DR MetroCluster au cluster.

Après avoir vérifié l'intégrité de la configuration à douze nœuds, déplacez les données et les LIF (le cas échéant) d'un des groupes MetroCluster FC DR vers le groupe MetroCluster IP DR. Lorsqu'un des groupes MetroCluster FC DR est vide, supprimez ce groupe DR et retirez ces nœuds. La configuration résultante est un cluster à huit nœuds composé d'un groupe MetroCluster FC DR et d'un groupe MetroCluster IP DR.

Ensuite, ajoutez le deuxième groupe IP DR MetroCluster au cluster et effectuez la transition des données et des LIF (le cas échéant). Lorsque le dernier groupe FC DR MetroCluster restant est vide, supprimez-le et retirez ces nœuds du cluster.

À aucun moment durant la transition, le nombre de nœuds dans la MetroCluster configuration ne dépasse douze nœuds.

|===
Pour plus d'informations, consultez le link:concept_transition_workflow_fc_to_ip_transition.html["Flux de travail pour une transition MetroCluster sans interruption"].



== Informations importantes lors de l'ajout d'un modèle de plateforme plus ancien

Les conseils suivants concernent un scénario peu courant dans lequel vous devez ajouter un ancien modèle de plate-forme (plates-formes publiées avant ONTAP 9.15.1) à une configuration MetroCluster existante qui contient un modèle de plate-forme plus récent (plates-formes publiées dans ONTAP 9.15.1 ou plus récent). Pour une transition FC vers IP à huit nœuds, ce guide s'applique si vous avez fait la transition de votre premier groupe DR FC vers un modèle de plateforme introduit dans ONTAP 9.15.1 ou plus récent et que vous prévoyez de faire la transition du second groupe DR vers une plateforme introduite avant ONTAP 9.15.1.

Si votre configuration MetroCluster existante contient une plate-forme qui utilise des ports *shared cluster/HA* (plates-formes publiées dans ONTAP 9.15.1 ou plus tard), vous ne pouvez pas ajouter une plate-forme qui utilise des ports *shared MetroCluster/HA* (plates-formes publiées avant ONTAP 9.15.1) sans mettre à niveau tous les nœuds de la configuration vers ONTAP 9.15.1P11 ou ONTAP 9.16.1P4 ou plus tard.

[CAUTION]
====
L'ajout d'un ancien modèle de plate-forme qui utilise des ports *partagés/MetroCluster HA* à un MetroCluster contenant un modèle de plate-forme plus récent qui utilise des ports *partagés cluster/HA* est un scénario peu courant et la plupart des combinaisons ne sont pas affectées.

====
Utilisez le tableau suivant pour vérifier si votre combinaison est affectée. Si votre plate-forme existante est répertoriée dans la première colonne et que la plate-forme que vous souhaitez ajouter à la configuration est répertoriée dans la deuxième colonne, tous les nœuds de la configuration doivent exécuter ONTAP 9.15.1P11 ou ONTAP 9.16.1P4 ou une version ultérieure pour ajouter le nouveau groupe DR.

[cols="20,20,20,20,20"]
|===
2+| Si votre MetroCluster existant contient... 2+| Et la plateforme que vous ajoutez est... | Alors... 


 a| 
Un système AFF utilisant des *ports de cluster/HA partagés* :

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Un système FAS utilisant des *ports de cluster/HA partagés* :

* FAS50
* FAS70
* FAS90

 a| 
Un système AFF utilisant des *ports MetroCluster/HA partagés* :

* AFF A150, ASA A150
* AVEC AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Un système FAS utilisant des *ports MetroCluster/HA partagés* :

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Avant d'ajouter la nouvelle plateforme à votre configuration MetroCluster existante, mettez à niveau tous les nœuds de la configuration existante et nouvelle vers ONTAP 9.15.1P11 ou ONTAP 9.16.1P4 ou version ultérieure. 
|===