---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: Depuis ONTAP 9.8, la transition des charges de travail et des données sans interruption entre une configuration MetroCluster FC à quatre nœuds et une nouvelle configuration MetroCluster IP est prise en charge. 
---
= Transition sans interruption d'une configuration MetroCluster FC vers une configuration MetroCluster IP (ONTAP 9.8 et versions ultérieures)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.8, la transition des charges de travail et des données sans interruption entre une configuration MetroCluster FC à quatre nœuds et une nouvelle configuration MetroCluster IP est prise en charge.

* Cette procédure est prise en charge sur les systèmes exécutant ONTAP 9.8 et versions ultérieures.
* Cette procédure ne génère aucune interruption.
+
La configuration MetroCluster peut continuer à transmettre des données pendant l'opération.

* Cette procédure s'applique uniquement aux configurations FC MetroCluster à quatre nœuds.
+
Si vous disposez d'une configuration FC MetroCluster à deux nœuds, reportez-vous à la section link:concept_choosing_your_transition_procedure_mcc_transition.html["Choix de la procédure de transition"].

* Vous devez répondre à toutes les exigences et suivre toutes les étapes de la procédure.

