---
permalink: transition/concept_requirements_for_fc_to_ip_transition_mcc.html 
sidebar: sidebar 
keywords: start, transition, process, configuration, requirement, nondisruptive, fc-to-ip 
summary: Avant de lancer le processus de transition, vous devez vérifier que la configuration répond aux exigences. 
---
= Exigences relatives à la transition sans interruption de FC à IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de lancer le processus de transition, vous devez vérifier que la configuration répond aux exigences.

* Il doit s'agir d'une configuration à quatre nœuds et tous les nœuds doivent exécuter ONTAP 9.8 ou une version ultérieure.
* Les plateformes existantes et nouvelles doivent être prises en charge pour la transition.
+
link:concept_supported_platforms_for_transition.html["Plateformes prises en charge pour une transition sans interruption"]

* Il doit prendre en charge une configuration de cluster commuté.
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* Il doit répondre à toutes les exigences et à tous les câbles, comme décrit dans les procédures _MetroCluster installation and Configuration_.
+
link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]

+
link:../install-stretch/concept_considerations_differences.html["Installation et configuration d'Stretch MetroCluster"]


