---
permalink: transition/reference_where_to_find_additional_information_mcc_ug.html 
sidebar: sidebar 
keywords: metrocluster, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: 'Pour plus d"informations sur la configuration et le fonctionnement de MetroCluster, consultez la documentation NetApp.' 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur la configuration MetroCluster,



== MetroCluster et informations diverses

|===


| Informations | Objet 


 a| 
link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]
 a| 
* Architecture Fabric-Attached MetroCluster
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration des commutateurs FC
* Configuration de MetroCluster dans ONTAP




 a| 
link:../install-stretch/concept_considerations_differences.html["Installation et configuration d'Stretch MetroCluster"]
 a| 
* Architecture MetroCluster extensible
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration de MetroCluster dans ONTAP




 a| 
link:../manage/index.html["Gestion MetroCluster"]
 a| 
* Présentation de la configuration MetroCluster
* Basculement, rétablissement et rétablissement




 a| 
link:../disaster-recovery/concept_dr_workflow.html["Reprise sur incident"]
 a| 
* Reprise après incident
* Basculement forcé
* La restauration après une panne de plusieurs contrôleurs ou de stockage




 a| 
link:../maintain/index.html["Maintenance MetroCluster"]
 a| 
* Instructions relatives à la maintenance dans une configuration MetroCluster FC
* Procédure de remplacement ou de mise à niveau du matériel et de mise à niveau du firmware pour les ponts FC-SAS et les commutateurs FC
* Ajout à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Retrait à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Remplacement du matériel sur un site d'incident dans une configuration MetroCluster FC Stretch ou Fabric-Attached
* Extension d'une configuration MetroCluster FC extensible ou Fabric-Attached à deux nœuds à une configuration MetroCluster à quatre nœuds.
* Extension d'une configuration MetroCluster FC à quatre nœuds (Fabric-Attached ou Stretch FC) à une configuration MetroCluster FC à huit nœuds.




 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Mise à niveau et extension de MetroCluster"]
 a| 
* Mise à niveau ou actualisation d'une configuration MetroCluster
* Extension d'une configuration MetroCluster par l'ajout de nœuds supplémentaires




 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["Transition MetroCluster"]
 a| 
* Passer d'une configuration MetroCluster FC à une configuration MetroCluster IP




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Mise à niveau, transition et extension de MetroCluster"]
 a| 
* Contrôle de la configuration de MetroCluster avec le logiciel MetroCluster Tiebreaker




 a| 
https://docs.netapp.com/us-en/ontap-systems/["Documentation des systèmes matériels ONTAP"^]

*Remarque :* les procédures de maintenance standard des tiroirs de stockage peuvent être utilisées avec les configurations IP de MetroCluster.
 a| 
* Ajout à chaud d'un tiroir disque
* Retrait à chaud d'un tiroir disque




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transition basée sur la copie"^]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["Concepts relatifs à ONTAP"^]
 a| 
* Fonctionnement des agrégats en miroir


|===