---
permalink: transition/task_move_data_to_new_drive_shelves.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Pendant la transition, vous déplacez les données des tiroirs disques de la configuration FC MetroCluster vers la nouvelle configuration IP MetroCluster. 
---
= Déplacement des données vers les nouveaux tiroirs disques
:allow-uri-read: 


[role="lead"]
Pendant la transition, vous déplacez les données des tiroirs disques de la configuration FC MetroCluster vers la nouvelle configuration IP MetroCluster.

.Avant de commencer
Vous devez créer de nouvelles LIF SAN sur les nœuds de destination ou IP et connecter les hôtes avant de déplacer des volumes vers les nouveaux agrégats.

. Pour reprendre la génération automatique de dossier de support, envoyez un message AutoSupport pour indiquer que la maintenance est terminée.
+
.. Exécutez la commande suivante : `system node autosupport invoke -node * -type all -message MAINT=end`
.. Répétez la commande sur le cluster partenaire.


. Déplacez les volumes de données vers des agrégats des nouveaux contrôleurs, un volume à la fois.
+
Suivre la procédure décrite dans http://["Création d'un agrégat et déplacement des volumes vers les nouveaux nœuds"].

. Créez des LIF SAN sur les nœuds récemment ajoutés.
+
Suivre la procédure suivante dans http://["Mise à jour des chemins de LUN pour les nouveaux nœuds"^].

. Vérifiez si des licences de nœud sont verrouillées dans les nœuds FC. S'il y a, elles doivent être ajoutées aux nouveaux nœuds ajoutés.
+
Suivre la procédure suivante dans http://["Ajout de licences verrouillées par des nœuds"^].

. Migrer les LIF de données.
+
Suivre la procédure décrite dans  http://["Déplacement des LIF de données non-SAN et des LIF de gestion du cluster vers les nouveaux nœuds"^] Mais n'effectuez *pas* les deux dernières étapes pour migrer les LIF de gestion du cluster.



[NOTE]
====
* Vous ne pouvez pas migrer une LIF utilisée pour effectuer des opérations de déchargement des copies avec VMware vStorage APIs for Array Integration (VAAI).
* Une fois la transition de vos nœuds MetroCluster de FC vers IP terminée, vous devrez peut-être déplacer vos connexions hôtes iSCSI vers les nouveaux nœuds, voir link:task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html["Déplacement des hôtes iSCSI Linux depuis les nœuds FC MetroCluster vers les nœuds IP MetroCluster."]


====