---
permalink: transition/task_move_cluster_connections.html 
sidebar: sidebar 
keywords: transition, cluster connections 
summary: 'Après avoir passé en revue toutes les exigences et préparé la transition, vous effectuez la procédure de transition. Vous devez effectuer chaque tâche dans l"ordre, en effectuant toutes les étapes de chaque tâche avant de passer à la suivante. Vous ne devez pas connecter les nouveaux contrôleurs ou tiroirs de stockage à la configuration existante tant qu"ils ne sont pas dirigées.' 
---
= Déplacez les connexions locales du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez déplacer les interfaces de cluster de la configuration MetroCluster FC vers les commutateurs IP.



== Déplacez les connexions du cluster sur les nœuds FC MetroCluster

Vous devez déplacer les connexions du cluster sur les nœuds FC MetroCluster vers les commutateurs IP. Les étapes dépendent de l'utilisation des commutateurs IP existants ou de l'utilisation de nouveaux commutateurs IP.

Vous devez effectuer cette tâche sur les deux sites MetroCluster.



=== Les connexions à déplacer

La tâche suivante suppose qu'un module de contrôleur utilise deux ports pour les connexions de cluster. Certains modèles de modules de contrôleur utilisent au moins quatre ports pour la connexion en cluster. Dans ce cas, aux fins de cet exemple, les ports sont divisés en deux groupes, alternant les ports entre les deux groupes

Le tableau suivant présente les exemples de ports utilisés dans cette tâche.

|===


| Nombre de connexions de cluster sur le module de contrôleur | Regrouper les ports | Ports du groupe B. 


 a| 
Deux
 a| 
e0a
 a| 
e0b



 a| 
Quatre
 a| 
e0a, e0c
 a| 
e0b, e0d

|===
* Les ports du groupe A se connectent au commutateur local switch switch_x_1-IP.
* Les ports du groupe B se connectent au commutateur local switch_x_2-IP.


Le tableau suivant indique les ports de switch auxquels les nœuds FC se connectent. Pour le commutateur Broadcom BES-53248, l'utilisation des ports dépend du modèle des nœuds IP MetroCluster.

|===


| Changer de modèle | Modèle de nœud IP MetroCluster | Port(s) du commutateur | Se connecte à 


| Cisco 3132Q-V  a| 
Toutes
 a| 
5, 6
 a| 
Interface de cluster locale sur un nœud FC



 a| 
Cisco 3232C ou 9336C-FX2
 a| 
Toutes
 a| 
5, 6 ou 13, 14

*Remarque :* les ports de commutation 13 et 14 ne peuvent être utilisés que lorsque vous sélectionnez deux modes de vitesse.
 a| 
Interface de cluster locale sur un nœud FC



 a| 
Cisco 9336C-FX2 partagé
 a| 
Toutes
 a| 
3, 4 ou 11, 12

*Remarque :* les ports de commutation 11 et 12 ne peuvent être utilisés que lorsque vous sélectionnez deux modes de vitesse.
 a| 
Interface de cluster locale sur un nœud FC



.3+| Broadcom BES-53248  a| 
FAS500f/A250
 a| 
1 - 6
 a| 
Interface de cluster locale sur un nœud FC



 a| 
FAS8200/A300
 a| 
3, 4, 9, 10, 11, 12
 a| 
Interface de cluster locale sur un nœud FC



 a| 
FAS8300/A400/FAS8700
 a| 
1 - 6
 a| 
Interface de cluster locale sur un nœud FC



 a| 
NVIDIA SN2100
 a| 
Toutes
 a| 
5, 6 ou 11, 12

*Remarque :* les ports de commutation 11 et 12 ne peuvent être utilisés que lorsque vous sélectionnez deux modes de vitesse.
 a| 
Interface de cluster locale sur un nœud FC

|===


=== Déplacement des connexions du cluster local lors de l'utilisation de nouveaux commutateurs IP

Si vous utilisez de nouveaux commutateurs IP, vous devez déplacer physiquement les connexions de cluster des nœuds FC MetroCluster existants vers les nouveaux commutateurs.

. Déplacez les connexions du cluster au groupe de nœuds FC MetroCluster avec les nouveaux commutateurs IP.
+
Utilisez les ports décrits dans <<Les connexions à déplacer>>.

+
.. Déconnecter tous les ports du groupe A du commutateur ou, si la configuration MetroCluster FC était un cluster sans commutateur, les déconnecter du nœud partenaire.
.. Déconnectez les ports du groupe A du nœud_A_1-FC et du nœud_A_2-FC.
.. Connectez les ports group A de node_A_1-FC aux ports de switch du nœud FC sur switch_A_1-IP
.. Connectez les ports group A de node_A_2-FC aux ports de switch du nœud FC sur switch_A_1-IP


. Vérifier que tous les ports du cluster sont bien :
+
`network port show -ipspace Cluster`

+
....
cluster_A::*> network port show -ipspace Cluster

Node: node_A_1-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

cluster_A::*>
....
. Vérifiez que vos liaisons intersites ISL sont opérationnelles et que les canaux de port sont opérationnels :
+
`show interface brief`

+
Dans l’exemple suivant, les ports ISL “eth1/15” à “eth1/20” sont configurés comme “Po10” pour la liaison du site distant et “eth1/7” à “eth1/8” sont configurés comme “Po1” pour le cluster ISL local. L'état "eth1/15" à "eth1/20", "eth1/7" à "eth1/8", "Po10" et "Po1" devrait être "UP".

+
[listing]
----
IP_switch_A_1# show interface brief

--------------------------------------------------------------
Port   VRF          Status   IP Address        Speed      MTU
--------------------------------------------------------------
mgmt0  --            up        100.10.200.20    1000      1500
--------------------------------------------------------------------------------
Ethernet     VLAN   Type Mode    Status     Reason              Speed    Port
Interface                                    Ch #
--------------------------------------------------------------------------------

...

Eth1/7        1     eth  trunk    up        none                100G(D)    1
Eth1/8        1     eth  trunk    up        none                100G(D)    1

...

Eth1/15       1     eth  trunk    up        none                100G(D)    10
Eth1/16       1     eth  trunk    up        none                100G(D)    10
Eth1/17       1     eth  trunk    up        none                100G(D)    10
Eth1/18       1     eth  trunk    up        none                100G(D)    10
Eth1/19       1     eth  trunk    up        none                100G(D)    10
Eth1/20       1     eth  trunk    up        none                100G(D)    10

--------------------------------------------------------------------------------
Port-channel VLAN  Type Mode   Status   Reason         Speed    Protocol
Interface
--------------------------------------------------------------------------------
Po1          1     eth  trunk   up      none            a-100G(D) lacp
Po10         1     eth  trunk   up      none            a-100G(D) lacp
Po11         1     eth  trunk   down    No operational  auto(D)   lacp
                                        members
IP_switch_A_1#
----
. Vérifiez que toutes les interfaces s'affichent true dans la colonne « est à l'origine » :
+
`network interface show -vserver cluster`

+
Cette opération peut prendre plusieurs minutes.

+
....
cluster_A::*> network interface show -vserver cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1_FC_clus1
                       up/up      169.254.209.69/16  node_A_1_FC   e0a     true
            node_A_1-FC_clus2
                       up/up      169.254.49.125/16  node_A_1-FC   e0b     true
            node_A_2-FC_clus1
                       up/up      169.254.47.194/16  node_A_2-FC   e0a     true
            node_A_2-FC_clus2
                       up/up      169.254.19.183/16  node_A_2-FC   e0b     true

4 entries were displayed.

cluster_A::*>
....
. Effectuez les étapes ci-dessus sur les deux nœuds (node_A_1-FC et node_A_2-FC) pour déplacer les ports group B des interfaces cluster.
. Répétez les étapes ci-dessus sur le cluster partenaire « cluster_B ».




=== Déplacement des connexions du cluster local lors de la réutilisation des commutateurs IP existants

Si vous réutilisez des commutateurs IP existants, vous devez mettre à jour le micrologiciel, reconfigurer les commutateurs avec les fichiers de configuration de référence (RCFs) corrects et déplacer les connexions vers les ports corrects un commutateur à la fois.

Cette tâche est requise uniquement si les nœuds FC sont connectés à des commutateurs IP existants et que vous réutilisez les commutateurs.

. Déconnectez les connexions locales du cluster qui se connectent au commutateur_A_1_IP
+
.. Déconnectez les ports du groupe A du commutateur IP existant.
.. Déconnectez les ports ISL de switch_A_1_IP.
+
Vous pouvez voir les instructions d'installation et de configuration de la plate-forme pour voir l'utilisation du port du cluster.

+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["Systèmes AFF A320 : installation et configuration"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["Instructions d'installation et de configuration des systèmes AFF A220/FAS2700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["Instructions d'installation et de configuration des systèmes AFF A800"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["Instructions d'installation et de configuration des systèmes AFF A300"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["Instructions d'installation et de configuration du système FAS8200"^]



. Reconfigurez Switch_A_1_IP à l'aide de fichiers RCF générés pour la combinaison de votre plateforme et la transition.
+
Suivez les étapes de la procédure pour votre fournisseur de commutateur à partir de _MetroCluster IP installation and Configuration_:

+
link:../install-ip/concept_considerations_differences.html["Installation et configuration de MetroCluster IP"]

+
.. Si nécessaire, téléchargez et installez le nouveau micrologiciel du commutateur.
+
Vous devez utiliser le dernier firmware pris en charge par les nœuds IP MetroCluster.

+
*** link:../install-ip/task_switch_config_broadcom.html["Téléchargez et installez le logiciel EFOS du commutateur Broadcom"]
*** link:../install-ip/task_switch_config_cisco.html["Téléchargez et installez le logiciel Cisco switch NX-OS"]
*** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Téléchargez et installez le logiciel NVIDIA Cumulus"]


.. Préparez les commutateurs IP pour l'application des nouveaux fichiers RCF.
+
*** link:../install-ip/task_switch_config_broadcom.html["Réinitialisez les paramètres par défaut du commutateur IP Broadcom"]
*** link:../install-ip/task_switch_config_cisco.html["Réinitialisez le commutateur IP Cisco sur les paramètres d'usine par défaut"]
*** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Réinitialisez les paramètres par défaut du commutateur NVIDIA IP SN2100"]


.. Téléchargez et installez le fichier RCF IP selon votre fournisseur de commutateur.
+
*** link:../install-ip/task_switch_config_broadcom.html["Téléchargez et installez les fichiers Broadcom IP RCF"]
*** link:../install-ip/task_switch_config_cisco.html["Téléchargez et installez les fichiers Cisco IP RCF"]
*** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Téléchargez et installez les fichiers NVIDIA RCF"]




. Reconnectez les ports du groupe A à switch_A_1_IP.
+
Utilisez les ports décrits dans <<Les connexions à déplacer>>.

. Vérifier que tous les ports du cluster sont bien :
+
`network port show -ipspace cluster`

+
....
Cluster-A::*> network port show -ipspace cluster

Node: node_A_1_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

Cluster-A::*>
....
. Vérifiez que toutes les interfaces se trouvent sur leur port de départ :
+
`network interface show -vserver Cluster`

+
....
Cluster-A::*> network interface show -vserver Cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1_FC_clus1
                       up/up      169.254.209.69/16  node_A_1_FC   e0a     true
            node_A_1_FC_clus2
                       up/up      169.254.49.125/16  node_A_1_FC   e0b     true
            node_A_2_FC_clus1
                       up/up      169.254.47.194/16  node_A_2_FC   e0a     true
            node_A_2_FC_clus2
                       up/up      169.254.19.183/16  node_A_2_FC   e0b     true

4 entries were displayed.

Cluster-A::*>
....
. Répétez toutes les étapes précédentes sur switch_A_2_IP.
. Reconnectez les ports locaux ISL du cluster.
. Répétez les étapes ci-dessus à site_B pour le commutateur B_1_IP et le commutateur B_2_IP.
. Connectez les liens ISL distants entre les sites.




== Vérification que les connexions du cluster sont déplacées et que le cluster fonctionne correctement

Pour s'assurer que la connectivité est appropriée et que la configuration est prête à continuer le processus de transition, vous devez vérifier que les connexions du cluster sont correctement déplacées, que les commutateurs du cluster sont reconnus et que le cluster fonctionne correctement.

. Vérifier que tous les ports du cluster sont opérationnels :
+
`network port show -ipspace Cluster`

+
....
Cluster-A::*> network port show -ipspace Cluster

Node: Node-A-1-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: Node-A-2-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

Cluster-A::*>
....
. Vérifiez que toutes les interfaces se trouvent sur leur port de départ :
+
`network interface show -vserver Cluster`

+
Cette opération peut prendre plusieurs minutes.

+
L'exemple suivant montre que toutes les interfaces sont vraies dans la colonne « is Home ».

+
....
Cluster-A::*> network interface show -vserver Cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            Node-A-1_FC_clus1
                       up/up      169.254.209.69/16  Node-A-1_FC   e0a     true
            Node-A-1-FC_clus2
                       up/up      169.254.49.125/16  Node-A-1-FC   e0b     true
            Node-A-2-FC_clus1
                       up/up      169.254.47.194/16  Node-A-2-FC   e0a     true
            Node-A-2-FC_clus2
                       up/up      169.254.19.183/16  Node-A-2-FC   e0b     true

4 entries were displayed.

Cluster-A::*>
....
. Vérifiez que les deux commutateurs IP locaux sont détectés par les nœuds :
+
`network device-discovery show -protocol cdp`

+
....
Cluster-A::*> network device-discovery show -protocol cdp

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
Node-A-1-FC
           /cdp
            e0a    Switch-A-3-IP             1/5/1             N3K-C3232C
            e0b    Switch-A-4-IP             0/5/1             N3K-C3232C
Node-A-2-FC
           /cdp
            e0a    Switch-A-3-IP             1/6/1             N3K-C3232C
            e0b    Switch-A-4-IP             0/6/1             N3K-C3232C

4 entries were displayed.

Cluster-A::*>
....
. Sur le commutateur IP, vérifiez que les nœuds IP MetroCluster ont été détectés par les deux commutateurs IP locaux :
+
`show cdp neighbors`

+
Vous devez effectuer cette étape sur chaque commutateur.

+
Cet exemple montre comment vérifier que les nœuds sont détectés sur Switch-A-3-IP.

+
....
(Switch-A-3-IP)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Node-A-1-FC         Eth1/5/1       133    H         FAS8200       e0a
Node-A-2-FC         Eth1/6/1       133    H         FAS8200       e0a
Switch-A-4-IP(FDO220329A4)
                    Eth1/7         175    R S I s   N3K-C3232C    Eth1/7
Switch-A-4-IP(FDO220329A4)
                    Eth1/8         175    R S I s   N3K-C3232C    Eth1/8
Switch-B-3-IP(FDO220329B3)
                    Eth1/20        173    R S I s   N3K-C3232C    Eth1/20
Switch-B-3-IP(FDO220329B3)
                    Eth1/21        173    R S I s   N3K-C3232C    Eth1/21

Total entries displayed: 4

(Switch-A-3-IP)#
....
+
Cet exemple montre comment vérifier que les nœuds sont détectés sur Switch-A-4-IP.

+
....
(Switch-A-4-IP)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Node-A-1-FC         Eth1/5/1       133    H         FAS8200       e0b
Node-A-2-FC         Eth1/6/1       133    H         FAS8200       e0b
Switch-A-3-IP(FDO220329A3)
                    Eth1/7         175    R S I s   N3K-C3232C    Eth1/7
Switch-A-3-IP(FDO220329A3)
                    Eth1/8         175    R S I s   N3K-C3232C    Eth1/8
Switch-B-4-IP(FDO220329B4)
                    Eth1/20        169    R S I s   N3K-C3232C    Eth1/20
Switch-B-4-IP(FDO220329B4)
                    Eth1/21        169    R S I s   N3K-C3232C    Eth1/21

Total entries displayed: 4

(Switch-A-4-IP)#
....

