---
permalink: transition/task_remove_tiebreaker_4n_transition.html 
sidebar: sidebar 
keywords: Transitioning from MetroCluster FC to MetroCluster IP configurations, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 'Si la configuration existante est contrôlée avec la configuration MetroCluster Tiebreaker ou d"autres applications tierces (telles que ClusterLion) capables d"effectuer un basculement, vous devez supprimer la configuration MetroCluster du logiciel disjoncteur d"attache ou d"autres logiciels avant la transition.' 
---
= Suppression de la configuration existante du logiciel disjoncteur d'attache ou autre logiciel de surveillance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la configuration existante est contrôlée avec la configuration MetroCluster Tiebreaker ou d'autres applications tierces (telles que ClusterLion) capables d'effectuer un basculement, vous devez supprimer la configuration MetroCluster du logiciel disjoncteur d'attache ou d'autres logiciels avant la transition.

. Supprimer la configuration MetroCluster existante du logiciel disjoncteur d'attache
+
http://["Suppression des configurations MetroCluster"]

. Supprimez la configuration MetroCluster existante de toute application tierce pouvant effectuer le basculement.
+
Reportez-vous à la documentation de l'application.


