---
permalink: transition/task_remove_mc_fc_controllers.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Pour préparer la configuration à la transition, vous ajoutez les nouveaux nœuds à la configuration MetroCluster existante, puis déplacez les données vers les nouveaux nœuds. 
---
= Retrait des contrôleurs FC MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez effectuer des tâches de nettoyage et retirer les anciens modules de contrôleur de la configuration MetroCluster.

. Pour éviter la génération automatique de dossiers de demande de support, envoyez un message AutoSupport pour indiquer que la maintenance est en cours.
+
.. Exécutez la commande suivante : `system node autosupport invoke -node * -type all -message MAINT=maintenance-window-in-hours`
+
la fenêtre de maintenance en heures spécifie la durée de la fenêtre de maintenance, avec un maximum de 72 heures. Si la maintenance est terminée avant le temps écoulé, vous pouvez appeler un message AutoSupport indiquant la fin de la période de maintenance :``system node autosupport invoke -node * -type all -message MAINT=end``

.. Répétez la commande sur le cluster partenaire.


. Identifiez les agrégats hébergés sur la configuration MetroCluster FC qui doivent être supprimés.
+
Dans cet exemple, les agrégats de données suivants sont hébergés sur le cluster MetroCluster FC cluster_B et doivent être supprimés : aggr_Data_a1 et aggr_Data_a2.

+

NOTE: Les étapes permettant d'identifier, de mettre hors ligne et de supprimer les agrégats de données sur les deux clusters sont nécessaires. L'exemple est pour un seul cluster.

+
....
cluster_B::> aggr show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_node_A_1-FC
           349.0GB   16.83GB   95% online       1 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_2-FC
           349.0GB   16.83GB   95% online       1 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.63GB   95% online       1 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.62GB   95% online       1 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a1
            1.02TB    1.02TB    0% online       0 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a2
            1.02TB    1.02TB    0% online       0 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a3
            1.37TB    1.35TB    1% online       3 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a4
            1.25TB    1.24TB    1% online       2 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
8 entries were displayed.

cluster_B::>
....
. Vérifiez si les agrégats de données des nœuds FC ont des volumes MDV_aud et supprimez-les avant de supprimer les agrégats.
+
Vous devez supprimer les volumes MDV_aud car ils ne peuvent pas être déplacés.

. Mettre hors ligne chacun des agrégats de données, puis les supprimer :
+
.. Mettre l'agrégat hors ligne : `storage aggregate offline -aggregate aggregate-name`
+
L'exemple suivant montre l'agrégat aggr_data_a1 mis hors ligne :

+
....
cluster_B::> storage aggregate offline -aggregate aggr_data_a1

Aggregate offline successful on aggregate: aggr_data_a1
....
.. Supprimer l'agrégat : `storage aggregate delete -aggregate aggregate-name`
+
Vous pouvez détruire le plex lorsque vous y êtes invité.

+
L'exemple suivant montre l'agrégat aggr_data_a1 en cours de suppression.

+
....
cluster_B::> storage aggregate delete -aggregate aggr_data_a1
Warning: Are you sure you want to destroy aggregate "aggr_data_a1"? {y|n}: y
[Job 123] Job succeeded: DONE

cluster_B::>
....


. Identifiez le groupe de reprise après incident FC MetroCluster à supprimer.
+
Dans l'exemple suivant, les nœuds FC MetroCluster se trouvent dans le groupe DR '1', et il s'agit du groupe de reprise sur incident à supprimer.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        configured     enabled   normal
              node_A_2-FC        configured     enabled   normal
      cluster_B
              node_B_1-FC        configured     enabled   normal
              node_B_2-FC        configured     enabled   normal
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_3-IP        configured     enabled   normal
8 entries were displayed.

cluster_B::>
....
. Déplacer la LIF de cluster management d'un nœud FC MetroCluster vers un nœud IP MetroCluster : `cluster_B::> network interface migrate -vserver svm-name -lif cluster_mgmt -destination-node node-in-metrocluster-ip-dr-group -destination-port available-port`
. Modifier le home node et le home port du cluster management LIF : `cluster_B::> network interface modify -vserver svm-name -lif cluster_mgmt -service-policy default-management -home-node node-in-metrocluster-ip-dr-group -home-port lif-port`
. Déplacement d'epsilon d'un nœud FC MetroCluster vers un nœud IP MetroCluster :
+
.. Identifier le nœud qui possède actuellement epsilon : `cluster show -fields epsilon`
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      true
node_A_2-FC      false
node_A_1-IP      false
node_A_2-IP      false
4 entries were displayed.
....
.. Définir epsilon sur false sur le nœud FC MetroCluster (node_A_1-FC) : `cluster modify -node fc-node -epsilon false`
.. Défini sur true sur le nœud IP de MetroCluster (node_A_1-IP) : `cluster modify -node ip-node -epsilon true`
.. Vérifier que epsilon a déplacé vers le nœud approprié : `cluster show -fields epsilon`
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      false
node_A_2-FC      false
node_A_1-IP      true
node_A_2-IP      false
4 entries were displayed.
....


. Modifiez l'adresse IP de l'homologue de cluster des nœuds IP transférés pour chaque cluster :
+
.. Identifiez l'homologue cluster_A à l'aide de `cluster peer show` commande :
+
[listing]
----
cluster_A::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
cluster_B         1-80-000011           Unavailable    absent
----
+
... Modifiez l'adresse IP du poste cluster_A :
+
`cluster peer modify -cluster cluster_A -peer-addrs node_A_3_IP -address-family ipv4`



.. Identifiez l'homologue cluster_B à l'aide de `cluster peer show` commande :
+
[listing]
----
cluster_B::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
cluster_A         1-80-000011           Unavailable    absent
----
+
... Modifiez l'adresse IP de l'homologue cluster_B :
+
`cluster peer modify -cluster cluster_B -peer-addrs node_B_3_IP -address-family ipv4`



.. Vérifiez que l'adresse IP de l'homologue de cluster est mise à jour pour chaque cluster :
+
... Vérifiez que l'adresse IP est mise à jour pour chaque cluster à l'aide de `cluster peer show -instance` commande.
+
Le `Remote Intercluster Addresses` Dans les exemples suivants, le champ affiche l'adresse IP mise à jour.

+
Exemple pour cluster_A :

+
[listing]
----
cluster_A::> cluster peer show -instance

Peer Cluster Name: cluster_B
           Remote Intercluster Addresses: 172.21.178.204, 172.21.178.212
      Availability of the Remote Cluster: Available
                     Remote Cluster Name: cluster_B
                     Active IP Addresses: 172.21.178.212, 172.21.178.204
                   Cluster Serial Number: 1-80-000011
                    Remote Cluster Nodes: node_B_3-IP,
                                          node_B_4-IP
                   Remote Cluster Health: true
                 Unreachable Local Nodes: -
          Address Family of Relationship: ipv4
    Authentication Status Administrative: use-authentication
       Authentication Status Operational: ok
                        Last Update Time: 4/20/2023 18:23:53
            IPspace for the Relationship: Default
Proposed Setting for Encryption of Inter-Cluster Communication: -
Encryption Protocol For Inter-Cluster Communication: tls-psk
  Algorithm By Which the PSK Was Derived: jpake

cluster_A::>

----
+
Exemple pour cluster_B.

+
[listing]
----
cluster_B::> cluster peer show -instance

                       Peer Cluster Name: cluster_A
           Remote Intercluster Addresses: 172.21.178.188, 172.21.178.196 <<<<<<<< Should reflect the modified address
      Availability of the Remote Cluster: Available
                     Remote Cluster Name: cluster_A
                     Active IP Addresses: 172.21.178.196, 172.21.178.188
                   Cluster Serial Number: 1-80-000011
                    Remote Cluster Nodes: node_A_3-IP,
                                          node_A_4-IP
                   Remote Cluster Health: true
                 Unreachable Local Nodes: -
          Address Family of Relationship: ipv4
    Authentication Status Administrative: use-authentication
       Authentication Status Operational: ok
                        Last Update Time: 4/20/2023 18:23:53
            IPspace for the Relationship: Default
Proposed Setting for Encryption of Inter-Cluster Communication: -
Encryption Protocol For Inter-Cluster Communication: tls-psk
  Algorithm By Which the PSK Was Derived: jpake

cluster_B::>
----




. Sur chaque cluster, retirer le groupe de reprise après incident contenant les anciens nœuds de la configuration MetroCluster FC.
+
Vous devez effectuer cette étape sur les deux clusters, un à la fois.

+
....
cluster_B::> metrocluster remove-dr-group -dr-group-id 1

Warning: Nodes in the DR group that are removed from the MetroCluster
         configuration will lose their disaster recovery protection.

         Local nodes "node_A_1-FC, node_A_2-FC" will be removed from the
         MetroCluster configuration. You must repeat the operation on the
         partner cluster "cluster_B" to remove the remote nodes in the DR group.
Do you want to continue? {y|n}: y

Info: The following preparation steps must be completed on the local and partner
      clusters before removing a DR group.

      1. Move all data volumes to another DR group.
      2. Move all MDV_CRS metadata volumes to another DR group.
      3. Delete all MDV_aud metadata volumes that may exist in the DR group to
      be removed.
      4. Delete all data aggregates in the DR group to be removed. Root
      aggregates are not deleted.
      5. Migrate all data LIFs to home nodes in another DR group.
      6. Migrate the cluster management LIF to a home node in another DR group.
      Node management and inter-cluster LIFs are not migrated.
      7. Transfer epsilon to a node in another DR group.

      The command is vetoed ifthe preparation steps are not completed on the
      local and partner clusters.
Do you want to continue? {y|n}: y
[Job 513] Job succeeded: Remove DR Group is successful.

cluster_B::>
....
. Vérifiez que les nœuds sont prêts à être supprimés des clusters.
+
Vous devez effectuer cette étape sur les deux clusters.

+

NOTE: À ce stade, le `metrocluster node show` La commande n'affiche que les nœuds FC MetroCluster locaux et n'affiche plus les nœuds qui font partie du cluster partenaire.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        ready to configure
                                                -         -
              node_A_2-FC        ready to configure
                                                -         -
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_4-IP        configured     enabled   normal
6 entries were displayed.

cluster_B::>
....
. Désactiver le basculement du stockage pour les nœuds FC MetroCluster.
+
Vous devez effectuer cette étape sur chaque nœud.

+
....
cluster_A::> storage failover modify -node node_A_1-FC -enabled false
cluster_A::> storage failover modify -node node_A_2-FC -enabled false
cluster_A::>
....
. Déconnecter les nœuds MetroCluster FC des clusters : `cluster unjoin -node node-name`
+
Vous devez effectuer cette étape sur chaque nœud.

+
....
cluster_A::> cluster unjoin -node node_A_1-FC

Warning: This command will remove node "node_A_1-FC"from the cluster. You must
         remove the failover partner as well. After the node is removed, erase
         its configuration and initialize all disks by usingthe "Clean
         configuration and initialize all disks (4)" option from the boot menu.
Do you want to continue? {y|n}: y
[Job 553] Job is queued: Cluster remove-node of Node:node_A_1-FC with UUID:6c87de7e-ff54-11e9-8371
[Job 553] Checking prerequisites
[Job 553] Cleaning cluster database
[Job 553] Job succeeded: Node remove succeeded
If applicable, also remove the node's HA partner, and then clean its configuration and initialize all disks with the boot menu.
Run "debug vreport show" to address remaining aggregate or volume issues.

cluster_B::>
....
. Mettez les modules de contrôleur FC MetroCluster et les tiroirs de stockage hors tension.
. Déconnecter et retirer les modules de contrôleur FC MetroCluster et les tiroirs de stockage.

