---
permalink: transition/task_apply_rcfs.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Si vous utilisez de nouveaux commutateurs IP pour la configuration IP MetroCluster, vous devez configurer les switchs avec un fichier RCF personnalisé. 
---
= Génération et application des RCFC aux nouveaux commutateurs IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez de nouveaux commutateurs IP pour la configuration IP MetroCluster, vous devez configurer les switchs avec un fichier RCF personnalisé.

Cette tâche est requise si vous utilisez de nouveaux commutateurs.

Si vous utilisez des commutateurs existants, passer à link:task_move_cluster_connections.html["Déplacement des connexions locales du cluster"].

. Installez et installez les nouveaux commutateurs IP dans leur rack.
. Préparez les commutateurs IP pour l'application des nouveaux fichiers RCF.
+
Suivez les étapes de la section pour votre fournisseur de commutateurs :

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Réinitialisez les paramètres par défaut du commutateur IP Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Réinitialisez le commutateur IP Cisco sur les paramètres d'usine par défaut"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Réinitialisez les paramètres par défaut du commutateur NVIDIA IP SN2100"]


. Mettez à jour le micrologiciel du commutateur vers une version prise en charge, si nécessaire.
. Utilisez l'outil FCR Generator pour créer le fichier RCF en fonction de votre fournisseur de commutateur et des modèles de plateforme, puis mettez à jour les switchs avec le fichier.
+
Suivez les étapes de la section pour votre fournisseur de commutateurs :

+
** link:../install-ip/task_switch_config_broadcom.html["Téléchargez et installez les fichiers RCF IP Broadcom"]
** link:../install-ip/task_switch_config_cisco.html["Téléchargez et installez les fichiers RCF IP Cisco"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Téléchargez et installez les fichiers NVIDIA RCF"]



