---
permalink: transition/task_move_an_fc_san_workload_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: non-disruptively, transition, metrocluster, fc, ip, node, san, host, moving, move 
summary: 'Lors de la transition entre des nœuds FC de MetroCluster et des nœuds IP sans interruption, vous devez déplacer des objets hôte SAN FC de MetroCluster vers des nœuds IP, sans interrompre l"activité.' 
---
= Déplacement d'une charge de travail SAN FC des nœuds FC MetroCluster vers les nœuds IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la transition entre des nœuds FC de MetroCluster et des nœuds IP sans interruption, vous devez déplacer des objets hôte SAN FC de MetroCluster vers des nœuds IP, sans interrompre l'activité.



== Déplacez une charge de travail SAN FC des nœuds FC MetroCluster vers les nœuds IP MetroCluster

.Étapes
. Configuration des nouvelles interfaces FC (LIF) sur les nœuds IP MetroCluster :
+
.. Si nécessaire, sur les nœuds IP MetroCluster, modifiez les ports FC à utiliser pour la connectivité client et la personnalité de la cible FC.
+
Cela peut nécessiter un redémarrage des nœuds.

.. Créez des LIF/interfaces FC sur des nœuds IP pour tous les SVM SAN. Vérifiez éventuellement que les WWPN des LIF FC nouvellement créées sont connectés au commutateur FC SAN


. Mettre à jour la configuration de la segmentation SAN pour les LIF FC qui ont été ajoutées sur les nœuds IP MetroCluster.
+
Pour faciliter le déplacement de volumes contenant des LUN qui fournissent activement les données aux clients SAN FC, mettre à jour les zones de commutation FC existantes afin que les clients SAN FC puissent accéder aux LUN sur les nœuds IP MetroCluster.

+
.. Sur le commutateur FC SAN (Cisco ou Brocade), ajoutez les WWPN des LIF FC SAN récemment ajoutées à la zone.
.. Mettre à jour, enregistrer et valider les modifications de zoning.
.. Depuis le client, vérifiez que les connexions des initiateurs FC sont connexions aux nouvelles LIF SAN sur les nœuds IP MetroCluster : `sanlun lun show -p`
+
À ce stade, le client doit voir et être connecté aux interfaces FC sur les nœuds IP MetroCluster FC et MetroCluster. Les LUN et les volumes sont toujours hébergés physiquement sur les nœuds FC MetroCluster.

+
Les LUN étant signalées uniquement sur les interfaces de nœuds FC MetroCluster, le client affiche uniquement les chemins sur les nœuds FC. Ceci est visible dans la sortie du `sanlun lun show -p` et `multipath -ll -d` commandes.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_

[root@stemgr]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


. Modifiez les nœuds de reporting pour ajouter les nœuds IP MetroCluster
+
.. Liste des nœuds de rapports pour les LUN sur le SVM : `lun mapping show -vserver svm-name -fields reporting-nodes -ostype linux`
+
Les nœuds de rapports affichés sont des nœuds locaux au fur et à mesure que les LUN se trouvent physiquement sur les nœuds FC A_1 et A_2.

+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver  path                        igroup         reporting-nodes
-------  --------------------------- ------------   -------------------------------------
vsa_1    /vol/vsa_1_vol1/lun_linux_2 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol1/lun_linux_3 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol2/lun_linux_4 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol3/lun_linux_7 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_8 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_9 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_12 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_13 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol7/lun_linux_14 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol8/lun_linux_17 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_18 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_19 igroup_linux  A_1,A_2
12 entries were displayed.
----
.. Ajoutez des nœuds de reporting pour inclure les nœuds IP MetroCluster.
+
[listing]
----
cluster_A::> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes B_1,B_2 -igroup igroup_linux

12 entries were acted on.
----
.. Lister les nœuds de reporting et vérifier la présence des nouveaux nœuds :
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path                          igroup          reporting-nodes
------- ---------------------------   ------------    -------------------------------------------------------------------------------

vsa_1   /vol/vsa_1_vol1/lun_linux_2   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol1/lun_linux_3   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol2/lun_linux_4   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol3/lun_linux_7   igroup_linux    A_1,A_2,B_1,B_2
...

12 entries were displayed.
----
.. Vérifiez que le `sg3-utils` Le package est installé sur l'hôte Linux. Cela permet d'éviter un `rescan-scsi-bus.sh utility not found` Erreur lors de la nouvelle analyse de l'hôte Linux pour les LUN nouvellement mappées à l'aide du `rescan-scsi-bus` commande.
.. Relancez la recherche du bus SCSI sur l'hôte pour découvrir les nouveaux chemins ajoutés : `/usr/bin/rescan-scsi-bus.sh -a`
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
.. Afficher les nouveaux chemins ajoutés : `sanlun lun show -p`
+
Chaque LUN aura quatre chemins d'accès.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_
up secondary sdag host4 iscsi_lf__n4_p1_
up secondary sdah host5 iscsi_lf__n3_p1_
----
.. Sur les contrôleurs, déplacez les volumes contenant des LUN du MetroCluster FC vers les nœuds IP de MetroCluster.
+
[listing]
----
cluster_A::> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate A_1_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "A_1_htp_005_aggr1". Use the "volume move show -vserver vsa_1 -volume vsa_1_vol1"
command to view the status of this operation.
cluster_A::> volume move show
Vserver    Volume    State    Move Phase   Percent-Complete Time-To-Complete
--------- ---------- -------- ----------   ---------------- ----------------
vsa_1     vsa_1_vol1 healthy  initializing
 - -
----
.. Sur le client SAN FC, afficher les informations relatives à la LUN : `sanlun lun show -p`
+
Les interfaces FC des nœuds IP MetroCluster sur lesquels réside la LUN sont mises à jour en tant que chemins principaux. Si le chemin d'accès principal n'est pas mis à jour après le déplacement du volume, exécutez /usr/bin/rescan-scsi-bus.sh -a ou attendez simplement que le chemin d'accès multivoie soit récréé.

+
Le chemin principal dans l'exemple suivant est la LIF sur le nœud IP MetroCluster.

+
[listing]
----
[root@localhost ~]# sanlun lun show -p

                    ONTAP Path: vsa_1:/vol/vsa_1_vol1/lun_linux_2
                           LUN: 22
                      LUN Size: 2g
                       Product: cDOT
                   Host Device: 3600a098038302d324e5d50305063546e
              Multipath Policy: service-time 0
            Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host      vserver
path      path       /dev/   host         vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ----------------------------------------------
up        primary    sddv    host6        fc_5
up        primary    sdjx    host7        fc_6
up        secondary  sdgv    host6        fc_8
up        secondary  sdkr    host7        fc_8
----
.. Répétez les étapes ci-dessus pour tous les volumes, les LUN et les interfaces FC appartenant à un hôte FC SAN.
+
Lorsqu'elles sont terminées, toutes les LUN pour un hôte SVM et FC SAN donné doivent être sur des nœuds IP MetroCluster.



. Supprimez les nœuds de reporting et rescannez les chemins du client.
+
.. Supprimez les nœuds de reporting distants (nœuds FC MetroCluster) pour les LUN linux : `lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true`
+
[listing]
----
cluster_A::> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true
12 entries were acted on.
----
.. Vérifier les nœuds de reporting des LUN : `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path igroup reporting-nodes
------- --------------------------- ------------ -----------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol2/lun_linux_4 igroup_linux B_1,B_2
...

12 entries were displayed.
----
.. Lancez une nouvelle analyse du bus SCSI sur le client : `/usr/bin/rescan-scsi-bus.sh -r`
+
Les chemins d'accès des nœuds FC MetroCluster sont supprimés :

+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
...
----
.. Vérifier que seuls les chemins depuis les nœuds IP MetroCluster sont visibles depuis l'hôte : `sanlun lun show -p`
.. Si nécessaire, supprimez les LIF iSCSI des nœuds FC MetroCluster.
+
Cela doit être effectué s'il n'y a pas d'autres LUN sur les nœuds mappés sur les autres clients.




