---
permalink: upgrade/concept_choosing_tech_refresh_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, choose, upgrade, refresh, method 
summary: 'La procédure de mise à jour que vous utilisez dépend du modèle de plateforme, de l"étendue de la mise à niveau et du type de configuration MetroCluster.' 
---
= Choix d'une méthode de renouvellement du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procédure de mise à jour du système que vous utilisez dépend du modèle de plateforme, de l'étendue de la mise à niveau et du type de configuration MetroCluster.

[cols="2,1,1,2"]
|===
| Portée | Type de configuration | Prise en charge de ONTAP | Aller à... 


 a| 
* Périmètre : plateforme (modules de contrôleurs) et tiroirs de stockage
* Méthode : développez la configuration MetroCluster, puis supprimez les anciens nœuds

 a| 
FC
 a| 
9.6 et versions ultérieures
 a| 
link:task_refresh_4n_mcc_fc.html["Mise à jour d'une configuration FC MetroCluster à quatre nœuds"]



 a| 
* Périmètre : plateforme (modules de contrôleurs) et tiroirs de stockage
* Méthode : développez la configuration MetroCluster, puis supprimez les anciens nœuds

 a| 
IP
 a| 
9.8
 a| 
link:task_refresh_4n_mcc_ip.html["Mise à jour d'une configuration IP MetroCluster à quatre nœuds (ONTAP 9.8 et versions ultérieures)"]

|===