---
permalink: upgrade/concept_choosing_controller_upgrade_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, choose, upgrade, refresh, method 
summary: La procédure de mise à niveau que vous utilisez dépend du modèle de plate-forme. 
---
= Choix d'une procédure de mise à niveau des contrôleurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procédure de mise à niveau du contrôleur que vous utilisez dépend du modèle de plateforme, de l'étendue de la mise à niveau et du type de configuration MetroCluster.



== Choix d'une procédure qui n'utilise pas le transfert d'agrégats

[cols="2,1,1,2"]
|===


| Type de mise à niveau ou d'actualisation | Type de MetroCluster | Prise en charge de la première version de ONTAP | Procédure 


 a| 
* Périmètre : plateforme (modules de contrôleur) uniquement
* Méthode : basculement/rétablissement automatisé

 a| 
FC
 a| 
9.10.1
 a| 
link:task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_fc.html["Mise à niveau des contrôleurs en une configuration FC MetroCluster à quatre nœuds via le basculement et le rétablissement avec des commandes « system contrôleur replace » (ONTAP 9.10.1 et versions ultérieures)"]



 a| 
* Périmètre : plateforme (modules de contrôleur) uniquement
* Méthode : basculement/rétablissement automatisé

 a| 
IP
 a| 
9.10.1
 a| 
link:task_upgrade_A700_to_A900_in_a_four_node_mcc_ip_us_switchover_and_switchback.html["Mise à niveau des contrôleurs de AFF A700 vers AFF A900 dans une configuration IP MetroCluster via le basculement et le rétablissement (ONTAP 9.10.1 et versions ultérieures)"]



 a| 
* Périmètre : plateforme (modules de contrôleur) uniquement
* Méthode : basculement/rétablissement

 a| 
FC
 a| 
9.8
 a| 
link:task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Mise à niveau des contrôleurs en une configuration MetroCluster FC à l'aide du basculement et du rétablissement"]



 a| 
* Périmètre : plateforme (modules de contrôleur) uniquement
* Méthode : basculement/rétablissement

 a| 
IP
 a| 
9.8
 a| 
link:task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["Mise à niveau des contrôleurs dans une configuration MetroCluster IP à l'aide du basculement et du rétablissement (ONTAP 9.8 et versions ultérieures)"]

|===


== Choix d'une procédure à l'aide du transfert d'agrégats

|===
| Procédure de transfert d'agrégats | Type de MetroCluster | Prise en charge de la première version de ONTAP | Procédure 


 a| 
À l'aide de `system controller replace` Commande et échange du module de contrôleur et de la NVM
 a| 
FC
 a| 
9.10.1 et versions ultérieures
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html["Utilisez les commandes « system Controller replace » pour mettre à niveau AFF A700 vers AFF A900 exécutant ONTAP 9.10.1 RC2 ou version ultérieure"^]



 a| 
À l'aide de `system controller replace` commandes
 a| 
FC
 a| 
9.8 et versions ultérieures
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/index.html["À l'aide des commandes « System Controller replace » pour mettre à niveau le matériel du contrôleur exécutant ONTAP 9.8 et versions ultérieures"^]



 a| 
À l'aide de `system controller replace` commandes
 a| 
FC
 a| 
9.5 à 9.7
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/index.html["À l'aide des commandes « contrôleur système replace » pour mettre à niveau le matériel du contrôleur exécutant ONTAP 9.5 vers ONTAP 9.7"^]



 a| 
À l'aide des commandes ARL manuelles
 a| 
FC
 a| 
9.8
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/index.html["Mettez manuellement à niveau le matériel du contrôleur exécutant ONTAP 9.8 et les versions ultérieures"^]



 a| 
À l'aide des commandes ARL manuelles
 a| 
FC
 a| 
9.7 et versions antérieures
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/index.html["Mettez à niveau manuellement le matériel du contrôleur en exécutant ONTAP 9.7 et les versions antérieures"^]

|===