---
permalink: upgrade/reference_where_to_find_additional_information_mcc_ug.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, additional, information 
summary: Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster, 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster,



== MetroCluster et informations diverses

|===


| Informations | Objet 


 a| 
link:../index.html["Documentation MetroCluster"]
 a| 
* Toutes les informations relatives aux MetroCluster




 a| 
link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]
 a| 
* Architecture Fabric-Attached MetroCluster
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration des commutateurs FC
* Configuration de MetroCluster dans ONTAP




 a| 
link:../install-stretch/concept_considerations_differences.html["Installation et configuration d'Stretch MetroCluster"]
 a| 
* Architecture MetroCluster extensible
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration de MetroCluster dans ONTAP




 a| 
link:../disaster-recovery/concept_dr_workflow.html["Gestion et reprise après incident MetroCluster"]
 a| 
* Présentation de la configuration MetroCluster
* Basculement, rétablissement et rétablissement
* Reprise après incident




 a| 
link:../maintain/index.html["Gérer les composants MetroCluster"]
 a| 
* Instructions relatives à la maintenance dans une configuration MetroCluster FC
* Procédure de remplacement ou de mise à niveau du matériel et de mise à niveau du firmware pour les ponts FC-SAS et les commutateurs FC
* Ajout à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Retrait à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Remplacement du matériel sur un site d'incident dans une configuration MetroCluster FC Stretch ou Fabric-Attached
* Extension d'une configuration MetroCluster FC extensible ou Fabric-Attached à deux nœuds à une configuration MetroCluster à quatre nœuds.
* Extension d'une configuration MetroCluster FC à quatre nœuds (Fabric-Attached ou Stretch FC) à une configuration MetroCluster FC à huit nœuds.




 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Mise à niveau, transition et extension de MetroCluster"]
 a| 
* Mise à niveau ou actualisation d'une configuration MetroCluster
* Passer d'une configuration MetroCluster FC à une configuration MetroCluster IP
* Extension d'une configuration MetroCluster par l'ajout de nœuds supplémentaires




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation et configuration du logiciel MetroCluster Tiebreaker"]
 a| 
* Contrôle de la configuration de MetroCluster avec le logiciel MetroCluster Tiebreaker




 a| 
https://docs.netapp.com/platstor/index.jsp["Documentation des systèmes matériels ONTAP"^]


NOTE: Les procédures standard de maintenance des tiroirs de stockage sont compatibles avec les configurations MetroCluster IP.
 a| 
* Ajout à chaud d'un tiroir disque
* Retrait à chaud d'un tiroir disque




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transition basée sur la copie"^]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["Concepts relatifs à ONTAP"^]
 a| 
* Fonctionnement des agrégats en miroir


|===