---
permalink: upgrade/task_apply_the_rcf_files_and_recable_the_switches.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, apply, rcf, files, recable, switches 
summary: 'Vous devez appliquer les fichiers RCF pour reconfigurer votre zoning afin de l"adapter aux nouveaux nœuds.' 
---
= Recâblage et reconfiguration des commutateurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez appliquer les fichiers de configuration de référence (RCF) pour reconfigurer votre zonage afin d’accommoder les nouveaux nœuds.

Si vous ne pouvez pas utiliser les RCF pour configurer les commutateurs, vous devez les configurer manuellement. Voir :

* link:../install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurez manuellement les commutateurs FC Brocade"]
* link:../install-fc/task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configurez manuellement les commutateurs Cisco FC"]


.Étapes
. Localisez les RCF pour votre configuration.
+
Vous devez utiliser les RCF pour une configuration à huit nœuds correspondant à votre modèle de commutateur.

. Appliquez les RCF en suivant les instructions sur la page de téléchargement et en ajustant les paramètres ISL si nécessaire.
. Assurez-vous que la configuration du commutateur est enregistrée.
. Redémarrez les commutateurs FC.
. Reliez les ponts FC-to-SAS existants et les nouveaux ponts FC-SAS aux commutateurs FC, à l'aide de la disposition de câblage que vous avez créée précédemment.
+
L'utilisation des ports du commutateur FC doit correspondre à l'utilisation à huit nœuds MetroCluster décrite dans link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"] afin que les RCF puissent être utilisés.

. Vérifiez que les ports sont en ligne à l'aide de la commande appropriée pour votre commutateur.
+
|===


| Changer de fournisseur | Commande 


 a| 
Brocade
 a| 
affichage du commutateur



 a| 
Cisco
 a| 
afficher la description de l'interface

|===
. Suivre la procédure décrite dans link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"] Pour câbler les ports FC-VI des nouveaux contrôleurs et existants, en utilisant la disposition de câblage que vous avez créée précédemment.
+
L'utilisation des ports du commutateur FC doit correspondre à l'utilisation à huit nœuds MetroCluster décrite dans link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"] afin que les RCF puissent être utilisés.

. Depuis les nœuds existants, vérifier que les ports FC-VI sont en ligne :
+
`metrocluster interconnect adapter show`

+
`metrocluster interconnect mirror show`

. Reliez les ports HBA aux contrôleurs actuels et nouveaux.
. Sur les modules de contrôleur existants, activer en e-commerce les ports connectés au commutateur en cours de maintenance :
+
`storage port enable -node _node-name_ -port _port-ID_`

. Démarrer les nouveaux contrôleurs et les démarrer en mode maintenance :
+
`boot_ontap maint`

. Vérifier que seul le stockage qui sera utilisé par le nouveau groupe DR est visible pour les nouveaux modules de contrôleur.
+
Aucun du stockage utilisé par l'autre groupe DR ne doit être visible.

. Revenez au début de ce processus pour raccorder à nouveau le second commutateur de structure.

