---
permalink: upgrade/task_clear_the_configuration_on_a_controller_module_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, clear, configuration, controller, module 
summary: 'Avant d"utiliser un nouveau module de contrôleur dans la configuration MetroCluster, vous devez effacer la configuration.' 
---
= Effacement de la configuration sur un module de contrôleur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser un nouveau module de contrôleur dans la configuration MetroCluster, il faut effacer la configuration existante.

.Étapes
. Si nécessaire, arrêtez le nœud pour afficher l'invite DU CHARGEUR :
+
`halt`

. Dans l'invite DU CHARGEUR, définissez les variables environnementales sur les valeurs par défaut :
+
`set-defaults`

. Enregistrez l'environnement :
+
`saveenv`

. À l'invite DU CHARGEUR, lancez le menu de démarrage :
+
`boot_ontap menu`

. À l'invite du menu de démarrage, effacez la configuration :
+
`wipeconfig`

+
Répondez `yes` à l'invite de confirmation.

+
Le nœud redémarre et le menu de démarrage s'affiche de nouveau.

. Dans le menu de démarrage, sélectionnez l'option *5* pour démarrer le système en mode Maintenance.
+
Répondez `yes` à l'invite de confirmation.


