---
permalink: upgrade/task_refresh_the_mcc_configuration_mcc_configure_refresh.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, refresh, configuration, new, controller 
summary: 'Vous devez actualiser la configuration MetroCluster lors de son extension d"une configuration à deux nœuds à une configuration à quatre nœuds.' 
---
= Actualisation de la configuration MetroCluster avec de nouveaux contrôleurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez actualiser la configuration MetroCluster lors de son extension d'une configuration à deux nœuds à une configuration à quatre nœuds.

.Étapes
. Actualisez la configuration MetroCluster :
+
.. Passez en mode de privilège avancé : +
`set -privilege advanced`
.. Actualisez la configuration MetroCluster : +
`metrocluster configure -refresh true -allow-with-one-aggregate true`
+
La commande suivante actualise la configuration de MetroCluster sur tous les nœuds du groupe DR qui contient Controller_A_1 :

+
[listing]
----
controller_A_1::*> metrocluster configure -refresh true -allow-with-one-aggregate true

[Job 726] Job succeeded: Configure is successful.
----
.. Revenir en mode de privilège admin :
+
`set -privilege admin`



. Vérifiez l'état de la mise en réseau sur le site A :
+
`network port show`

+
L'exemple suivant montre l'utilisation du port réseau sur une configuration MetroCluster à quatre nœuds :

+
[listing]
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----
. Vérifier la configuration MetroCluster des deux sites de la configuration MetroCluster.
+
.. Vérifier la configuration à partir du site A :
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vérifier la configuration à partir du site B :
+
`metrocluster show`

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vérifier que les relations de reprise sur incident ont été correctement créées :
+
`metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner`

+
[listing]
----
metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner
dr-group-id cluster     node    ha-partner dr-cluster  dr-partner   dr-auxiliary  node-object-limit automatic-uso
----------- ---------   ----    ---------- ----------  ----------   ------------  ----------------- -------------
2           cluster_A   node_A_1 node_A_2    cluster_B  node_B_1     node_B_2      on                true
2           cluster_A   node_A_2 node_A_1    cluster_B  node_B_2     node_B_1      on                true
2           cluster_B   node_B_1 node_B_2    cluster_A  node_A_1     node_A_2      on                true
2           cluster_B   node_B_2 node_B_1    cluster_A  node_A_2     node_A_1      on                true
4 entries were displayed.
----



