---
permalink: upgrade/task_determin_the_new_cable_layout_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, determine, new, cabling, layout 
summary: Vous devez déterminer le câblage reliant les nouveaux modules de contrôleur et les nouveaux tiroirs disques aux commutateurs FC existants. 
---
= Détermination de la nouvelle disposition de câblage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez déterminer le câblage reliant les nouveaux modules de contrôleur et les nouveaux tiroirs disques aux commutateurs FC existants.

.Description de la tâche
Cette tâche doit être effectuée sur chaque site MetroCluster.

.Étapes
. Suivre la procédure décrite dans link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"] Pour créer une disposition de câblage pour votre type de commutateur, en utilisant l'utilisation des ports pour une configuration MetroCluster à huit nœuds.
+
L'utilisation du port de commutateur FC doit correspondre à l'utilisation décrite dans la procédure pour que les fichiers de configuration de référence (RCFs) puissent être utilisés.

+

NOTE: Si votre environnement ne peut pas être câblé de sorte que les fichiers RCF puissent être utilisés, vous devez configurer manuellement le système en suivant les instructions du link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]. N'utilisez pas cette procédure si le câblage ne peut pas utiliser les fichiers RCF.


