---
permalink: upgrade/task_create_unmirrored_data_aggregates_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, unmirrored, data, aggregates 
summary: Vous pouvez choisir de créer des agrégats de données non mis en miroir pour des données ne nécessitant pas la mise en miroir redondante fournie par les configurations MetroCluster. 
---
= Création d'agrégats de données sans mise en miroir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez choisir de créer des agrégats de données non mis en miroir pour des données ne nécessitant pas la mise en miroir redondante fournie par les configurations MetroCluster.

.Description de la tâche
* Vous devez savoir quels disques ou LUN de baie seront utilisés dans le nouvel agrégat.
* Si votre système compte plusieurs types de disques (stockage hétérogène), vous devez comprendre comment vous pouvez vérifier que le type de disque approprié est sélectionné.



IMPORTANT: Dans les configurations MetroCluster IP, les agrégats distants sans mise en miroir ne sont pas accessibles après un basculement


NOTE: Les agrégats non mis en miroir doivent être locaux au nœud qu'ils possèdent.

* Les disques et les LUN de baie sont détenus par un nœud spécifique. Lorsque vous créez un agrégat, tous les disques de cet agrégat doivent être détenus par le même nœud, qui devient le nœud de rattachement de cet agrégat.
* Les noms d'agrégats doivent être conformes au schéma de nommage que vous avez déterminé lors de la planification de votre configuration MetroCluster.
* _Gestion des disques et des agrégats_ contient plus d'informations sur les agrégats en miroir.


.Étapes
. Installez et câisez les tiroirs disques qui contiennent les agrégats non mis en miroir.
+
Vous pouvez utiliser les procédures de la documentation _installation et Setup_ pour votre plate-forme et vos tiroirs disques.

+
https://docs.netapp.com/platstor/index.jsp["Documentation des systèmes matériels ONTAP"^]

. Attribuer manuellement tous les disques du nouveau shelf au nœud approprié :
+
`disk assign -disk <disk-id> -owner <owner-node-name>`

. Créer l'agrégat :
+
`storage aggregate create`

+
Si vous êtes connecté au cluster depuis l'interface de gestion du cluster, vous pouvez créer un agrégat sur n'importe quel nœud du cluster. Pour vérifier que l'agrégat est créé sur un nœud spécifique, il est important d'utiliser le `-node` paramètre ou spécifiez les disques qui sont détenus par ce nœud.

+
Vérifiez que vous n'avez inclus que les disques du tiroir sans miroir à l'agrégat.

+
Vous pouvez spécifier les options suivantes :

+
** Nœud de rattachement de l'agrégat (c'est-à-dire le nœud qui détient l'agrégat en fonctionnement normal)
** Liste de disques spécifiques ou de LUN de baies à ajouter à l'agrégat
** Nombre de disques à inclure
** Style de checksum à utiliser pour l'agrégat
** Type de disques à utiliser
** Taille des disques à utiliser
** Vitesse de conduite à utiliser
** Type RAID des groupes RAID sur l'agrégat
** Nombre maximal de disques ou de LUN de baies pouvant être inclus dans un groupe RAID
** Indique si les disques à régime différent sont autorisés
+
Pour plus d'informations sur ces options, reportez-vous au `storage aggregate create` page de manuel.

+
La commande suivante crée un agrégat sans mise en miroir avec 10 disques :

+
[listing]
----
controller_A_1::> storage aggregate create aggr1_controller_A_1 -diskcount 10 -node controller_A_1
[Job 15] Job is queued: Create aggr1_controller_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----
+

NOTE: Vous pouvez également utiliser `-disklist` le paramètre de la commande pour spécifier les disques que vous souhaitez utiliser pour l'agrégat.



. Vérifier le groupe RAID et les disques de votre nouvel agrégat :
+
`storage aggregate show-status -aggregate <aggregate-name>`



.Informations associées
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestion des disques et des agrégats"]
