---
permalink: upgrade/task_zone_for_the_new_controller_ports_in_a_fabric_attached_mcc_configuration_four_node_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, zone, controller, fabric, attached, ports, add 
summary: 'La segmentation des commutateurs FC doit s"adapter aux nouvelles connexions du contrôleur. Si vous avez utilisé les fichiers \(RCFs\) de configuration de référence fournis par NetApp pour configurer vos commutateurs, le zoning est préconfiguré et vous n"avez pas besoin d"apporter de modifications.' 
---
= Segmentation des nouveaux ports de contrôleur lors de l'ajout d'un module de contrôleur dans une configuration Fabric-Attached MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La segmentation des commutateurs FC doit s'adapter aux nouvelles connexions du contrôleur. Si vous avez utilisé les fichiers RCF (Reference Configuration File) fournis par NetApp pour configurer vos commutateurs, le zoning est préconfiguré et vous n'avez pas besoin d'apporter de modifications.

Si vous avez configuré manuellement vos commutateurs FC, vous devez vérifier que la segmentation est correcte pour les connexions initiateurs des nouveaux modules de contrôleur. Voir les sections sur la segmentation dans link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"].
