---
permalink: upgrade/task_verify_that_the_ha_state_of_components_is_mcc_dr_smok_crater_or_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, verify, ha, config, component, state 
summary: 'Dans une configuration MetroCluster, l"état ha-config du module de contrôleur et des composants du châssis doit être défini sur mcc afin qu"ils s"démarrent correctement.' 
---
= Vérification de l'état ha-config des composants
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans une configuration MetroCluster, l'état ha-config du module de contrôleur et des composants du châssis doit être défini sur *mcc* pour qu'ils s'démarrent correctement.

.Description de la tâche
* Le système doit être en mode Maintenance.
* Cette tâche doit être effectuée sur chaque nouveau module de contrôleur.


.Étapes
. En mode Maintenance, afficher l'état HA du module de contrôleur et du châssis :
+
`ha-config show`

+
L'état HA pour tous les composants doit être « mcc ».

. Si l'état système affiché du contrôleur n'est pas correct, définissez l'état HA pour le module de contrôleur :
+
`ha-config modify controller mcc`

. Si l'état du système affiché du châssis n'est pas correct, définissez l'état de haute disponibilité du châssis :
+
`ha-config modify chassis mcc`

. Répétez ces étapes sur l'autre nœud de remplacement.

