---
permalink: upgrade/task-configure-intercluster-lifs-4node.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, dedicated, ports, shared 
summary: Vous pouvez configurer les LIFs intercluster sur des ports dédiés ou partagés. 
---
= Configurer les LIFs intercluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apprenez à configurer les LIFs intercluster sur des ports dédiés et partagés.

[role="tabbed-block"]
====
.Configurer les LIFs intercluster sur les ports dédiés
--
Vous pouvez configurer des LIFs intercluster sur des ports dédiés afin d'augmenter la bande passante disponible pour le trafic de réplication.

.Étapes
. Lister les ports dans le cluster :
+
`network port show`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant montre les ports réseau en cluster01 :

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. Déterminer les ports disponibles pour dédier aux communications intercluster :
+
`network interface show -fields home-port,curr-port`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant montre que les ports « e0e » et « e0f » n'ont pas été affectés aux LIF :

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01-01_clus1   e0a       e0a
Cluster cluster01-01_clus2   e0b       e0b
Cluster cluster01-02_clus1   e0a       e0a
Cluster cluster01-02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. Créer un failover group pour les ports dédiés :
+
`network interface failover-groups create -vserver <system_SVM> -failover-group <failover_group> -targets <physical_or_logical_ports>`

+
L'exemple suivant attribue les ports « e0e » et « e0f » au groupe de basculement « intercluster01 » sur le SVM système « cluster01 » :

+
[listing]
----
cluster01::> network interface failover-groups create -vserver cluster01 -failover-group
intercluster01 -targets
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. Vérifier que le groupe de basculement a été créé :
+
`network interface failover-groups show`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[listing]
----
cluster01::> network interface failover-groups show
                                  Failover
Vserver          Group            Targets
---------------- ---------------- --------------------------------------------
Cluster
                 Cluster
                                  cluster01-01:e0a, cluster01-01:e0b,
                                  cluster01-02:e0a, cluster01-02:e0b
cluster01
                 Default
                                  cluster01-01:e0c, cluster01-01:e0d,
                                  cluster01-02:e0c, cluster01-02:e0d,
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
                 intercluster01
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
----
. Créer les LIF intercluster sur le SVM système et les assigner au failover group.
+
[cols="1,3"]
|===


| Version ONTAP | Commande 


 a| 
9.6 et versions ultérieures
 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`



 a| 
9.5 et versions antérieures
 a| 
`network interface create -vserver system_SVM -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`

|===
+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant crée les LIFs intercluster « cluster01_icl01 » et « cluster01_icl02 » dans le groupe de basculement « intercluster01 » :

+
[listing]
----
cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0 -failover-group intercluster01

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0 -failover-group intercluster01
----
. Vérifier que les LIFs intercluster ont été créés :
+
|===


| *Dans ONTAP 9.6 et plus tard:* 


 a| 
`network interface show -service-policy default-intercluster`



| *Dans ONTAP 9.5 et versions antérieures:* 


 a| 
`network interface show -role intercluster`

|===
+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. Vérifier que les LIFs intercluster sont redondants :
+
|===


| *Dans ONTAP 9.6 et plus tard:* 


 a| 
`network interface show -service-policy default-intercluster -failover`



| *Dans ONTAP 9.5 et versions antérieures:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant montre que les LIFs intercluster « cluster01_icl01 » et « cluster01_icl02 » sur le port SVM « e0e » basculeront vers le port « e0f ».

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----


--
.Configurer les LIFs intercluster sur des ports data partagés
--
Vous pouvez configurer des LIFs intercluster sur des ports partagés avec le réseau de données afin de réduire le nombre de ports nécessaires pour la mise en réseau intercluster.

.Étapes
. Lister les ports dans le cluster :
+
`network port show`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant montre les ports réseau en cluster01 :

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. Création des LIFs intercluster sur le SVM système :
+
|===


| *Dans ONTAP 9.6 et plus tard:* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`



| *Dans ONTAP 9.5 et versions antérieures:* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`

|===
+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant illustre la création de LIFs intercluster `cluster01_icl01` et `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. Vérifier que les LIFs intercluster ont été créés :
+
|===


| *Dans ONTAP 9.6 et plus tard:* 


 a| 
`network interface show -service-policy default-intercluster`



| *Dans ONTAP 9.5 et versions antérieures:* 


 a| 
`network interface show -role intercluster`

|===
+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Vérifier que les LIFs intercluster sont redondants :
+
|===


| *Dans ONTAP 9.6 et plus tard:* 


 a| 
`network interface show –service-policy default-intercluster -failover`



| *Dans ONTAP 9.5 et versions antérieures:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant montre que les LIFs intercluster « cluster01_icl01 » et « cluster01_icl02 » sur le port « e0c » basculeront vers le port « e0d ».

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----


--
====