---
permalink: upgrade/task_verify_the_health_of_the_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, health, verify, conofiguration 
summary: 'Vous devez vérifier l"état de santé de la configuration MetroCluster pour vérifier que celle-ci fonctionne correctement.' 
---
= Vérification de l'état de santé de la configuration MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vérifier l'état de santé de la configuration MetroCluster pour vérifier que celle-ci fonctionne correctement.

.Étapes
. Vérifier que la MetroCluster est configurée et en mode normal sur chaque cluster :
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
. Vérifier que la mise en miroir est activée sur chaque nœud :
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
. Vérifier que les composants MetroCluster sont sains :
+
`metrocluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
. Vérifier qu'il n'y a pas d'alerte de santé :
+
`system health alert show`

. Simuler une opération de basculement :
+
.. Depuis l'invite d'un nœud, passez au niveau de privilège avancé : +
`set -privilege advanced`
+
Vous devez répondre avec `*y*` lorsque vous êtes invité à passer en mode avancé et à afficher l'invite du mode avancé (*>).

.. Effectuer l'opération de basculement avec le paramètre -Simulate : +
`metrocluster switchover -simulate`
.. Revenir au niveau de privilège admin : +
`set -privilege admin`



