---
permalink: upgrade/task_power_up_both_controller_modules_and_display_the_loader_prompt_2_node_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, power, up, controller. modules, display, loader, prompt 
summary: 'Vous mettez le module de contrôleur existant sous tension et le nouveau module de contrôleur pour afficher l"invite DU CHARGEUR.' 
---
= Mise sous tension des deux modules de contrôleur et affichage de l'invite DU CHARGEUR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous mettez le module de contrôleur existant sous tension et le nouveau module de contrôleur pour afficher l'invite DU CHARGEUR.

.Étapes
Mettez les modules de contrôleur sous tension et interrompez le processus de démarrage en suivant les étapes de votre configuration :

[cols="25,75"]
|===


| Si les modules de contrôleur sont... | Alors... 


 a| 
Dans le même châssis
 a| 
. Vérifiez que le nouveau module de contrôleur est entièrement inséré dans la baie.
+
Le module de contrôleur existant doit être complètement inséré dans la baie, car il n'a jamais été retiré du châssis, mais le nouveau module de contrôleur ne doit pas être.

. Branchez l'alimentation et mettez les blocs d'alimentation sous tension afin que le module de contrôleur existant soit alimenté.
. Interrompez le processus de démarrage du module de contrôleur existant en appuyant sur Ctrl-C.
. Poussez fermement le nouveau module de contrôleur dans la baie.
+
Lorsqu'il est bien en place, le nouveau module de contrôleur reçoit l'alimentation et démarre automatiquement.

. Interrompez le processus de démarrage en appuyant sur Ctrl-C.
. Serrez la vis moletée sur la poignée de came, le cas échéant.
. Installez le dispositif de gestion des câbles, le cas échéant.
. Fixez les câbles au dispositif de gestion des câbles à l'aide du crochet et de la sangle de boucle.




 a| 
Dans un châssis séparé
 a| 
. Allumer les alimentations sur le module de contrôleur existant.
. Interrompez le processus de démarrage en appuyant sur Ctrl-C.
. Répétez ces étapes pour le nouveau module de contrôleur


|===
Chaque module de contrôleur doit afficher l'invite DU CHARGEUR (`LOADER>`, `LOADER-A>`, ou `LOADER-B>`).


NOTE: S'il n'y a pas d'invite DU CHARGEUR, enregistrez le message d'erreur. Si le système affiche le menu de démarrage, redémarrez et essayez à nouveau d'interrompre le processus de démarrage.
