---
permalink: upgrade/task_check_for_mcc_configuration_errors_with_config_advisor.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, check, configuration, errors, config, advisor 
summary: 'Vous pouvez accéder au site de support NetApp et télécharger l"outil Config Advisor pour vérifier les erreurs de configuration courantes.' 
---
= Vérification des erreurs de configuration MetroCluster avec Config Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez accéder au site de support NetApp et télécharger l'outil Config Advisor pour vérifier les erreurs de configuration courantes.

.Description de la tâche
Config Advisor est un outil de validation de la configuration et de vérification de l'état de santé. Vous pouvez le déployer sur des sites sécurisés et sur des sites non sécurisés à des fins de collecte des données et d'analyse du système.


NOTE: Le support pour Config Advisor est limité et n'est disponible qu'en ligne.

.Étapes
. Accédez à la page de téléchargement Config Advisor et téléchargez l'outil.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"]

. Exécutez Config Advisor, examinez les résultats de l'outil et suivez les recommandations du produit pour résoudre tous les problèmes détectés.

