---
permalink: upgrade/upgrade-mcc-ip-manual-uninstall-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 'Déplacez les LIF de données vers un port commun, supprimez les VLAN et les groupes d"interface sur les anciens contrôleurs, puis désinstallez physiquement les contrôleurs.' 
---
= Supprimez les configurations d'interface et désinstallez les anciens contrôleurs IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifier le bon positionnement du LIF. Supprimez ensuite les VLAN et les groupes d'interface des anciens contrôleurs et désinstallez physiquement les contrôleurs.

.Description de la tâche
* Vous effectuez ces étapes sur les anciens contrôleurs (node_B_1-Old, node_B_2-Old).
* Vous avez besoin des informations que vous avez recueillies pour les utiliser dans link:upgrade-mcc-ip-prepare-system.html#map-ports-from-the-old-nodes-to-the-new-nodes["Mappage des ports des anciens nœuds sur les nouveaux nœuds"]cette procédure.


.Étapes
. Démarrez les anciens nœuds et connectez-vous aux nœuds :
+
`boot_ontap`

. Modifier les LIFs intercluster sur les anciens contrôleurs de manière à utiliser un port home différent de celui des ports utilisés pour l'interconnexion haute disponibilité ou l'interconnexion MetroCluster IP DR sur les nouveaux contrôleurs.
+

NOTE: Cette étape est requise pour une mise à niveau réussie.

+
Les LIF intercluster des anciens contrôleurs doivent utiliser un port home différent de celui des ports utilisés pour l'interconnexion haute disponibilité ou l'interconnexion MetroCluster IP DR sur les nouveaux contrôleurs. Par exemple, lorsque vous effectuez une mise à niveau vers des contrôleurs AFF A90, les ports d'interconnexion haute disponibilité sont e1a et e7a et les ports d'interconnexion pour la reprise après incident IP MetroCluster sont e2b et e3b. Vous devez déplacer les LIFs intercluster sur les anciens contrôleurs s'ils sont hébergés sur les ports e1a, e7a, e2b ou e3b.

+
Pour la distribution et l'allocation des ports sur les nouveaux nœuds, reportez-vous à la https://hwu.netapp.com["Hardware Universe"].

+
.. Sur les anciens contrôleurs, afficher les LIFs intercluster :
+
`network interface show  -role intercluster`

+
Effectuez l'une des actions suivantes si les LIF intercluster des anciens contrôleurs utilisent les mêmes ports que les ports utilisés pour l'interconnexion haute disponibilité ou l'interconnexion MetroCluster IP DR sur les nouveaux contrôleurs.

+
[cols="2*"]
|===
| Si les LIFs intercluster... | Aller à... 


| Utilisez le même port de base | <<controller_manual_upgrade_prepare_network_ports_2b,Sous-étape b>> 


| Utilisez un autre port de base | <<controller_manual_upgrade_prepare_network_ports_3,Étape 3>> 
|===
.. [[Controller_Manual_upgrade_prepare_network_ports_2b]]modifiez les LIFs intercluster pour utiliser un autre port home :
+
`network interface modify -vserver <vserver> -lif <intercluster_lif> -home-port <port-not-used-for-ha-interconnect-or-mcc-ip-dr-interconnect-on-new-nodes>`

.. Vérifier que toutes les LIFs intercluster se trouvent sur leurs nouveaux ports home :
+
`network interface show -role intercluster -is-home  false`

+
La sortie de la commande doit être vide, ce qui indique que toutes les LIFs intercluster se trouvent sur leurs ports home respectifs.

.. Reconvertir toutes les LIF qui ne se trouvent pas sur leur port de base :
+
`network interface revert -lif <intercluster_lif>`

+
Répéter la commande pour chaque LIF intercluster qui ne se trouve pas sur le home port.



. [[Controller_Manual_upgrade_prepare_network_ports_3]]affectez le port de base de toutes les LIFs de données de l'ancien contrôleur à un port commun identique sur l'ancien et le nouveau module de contrôleur.
+

CAUTION: Si les anciens et les nouveaux contrôleurs ne disposent pas de port commun, il n'est pas nécessaire de modifier les LIFs data. Ignorez cette étape et passez directement à <<upgrades_manual_without_matching_ports,Étape 4>>.

+
.. Afficher les LIFs :
+
`network interface show`

+
Toutes les LIF DE données, y compris SAN et NAS, sont administratives et opérationnelles, car elles fonctionnent sur le site de basculement (cluster_A).

.. Vérifiez le résultat de cette commande pour trouver un port réseau physique commun identique sur l'ancien et le nouveau contrôleur qui n'est pas utilisé comme port du cluster.
+
Ainsi, le port e0d est un port physique des anciens contrôleurs et il est également présent sur les nouveaux contrôleurs. e0d n'est pas utilisé comme port de cluster ou autre sur les nouveaux contrôleurs.

+
Pour l'utilisation des ports pour les modèles de plate-forme, voir https://hwu.netapp.com/["Hardware Universe"]

.. Modifier toutes les LIFS de données pour utiliser le port commun comme port de home : +
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`
+
Dans l'exemple suivant, il s'agit de « e0d ».

+
Par exemple :

+
[listing]
----
network interface modify -vserver vs0 -lif datalif1 -home-port e0d
----


. [[upgrades_Manual_without_matching_ports]]modifiez les domaines de diffusion pour supprimer le VLAN et les ports physiques qui doivent être supprimés :
+
`broadcast-domain remove-ports -broadcast-domain <broadcast-domain-name> -ports <node-name:port-id>`

+
Répétez cette étape pour tous les réseaux VLAN et les ports physiques.

. Supprimez tous les ports VLAN utilisant des ports de cluster comme ports membres et groupes d'interfaces utilisant des ports de cluster comme ports membres.
+
.. Supprimer les ports VLAN : +
`network port vlan delete -node <node_name> -vlan-name <portid-vlandid>`
+
Par exemple :

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. Supprimez les ports physiques des groupes d'interface :
+
`network port ifgrp remove-port -node <node_name> -ifgrp <interface-group-name> -port <portid>`

+
Par exemple :

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. Supprimez les ports VLAN et de groupe d'interfaces du broadcast domain :
+
`network port broadcast-domain remove-ports -ipspace <ipspace> -broadcast-domain <broadcast-domain-name> -ports <nodename:portname,nodename:portnamee>,..`

.. Modifiez les ports de groupe d'interface pour utiliser d'autres ports physiques comme membres, selon les besoins :
+
`ifgrp add-port -node <node_name> -ifgrp <interface-group-name> -port <port-id>`



. Arrêtez les nœuds à l' `LOADER`invite :
+
`halt -inhibit-takeover true`

. Connectez-vous à la console série des anciens contrôleurs (node_B_1-Old et node_B_2-Old) sur site_B et vérifiez que l'invite s'affiche `LOADER`.
. Rassemblez les valeurs de bootarg :
+
`printenv`

. Déconnectez les connexions de stockage et réseau sur les nœuds_B_1-Old et node_B_2-Old. Etiquetez les câbles afin de pouvoir les reconnecter aux nouveaux nœuds.
. Déconnectez les câbles d'alimentation du nœud_B_1-Old et du nœud_B_2-Old.
. Retirez le rack des contrôleurs node_B_1-Old et node_B_2-Old.


.Et la suite ?
link:upgrade-mcc-ip-manual-setup-controllers.html["Configurer les nouveaux contrôleurs"].
