---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-complete-upgrade.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 'Terminez le processus de mise à niveau automatique du contrôleur en vérifiant l"accessibilité du réseau et en restaurant toute configuration de surveillance.' 
---
= Terminez la mise à niveau du contrôleur IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Terminez le processus de mise à niveau automatique du contrôleur en vérifiant l'accessibilité du réseau et en restaurant toute configuration de surveillance.



== Vérifiez l'accessibilité du réseau

L'automatisation exécute des vérifications du système, puis s'interrompt pour que vous puissiez vérifier la capacité d'accès au réseau. Une fois la vérification terminée, la phase de récupération des ressources est lancée, et l'opération d'automatisation exécute le rétablissement sur le site A et s'interrompt après les vérifications de mise à niveau. Une fois que vous avez rétabli l'opération d'automatisation, il effectue les vérifications post-mise à niveau et, si aucune erreur n'est détectée, marque la mise à niveau comme terminée.

.Étapes
. Vérifiez l'accessibilité du réseau en suivant le message de la console.
. Une fois la vérification terminée, reprendre l'opération :
+
`system controller replace resume`

. L'opération d'automatisation est effectuée `heal-aggregate`, `heal-root-aggregate`, Et les opérations de rétablissement sur le site A, et les vérifications post-mise à niveau. Lorsque l'opération s'interrompt, vérifier manuellement le statut LIF SAN et vérifier la configuration du réseau en suivant le message de la console.
. Une fois la vérification terminée, reprendre l'opération :
+
`system controller replace resume`

. Vérifier l'état des vérifications post-mise à niveau :
+
`system controller replace show`

+
Si les vérifications post-mise à niveau n'ont pas signalé d'erreurs, la mise à niveau est terminée.

. Une fois la mise à niveau du contrôleur terminée, connectez-vous au site B et vérifiez que les contrôleurs remplacés sont configurés correctement.




== Mettre à niveau les nœuds sur cluster_A

Vous devez répéter les tâches de mise à niveau pour mettre à niveau les nœuds sur le cluster_A sur le site A.

.Étapes
. Répétez les étapes pour mettre à niveau les nœuds sur cluster_A, en commençant par link:upgrade-mcc-ip-system-controller-replace-supported-platforms.html["Préparation à la mise à niveau"].
+
Au fur et à mesure que vous effectuez les tâches, toutes les références aux clusters et aux nœuds sont inversées.





== Reconfigurer le médiateur ONTAP

Configurez manuellement le médiateur ONTAP qui a été automatiquement supprimé avant de commencer la mise à niveau.

. Suivez les étapes de la section link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Configurer ONTAP Mediator à partir d'une configuration IP MetroCluster"].




== Restaurez la surveillance du logiciel disjoncteur d'attache

Si le logiciel disjoncteur d'attache a déjà été configuré pour la surveillance de la configuration MetroCluster, vous pouvez restaurer la connexion ce dernier.

. Suivez les étapes de la section http://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/GUID-7259BCA4-104C-49C6-BAD0-1068CA2A3DA5.html["Ajouter des configurations MetroCluster"].




== Configurez le chiffrement de bout en bout

Si votre système le prend en charge, vous pouvez chiffrer le trafic back-end, tel que les données NVlog et de réplication du stockage, entre les sites IP MetroCluster. Reportez-vous à la section link:../maintain/task-configure-encryption.html["Configurez le chiffrement de bout en bout"] pour en savoir plus.
