---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-console-logging.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 'Activez la journalisation de la console sur vos périphériques avant d"effectuer la mise à niveau du contrôleur.' 
---
= Activez la journalisation de la console avant la mise à niveau de l'adresse IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Activez la journalisation de la console sur vos périphériques avant d'effectuer la mise à niveau du contrôleur.

NetApp vous recommande vivement d'activer la journalisation de la console sur les périphériques que vous utilisez et d'effectuer les actions suivantes lors de l'exécution de cette procédure :

* Laissez AutoSupport activé pendant la maintenance.
* Déclencher un message AutoSupport de maintenance avant et après la maintenance pour désactiver la création de dossiers pendant la durée de l'activité de maintenance.
+
Consultez l'article de la base de connaissances link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Comment supprimer la création automatique de dossier pendant les fenêtres de maintenance planifiées"^].

* Activer la journalisation de session pour toute session CLI. Pour obtenir des instructions sur l'activation de la journalisation des sessions, consultez la section « consignation des sorties de session » de l'article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].


.Et la suite ?
Consultez les informations de la section link:upgrade-mcc-ip-system-controller-replace-set-bootarg.html["Définir le démarrage requis (pour les mises à niveau vers les systèmes introduits dans la version 9.15.1 ou ultérieure)"] pour vérifier si vous devez définir un démarrage requis sur le système existant.
