---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc, bootarg 
summary: 'Les mises à niveau de systèmes introduites dans ONTAP 9.15.1 ou version ultérieure nécessitent la définition d"un amorçage avant de pouvoir procéder à la mise à niveau du contrôleur.' 
---
= Définir le démarrage requis (pour les mises à niveau MetroCluster IP vers les systèmes introduits dans ONTAP 9.15.1 ou version ultérieure)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous effectuez une mise à niveau vers un système introduit dans ONTAP 9.15.1 ou une version ultérieure, vous devez généralement définir un bootarg sur les anciens contrôleurs avant de pouvoir démarrer la mise à niveau.


NOTE: Si votre combinaison de mise à niveau est affectée, la définition d'un bootarg sur tous les anciens contrôleurs est nécessaire pour une mise à niveau réussie.  Consultez attentivement les informations de cette section pour vérifier si votre combinaison de mise à niveau nécessite que vous définissiez un bootarg et comment définir le bootarg correct pour votre combinaison.



== Étape 1 : Déterminez si vous devez définir un bootarg sur les anciens contrôleurs

Avant de commencer la mise à niveau, déterminez si vous devez définir un bootarg sur les anciens contrôleurs en utilisant les informations suivantes :

* Vous *devez* définir un bootarg sur les anciens contrôleurs pour les mises à niveau prises en charge vers les systèmes suivants, sauf indication contraire :
+
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60
** FAS50


* Vous n'avez *pas* besoin de définir de bootarg sur les anciens contrôleurs si votre mise à niveau correspond à l'une des combinaisons suivantes :
+
** D'un système AFF A70 à un système AFF A90
** D'un système FAS70 à un système FAS90





CAUTION: Si votre mise à niveau ne nécessite pas la définition d'un bootarg, vous pouvez ignorer cette tâche et accéder directement àlink:upgrade-mcc-ip-prepare-system.html["Préparez le système pour la mise à niveau"] .



== Étape 2 : Déterminez le bootarg à définir sur les anciens contrôleurs

La plupart des mises à niveau concernées nécessitent que vous définissiez le `hw.cxgbe.toe_keepalive_disable` bootarg sur les anciens contrôleurs.  Cependant, certains chemins de mise à niveau nécessitent que vous définissiez le `bootarg.siw.interop_enabled` bootarg à la place.

Utilisez le tableau suivant pour déterminer quel bootarg vous devez définir pour votre combinaison de mise à niveau spécifique.

[cols="2*"]
|===
| Pour cette mise à niveau... | Définir le bootarg... 


| De AFF A250 à AFF A30 | `bootarg.siw.interop_enabled` 


| De AFF C250 à AFF C30 | `bootarg.siw.interop_enabled` 


| De AFF A150 à AFF A20 | `bootarg.siw.interop_enabled` 


| De AFF A220 à AFF A20 | `bootarg.siw.interop_enabled` 


 a| 
Toutes les autres mises à niveau vers les systèmes AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A30, AFF C30, AFF C60 ou FAS50

*Remarque :* vous n'avez pas besoin de définir de bootarg si votre mise à niveau s'effectue d'un système AFF A70 vers AFF A90 ou d'un système FAS70 vers FAS90.
| `hw.cxgbe.toe_keepalive_disable` 
|===


== Étape 3 : définissez le bootarg requis sur les anciens contrôleurs

Après avoir déterminé le bootarg requis pour votre combinaison de mise à niveau, suivez les étapes pour définir le bootarg sur les anciens contrôleurs.


NOTE: Vous devez définir le bootarg sur tous les anciens nœuds des deux sites avant de démarrer la mise à niveau.

.Étapes
. Arrêtez un nœud sur les deux sites et permettez à son partenaire haute disponibilité d'effectuer une prise de contrôle du stockage du nœud :
+
`halt  -node <node_name>`

. Définissez le démarrage requis pour votre combinaison de mise à niveau. Vous avez déjà déterminé le bootarg que vous devez définir en utilisant la table dans <<upgrade_paths_bootarg_manual,déterminez le bootarg à définir>>.
+
[role="tabbed-block"]
====
.hw.cxgbe.tep_keepalive_disable
--
.. À `LOADER` l'invite du nœud interrompu, entrez les informations suivantes :
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
`saveenv`

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. À `LOADER` l'invite du nœud interrompu, entrez les informations suivantes :
+
`setenv bootarg.siw.interop_enabled 1`

+
`saveenv`

+
`printenv bootarg.siw.interop_enabled`



--
====
. Démarrez le nœud :
+
`boot_ontap`

. Au démarrage du nœud, effectuez un rétablissement pour le nœud à l'invite :
+
`storage failover giveback -ofnode <node_name>`

. Répétez cette procédure pour tous les nœuds du groupe de reprise sur incident ou des groupes de reprise sur incident que vous mettez à niveau.


.Et la suite ?
link:upgrade-mcc-ip-prepare-system.html["Préparez le système pour la mise à niveau"].
