---
permalink: tiebreaker/reference_where_to_find_additional_information_tb_icg.html 
sidebar: sidebar 
keywords: metrocluster, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster, 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster,



== MetroCluster et informations diverses

|===


| Informations | Objet 


 a| 
link:../index.html["Documentation MetroCluster"]
 a| 
* Toutes les informations relatives aux MetroCluster




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["Rapport technique de NetApp 4375 : NetApp MetroCluster pour ONTAP 9.3"^]
 a| 
* Présentation technique de la configuration et du fonctionnement de MetroCluster.
* Bonnes pratiques de configuration MetroCluster.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]
 a| 
* Architecture Fabric-Attached MetroCluster
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration des commutateurs FC
* Configuration de MetroCluster dans ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["Installation et configuration d'Stretch MetroCluster"]
 a| 
* Architecture MetroCluster extensible
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration de MetroCluster dans ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["Installation et configuration de MetroCluster IP"]
 a| 
* Architecture de MetroCluster IP
* Câblage de la configuration IP de MetroCluster
* Configuration de MetroCluster dans ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["Maintenance des composants MetroCluster"]
 a| 
* Instructions relatives à la maintenance dans une configuration MetroCluster
* Procédure de remplacement ou de mise à niveau du matériel et de mise à niveau du firmware pour les ponts FC-SAS et les commutateurs FC
* Ajout à chaud d'un tiroir disque dans une configuration Fabric-Attached ou Stretch MetroCluster
* Retrait à chaud d'un tiroir disque dans une configuration Fabric-Attached ou Stretch MetroCluster
* Remplacement du matériel sur un site d'incident dans une configuration MetroCluster Stretch ou Fabric-Attached
* Extension d'une configuration MetroCluster extensible ou Fabric-Attached à deux nœuds à une configuration MetroCluster à quatre nœuds.
* Extension d'une configuration MetroCluster extensible ou Fabric-Attached à quatre nœuds à une configuration MetroCluster à huit nœuds.




 a| 
Documentation Active IQ Unified Manager

https://docs.netapp.com["Documentation NetApp : guides et ressources produits"^]
 a| 
* Contrôle de la configuration et des performances d'MetroCluster




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Transition basée sur la copie"]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster


|===