---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: 'Pour utiliser SNMP avec le logiciel disjoncteur d"attache, vous devez configurer les paramètres SNMP.' 
---
= Configuration des paramètres SNMP pour le logiciel disjoncteur d'attache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour utiliser SNMP avec le logiciel Tiebreaker, vous devez configurer les paramètres SNMP.

. Utiliser l'interface de ligne de commande Tiebreaker `snmp config wizard` Pour ajouter des configurations MetroCluster.
+

NOTE: Un seul hôte d'interruption SNMP est actuellement pris en charge.

+
L'exemple suivant montre la configuration d'un récepteur SNMP qui prend en charge SNMP V3 avec une adresse IP 10.240.45.66 et le port numéro 162 pour les messages d'interruption. Le logiciel disjoncteur d'attache est prêt à envoyer des traps au récepteur SNMP que vous avez spécifié.

+
....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version[V1/V3]: v3
Enter SNMP Host: 10.240.45.66
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
Enter SNMP V3 Privacy password:
Engine ID : 8000031504932eff571825192a6f1193b265e24593
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
....
+

NOTE: Vous devez configurer SNMPv3 car SNMPv1 n'est pas sécurisé. Assurez-vous que la chaîne de communauté par défaut est *NOT* définie sur public.

. Vérifier que les paramètres SNMP sont configurés :
+
`snmp config test`

+
L'exemple suivant montre que le logiciel disjoncteur d'attache peut envoyer une interruption SNMP pour l'événement TEST_SNMP_CONFIG :

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V1.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

