---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: 'Pour utiliser SNMP avec le logiciel disjoncteur d"attache, vous devez configurer les paramètres SNMP.' 
---
= Configuration des paramètres SNMP pour le logiciel disjoncteur d'attache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour utiliser SNMP avec le logiciel disjoncteur d'attache, vous devez configurer les paramètres SNMP.

. Utilisez la commande disjoncteur d'attache de l'assistant de configuration snmp pour ajouter des configurations MetroCluster.
+

NOTE: Un seul hôte d'interruption SNMP est actuellement pris en charge.

+
L'exemple suivant montre la configuration d'un récepteur SNMP prenant en charge SNMP V1 avec une adresse IP de 10.222.210.234, le numéro de port 162 pour les messages d'interruption et la chaîne de communauté définie sur public :

+
....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version [V1/V3]: V1
Enter SNMP Host: 10.222.210.234
Enter SNMP Port: 162
Enter SNMP V1 Community: public
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
NetApp MetroCluster Tiebreaker :>
....
+
Le logiciel disjoncteur d'attache est prêt à envoyer des traps au récepteur SNMP que vous avez spécifié.

. Vérifier que les paramètres SNMP sont configurés :
+
`snmp config test`

+
L'exemple suivant montre que le logiciel disjoncteur d'attache peut envoyer une interruption SNMP pour l'événement TEST_SNMP_CONFIG :

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V1.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

