---
permalink: tiebreaker/task_install_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: 'Il offre des fonctionnalités de surveillance d"un environnement de stockage en cluster. Il envoie également des notifications SNMP en cas de problèmes de connectivité des nœuds et d"incidents sur site.' 
---
= Installation du logiciel disjoncteur d'attache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il offre des fonctionnalités de surveillance d'un environnement de stockage en cluster. Il envoie également des notifications SNMP en cas de problèmes de connectivité des nœuds et d'incidents sur site.

Le logiciel MetroCluster doit être installé et configuré.



== Configuration requise pour l'installation ou la mise à niveau du logiciel disjoncteur d'attache

Le logiciel disjoncteur d'attache est installé sur un troisième site, ce qui permet au logiciel de distinguer une panne de liaison interswitch (ISL) d'une panne sur un site. Votre système hôte doit respecter certaines exigences avant d'installer ou de mettre à niveau le logiciel disjoncteur d'attache sur votre ordinateur local afin de surveiller la configuration MetroCluster.

Le logiciel MetroCluster Tiebreaker présente les fonctionnalités et les exigences de surveillance suivantes :

* Aucune configuration spéciale n'est requise pour les différentes configurations MetroCluster.
* Capacités de contrôle pour jusqu'à 15 configurations MetroCluster simultanément.
+

NOTE: Pour éviter les conflits avec plusieurs moniteurs Tiebreaker, il vous suffit d'avoir un seul contrôle d'MetroCluster Tiebreaker par configuration MetroCluster.

* Prise en charge d'une combinaison de configurations MetroCluster IP, MetroCluster FC et Stretch MetroCluster.
* Matériel et logiciels :
+
** ONTAP 8.3.x, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9.1, 9.10.1 ou 9.11.1.


* Red Hat Enterprise Linux 7 à 7.9 ou CentOS 7 à 7.9 64 bits (installation physique ou machine virtuelle)
+
** Serveur MariaDB 5.5.52.x/MySQL 5.6x
** 4 GO DE RAM
** Ouvrez Java Runtime Environment 8


* Red Hat Enterprise Linux 8.1 à 8.5
+
** MariaDB 10.x (utilisez la version par défaut installée à l'aide de "yum install mariadb-Server.x86_64")
** 4 GO DE RAM
** Ouvrez Java Runtime Environment 8




* Capacité du disque : 8 Go
* Utilisateur : accès racine
* Pare-feu :
+
** Accès direct pour la configuration des messages AutoSupport
** SSH (port 22/TCP), HTTPS (port 443/TCP) et ping (ICMP)


* L'installation sur des hôtes compatibles FIPS n'est pas prise en charge.




== Installation des dépendances d'MetroCluster Tiebreaker

Vous devez installer un serveur MySQL ou MariaDB en fonction du système d'exploitation Linux qui est votre hôte avant d'installer ou de mettre à niveau le logiciel disjoncteur d'attache.

.Étapes
. Installez Java Runtime Environment.
+
,Installation de Java Runtime Environment 1.8

. Installez le serveur MySQL ou MariaDB :
+
[cols="30,70"]
|===


| Si l'hôte Linux est | Alors... 


 a| 
Red Hat Enterprise Linux 7/CentOS 7
 a| 
Installez MySQL

,Installation de MySQL Server 5.5.30 ou version ultérieure et des versions 5.6.x sur Red Hat Enterprise Linux 7 ou CentOS 7



 a| 
Red Hat Enterprise Linux 8
 a| 
Installez MariaDB

,Installation du serveur MariaDB sur Red Hat Enterprise Linux 8

|===




=== Installation de Java Runtime Environment 1.8

Vous devez installer Java Runtime Environment 1.8 sur votre système hôte avant d'installer ou de mettre à niveau le logiciel disjoncteur d'attache.

.Étapes
. Connectez-vous en tant que `root` vers le système hôte.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. Installez Java Runtime Environment 1.8 :
+
`[root@mcctb ~]# yum install java-1.8.0-openjdk.x86_64`

+
....
[root@mcctb ~]# yum install java-1.8.0-openjdk.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
... shortened....
Dependencies Resolved

=======================================================================
Package               Arch   Version                 Repository    Size
=======================================================================
Installing:
 java-1.8.0-openjdk  x86_64  1:1.8.0.144-0.b01.el7_4 updates      238 k
 ..
 ..
Transaction Summary
=======================================================================
Install  1 Package  (+ 4 Dependent packages)

Total download size: 34 M
Is this ok [y/d/N]: y

Installed:
java-1.8.0-openjdk.x86_64 1:1.8.0.144-0.b01.el7_4
Complete!
....




=== Installation de MySQL Server 5.5.30 ou version ultérieure et des versions 5.6.x sur Red Hat Enterprise Linux 7 ou CentOS 7

Vous devez installer MySQL Server 5.5.30 ou version ultérieure et 5.6.x sur votre système hôte avant d'installer ou de mettre à niveau le logiciel disjoncteur d'attache.

.Étapes
. Connectez-vous en tant que `root` vers le système hôte.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2016 from host.domain.com
----
. Ajoutez le référentiel MySQL à votre système hôte :
+
`[root@mcctb ~]# yum localinstall \https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm`

+
....

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
Setting up Local Package Process
Examining /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm: mysql-community-release-el6-5.noarch
Marking /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package mysql-community-release.noarch 0:el6-5 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
Package               Arch   Version
                                    Repository                             Size
================================================================================
Installing:
mysql-community-release
                       noarch el6-5 /mysql-community-release-el6-5.noarch 4.3 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total size: 4.3 k
Installed size: 4.3 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-release-el6-5.noarch                         1/1
  Verifying  : mysql-community-release-el6-5.noarch                         1/1
Installed:
  mysql-community-release.noarch 0:el6-5
Complete!
....
. Désactivez le référentiel mysql 57 :
+
`[root@mcctb ~]# yum-config-manager --disable mysql57-community`

. Activer le référentiel mysql 56 :
+
`[root@mcctb ~]# yum-config-manager --enable mysql56-community`

. Activer le référentiel :
+
`[root@mcctb ~]# yum repolist enabled | grep "mysql.*-community.*"`

+
....

mysql-connectors-community           MySQL Connectors Community            21
mysql-tools-community                MySQL Tools Community                 35
mysql56-community                    MySQL 5.6 Community Server           231
....
. Installez le serveur de communauté MySQL :
+
`[root@mcctb ~]# yum install mysql-community-server`

+
[listing]
----

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager
to register.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
.....Output truncated.....
---> Package mysql-community-libs-compat.x86_64 0:5.6.29-2.el6 will be obsoleting
--> Finished Dependency Resolution
Dependencies Resolved
==============================================================================
Package                          Arch   Version       Repository          Size
==============================================================================
Installing:
 mysql-community-client         x86_64  5.6.29-2.el6  mysql56-community  18  M
     replacing  mysql.x86_64 5.1.71-1.el6
 mysql-community-libs           x86_64  5.6.29-2.el6  mysql56-community  1.9 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-libs-compat    x86_64  5.6.29-2.el6  mysql56-community  1.6 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-server         x86_64  5.6.29-2.el6  mysql56-community  53  M
     replacing  mysql-server.x86_64 5.1.71-1.el6
Installing for dependencies:
mysql-community-common          x86_64  5.6.29-2.el6  mysql56-community   308 k

Transaction Summary
===============================================================================
Install       5 Package(s)
Total download size: 74 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): mysql-community-client-5.6.29-2.el6.x86_64.rpm       |  18 MB     00:28
(2/5): mysql-community-common-5.6.29-2.el6.x86_64.rpm       | 308 kB     00:01
(3/5): mysql-community-libs-5.6.29-2.el6.x86_64.rpm         | 1.9 MB     00:05
(4/5): mysql-community-libs-compat-5.6.29-2.el6.x86_64.rpm  | 1.6 MB     00:05
(5/5): mysql-community-server-5.6.29-2.el6.x86_64.rpm       |  53 MB     03:42
-------------------------------------------------------------------------------
Total                                              289 kB/s |  74 MB     04:24
warning: rpmts_HdrFromFdno: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
Retrieving key from file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Importing GPG key 0x5072E1F5:
 Userid : MySQL Release Engineering <mysql-build@oss.oracle.com>
Package: mysql-community-release-el6-5.noarch
         (@/mysql-community-release-el6-5.noarch)
 From   : file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-common-5.6.29-2.el6.x86_64
....Output truncated....
1.el6.x86_64                                                               7/8
  Verifying  : mysql-5.1.71-1.el6.x86_64                       	           8/8
Installed:
  mysql-community-client.x86_64 0:5.6.29-2.el6
  mysql-community-libs.x86_64 0:5.6.29-2.el6
  mysql-community-libs-compat.x86_64 0:5.6.29-2.el6
  mysql-community-server.x86_64 0:5.6.29-2.el6

Dependency Installed:
  mysql-community-common.x86_64 0:5.6.29-2.el6

Replaced:
  mysql.x86_64 0:5.1.71-1.el6 mysql-libs.x86_64 0:5.1.71-1.el6
  mysql-server.x86_64 0:5.1.71-1.el6
Complete!
----
. Démarrez le serveur MySQL :
+
`[root@mcctb ~]# service mysqld start`

+
....

Initializing MySQL database:  2016-04-05 19:44:38 0 [Warning] TIMESTAMP
with implicit DEFAULT value is deprecated. Please use
--explicit_defaults_for_timestamp server option (see documentation
for more details).
2016-04-05 19:44:38 0 [Note] /usr/sbin/mysqld (mysqld 5.6.29)
        starting as process 2487 ...
2016-04-05 19:44:38 2487 [Note] InnoDB: Using atomics to ref count
        buffer pool pages
2016-04-05 19:44:38 2487 [Note] InnoDB: The InnoDB memory heap is disabled
....Output truncated....
2016-04-05 19:44:42 2509 [Note] InnoDB: Shutdown completed; log sequence
       number 1625987

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER!
To do so, start the server, then issue the following commands:

  /usr/bin/mysqladmin -u root password 'new-password'
  /usr/bin/mysqladmin -u root -h mcctb password 'new-password'

Alternatively, you can run:
  /usr/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
.....Output truncated.....
WARNING: Default config file /etc/my.cnf exists on the system
This file will be read by default by the MySQL server
If you do not want to use this, either remove it, or use the
--defaults-file argument to mysqld_safe when starting the server

                                                           [  OK  ]
Starting mysqld:                                           [  OK  ]
....
. Vérifiez que le serveur MySQL est en cours d'exécution :
+
`[root@mcctb ~]# service mysqld status`

+
[listing]
----

mysqld (pid  2739) is running...
----
. Configurez les paramètres de sécurité et de mot de passe :
+
`[root@mcctb ~]# mysql_secure_installation`

+
....

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MySQL
       SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

 In order to log into MySQL to secure it, we'll need the current
 password for the root user.  If you've just installed MySQL, and
 you haven't set the root password yet, the password will be blank,
 so you should just press enter here.

 Enter current password for root (enter for none):   <== on default install
                                                         hit enter here
 OK, successfully used password, moving on...

 Setting the root password ensures that nobody can log into the MySQL
 root user without the proper authorization.

 Set root password? [Y/n] y
 New password:
 Re-enter new password:
 Password updated successfully!
 Reloading privilege tables..
  ... Success!

 By default, a MySQL installation has an anonymous user, allowing anyone
 to log into MySQL without having to have a user account created for
 them.  This is intended only for testing, and to make the installation
 go a bit smoother.  You should remove them before moving into a
 production environment.

 Remove anonymous users? [Y/n] y
  ... Success!

 Normally, root should only be allowed to connect from 'localhost'.  This
 ensures that someone cannot guess at the root password from the network.

 Disallow root login remotely? [Y/n] y
  ... Success!

 By default, MySQL comes with a database named 'test' that anyone can
 access.  This is also intended only for testing, and should be removed
 before moving into a production environment.

 Remove test database and access to it? [Y/n] y
  - Dropping test database...
 ERROR 1008 (HY000) at line 1: Can't drop database 'test';
 database doesn't exist
  ... Failed!  Not critical, keep moving...
  - Removing privileges on test database...
  ... Success!

 Reloading the privilege tables will ensure that all changes made so far
 will take effect immediately.

 Reload privilege tables now? [Y/n] y
  ... Success!

 All done!  If you've completed all of the above steps, your MySQL
 installation should now be secure.

 Thanks for using MySQL!

 Cleaning up...
....
. Vérifiez que la connexion MySQL fonctionne :
+
`[root@mcctb ~]# mysql -u root –p`

+
....

Enter password: <configured_password>
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.6.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql>
....
+
Si le login MySQL fonctionne, la sortie se termine au `mysql>` à l'invite.





==== Activation du paramètre de démarrage automatique MySQL

Assurez-vous que la fonction de démarrage automatique est activée pour le deamon MySQL. L'activation du démon MySQL redémarre automatiquement MySQL si le système sur lequel réside le logiciel MetroCluster Tiebreaker. Si le démon MySQL n'est pas en cours d'exécution, le logiciel disjoncteur d'attache continue à fonctionner, mais il ne peut pas être redémarré et des modifications de configuration ne peuvent pas être effectuées.

.Étape
. Vérifiez que MySQL est activé pour démarrer automatiquement lors du démarrage :
+
`[root@mcctb ~]# systemctl list-unit-files mysqld.service`

+
....
UNIT FILE          State
------------------ ----------
mysqld.service     enabled

....
+
Si MySQL n'est pas activé pour démarrer automatiquement au démarrage, consultez la documentation MySQL pour activer la fonction de démarrage automatique pour votre installation.





=== Installation du serveur MariaDB sur Red Hat Enterprise Linux 8

Vous devez installer le serveur MariaDB sur votre système hôte avant d'installer ou de mettre à niveau le logiciel disjoncteur d'attache.

Votre système hôte doit être exécuté sous Red Hat Enterprise Linux (RHEL) 8.

.Étapes
. Connectez-vous en tant que `root` vers le système hôte.
+
....

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
....
. Installer le serveur MariaDB :
+
`[root@mcctb ~]# yum install mariadb-server.x86_64`

+
....
 [root@mcctb ~]# yum install mariadb-server.x86_64
Loaded plugins: fastestmirror, langpacks
...
...

===========================================================================
 Package                      Arch   Version         Repository        Size
===========================================================================
Installing:
mariadb-server               x86_64   1:5.5.56-2.el7   base            11 M
Installing for dependencies:

Transaction Summary
===========================================================================
Install  1 Package  (+8 Dependent packages)
Upgrade             ( 1 Dependent package)

Total download size: 22 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for base warning:
/var/cache/yum/x86_64/7/base/packages/mariadb-libs-5.5.56-2.el7.x86_64.rpm:
Header V3 RSA/SHA256 Signature,
key ID f4a80eb5: NOKEY] 1.4 MB/s | 3.3 MB  00:00:13 ETA
Public key for mariadb-libs-5.5.56-2.el7.x86_64.rpm is not installed
(1/10): mariadb-libs-5.5.56-2.el7.x86_64.rpm  | 757 kB  00:00:01
..
..
(10/10): perl-Net-Daemon-0.48-5.el7.noarch.rpm|  51 kB  00:00:01
-----------------------------------------------------------------------------------------
Installed:
  mariadb-server.x86_64 1:5.5.56-2.el7

Dependency Installed:
mariadb.x86_64 1:5.5.56-2.el7
perl-Compress-Raw-Bzip2.x86_64 0:2.061-3.el7
perl-Compress-Raw-Zlib.x86_64 1:2.061-4.el7
perl-DBD-MySQL.x86_64 0:4.023-5.el7
perl-DBI.x86_64 0:1.627-4.el7
perl-IO-Compress.noarch 0:2.061-2.el7
perl-Net-Daemon.noarch 0:0.48-5.el7
perl-PlRPC.noarch 0:0.2020-14.el7

Dependency Updated:
  mariadb-libs.x86_64 1:5.5.56-2.el7
Complete!
....
. Démarrer le serveur MariaDB :
+
`[root@mcctb ~]# systemctl start mariadb`

. Vérifiez que le serveur MariaDB a démarré :
+
`[root@mcctb ~]# systemctl status mariadb`

+
....

[root@mcctb ~]# systemctl status mariadb
mariadb.service - MariaDB database server
...
Nov 08 21:28:59 mcctb systemd[1]: Starting MariaDB database server...
...
Nov 08 21:29:01 scspr0523972001 systemd[1]: Started MariaDB database server.
....
+

NOTE: Assurez-vous que le paramètre « activer le démarrage automatique » est activé pour MariaDB. Voir .

. Configurez les paramètres de sécurité et de mot de passe :
+
`[root@mcctb ~]# mysql_secure_installation`

+
....

[root@mcctb ~]# mysql_secure_installation
NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
SERVERS IN PRODUCTION USE! PLEASE READ EACH STEP CAREFULLY!
Set root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Remove anonymous users? [Y/n] y
... Success!
Normally, root should only be allowed to connect from 'localhost'. This
ensures that someone cannot guess at the root password from the network.
Disallow root login remotely? [Y/n] y
... Success!
Remove test database and access to it? [Y/n] y
- Dropping test database...
... Success!
- Removing privileges on test database...
... Success!
Reload privilege tables now? [Y/n]
... Success!
Cleaning up...
All done! If you've completed all of the above steps, your MariaDB
installation should now be secure.
Thanks for using MariaDB!
....




==== Activation du paramètre de démarrage automatique pour MariaDB

Assurez-vous que la fonction de démarrage automatique est activée pour MariaDB. Si vous n'activez pas la fonctionnalité de démarrage automatique et si le système sur lequel réside le logiciel MetroCluster Tiebreaker doit être redémarré, alors le logiciel disjoncteur d'attache continue d'être en cours d'exécution, mais le service MariaDB ne peut pas être redémarré et les modifications de configuration ne peuvent pas être effectuées.

.Étapes
. Activer le service de démarrage automatique :
+
`[root@mcctb ~]# systemctl enable mariadb.service`

. Vérifiez que MariaDB est activé pour démarrer automatiquement au démarrage :
+
`[root@mcctb ~]# systemctl list-unit-files mariadb.service`

+
....
UNIT FILE          State
------------------ ----------
mariadb.service    enabled

....




== Installation ou mise à niveau du progiciel

Vous devez installer ou mettre à niveau le logiciel MetroCluster Tiebreaker sur votre ordinateur local, afin d'assurer le contrôle des configurations MetroCluster.

* Votre système de stockage doit exécuter ONTAP 8.3.x ou une version ultérieure.
* Vous devez avoir installé OpenJDK à l'aide de `yum install java-1.8.0-openjdk` commande.


.Étapes
. Téléchargez la dernière version du logiciel MetroCluster Tiebreaker. Cet exemple utilise la version 1.21P3-1.
+
https://mysupport.netapp.com/site/["Support NetApp"]

. Connectez-vous à l'hôte en tant qu'utilisateur racine.
. Installer ou mettre à niveau le logiciel disjoncteur d'attache :
+
[cols="20,80"]
|===


| Si vous êtes... | Exécutez cette commande... 


 a| 
Exécution d'une nouvelle installation
 a| 
`rpm -ivh NetApp-MetroCluster-Tiebreaker-Software-1.21P3-1x86_64.rpm`

Pour une installation réussie, le système affiche les valeurs de sortie suivantes :

....
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
Post installation start Wed Oct 20 09:59:19 EDT 2021
Enter MetroCluster Tiebreaker user password:

Please enter mysql root password when prompted
Enter password:
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Enabled autostart of NetApp MetroCluster Tiebreaker software daemon during boot
Created symbolic link for NetApp MetroCluster Tiebreaker software CLI
Post installation end Wed Oct 20 09:59:28 EDT 2021
Successfully installed NetApp MetroCluster Tiebreaker software version 1.21P3.
....


 a| 
Mise à niveau d'une installation existante
 a| 
`rpm -Uvh NetApp-MetroCluster-Tiebreaker-Software-1.21P3-1.x86_64.rpm`

Le système affiche les résultats suivants pour une mise à niveau réussie :

....

MetroCluster-Tiebreaker-Software-1.21P3-1.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Upgrading NetApp MetroCluster Tiebreaker software....
Stopping NetApp MetroCluster Tiebreaker software services before upgrade.
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [ 50%]
Post installation start Wed Oct 20 09:57:49 EDT 2021
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Starting NetApp MetroCluster Tiebreaker software services. Retry: 1
Started NetApp MetroCluster Tiebreaker software services
Enabled autostart of NetApp MetroCluster Tiebreaker software daemon during boot
Created symbolic link for NetApp MetroCluster Tiebreaker software CLI
Post upgrade end Wed Oct 20 09:57:52 EDT 2021
Successfully upgraded NetApp MetroCluster Tiebreaker software to version 1.21P3.
Cleaning up / removing...
   2:NetApp-MetroCluster-Tiebreaker-So################################# [100%]

....
|===
+

NOTE: Si vous saisissez un mot de passe racine MySQL incorrect, le logiciel disjoncteur d'attache indique qu'il a été installé avec succès, mais affiche des messages « accès refusé ». Pour résoudre ce problème, vous devez désinstaller le logiciel disjoncteur d'attache à l'aide du `rpm -e` Puis réinstallez le logiciel en utilisant le mot de passe racine MySQL correct.

. Vérifiez la connectivité disjoncteur d'attache au logiciel MetroCluster en ouvrant une connexion SSH de l'hôte disjoncteur d'attache à chacune des LIF de gestion de nœud et des LIF de gestion du cluster.


https://mysupport.netapp.com/site/["Support NetApp"]



== Mise à niveau de l'hôte où le contrôle Tiebreaker est en cours d'exécution

Vous pouvez mettre à niveau l'hôte sur lequel le moniteur Tiebreaker fonctionne avec une interruption minimale si vous placez les moniteurs en mode observateur avant la mise à niveau.

.Étapes
. Vérifiez que les moniteurs sont en mode observateur :
+
`monitor show –status`

+
....
NetApp MetroCluster Tiebreaker:> monitor show -status
MetroCluster: cluster_A
    Disaster: false
    Monitor State: Normal
    Observer Mode: true
    Silent Period: 15
    Override Vetoes: false
    Cluster: cluster_Ba(UUID:4d9ccf24-080f-11e4-9df2-00a098168e7c)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-a1(UUID:78b44707-0809-11e4-9be1-e50dab9e83e1)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-a2(UUID:9a8b1059-0809-11e4-9f5e-8d97cdec7102)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
    Cluster: cluster_B(UUID:70dacd3b-0823-11e4-a7b9-00a0981693c4)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-b1(UUID:961fce7d-081d-11e4-9ebf-2f295df8fcb3)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-b2(UUID:9393262d-081d-11e4-80d5-6b30884058dc)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
....
. Changer tous les moniteurs en mode observateur.
+
....
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name _monitor_name_ -observer-mode true
....
. Pour mettre à niveau le logiciel disjoncteur d'attache, suivez toutes les étapes indiquées dans la procédure suivante :
+
,Installation ou mise à niveau du progiciel

. Désactivez le mode observateur pour remettre tous les moniteurs en mode en ligne.
+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name _monitor_name_ -observer-mode false
----




== Sélection de la source NTP du logiciel disjoncteur d'attache

Vous devez utiliser une source NTP (Network Time Protocol) locale pour le logiciel disjoncteur d'attache. Il ne doit pas utiliser la même source que les sites MetroCluster surveillés par le logiciel disjoncteur d'attache.
