---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: 'Lors de la planification de votre configuration MetroCluster pour une utilisation avec des disques et des LUN de baie, vous devez tenir compte de différents facteurs, tels que l"ordre de configuration de l"accès au stockage, l"emplacement de l"agrégat racine et l"utilisation des ports d"initiateur FC, des commutateurs et des ponts FC-SAS.' 
---
= Considérations relatives à l'implémentation d'une configuration MetroCluster avec des disques et des LUN de baies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la planification de votre configuration MetroCluster pour une utilisation avec des disques et des LUN de baie, vous devez tenir compte de différents facteurs, tels que l'ordre de configuration de l'accès au stockage, l'emplacement de l'agrégat racine et l'utilisation des ports d'initiateur FC, des commutateurs et des ponts FC-SAS.

Lors de la planification de votre configuration, tenez compte des informations du tableau suivant :

|===


| Réflexion | Directive 


 a| 
Ordre de configuration de l'accès au stockage
 a| 
Vous pouvez commencer par configurer l'accès aux disques ou aux LUN de baies. Vous devez terminer toute la configuration de ce type de stockage et vérifier qu'il est correctement configuré avant de configurer l'autre type de stockage.



 a| 
Emplacement de l'agrégat root
 a| 
* Si vous configurez un déploiement _New_ MetroCluster avec des disques et des LUN de baie, vous devez créer l'agrégat racine sur des disques natifs.
+
Pour ce faire, assurez-vous que _au moins un_ tiroir disque (avec 24 lecteurs de disque) est configuré sur chacun des sites.

* Si vous ajoutez des disques natifs à une configuration _existing_ MetroCluster qui utilise des LUN de baie, l'agrégat racine peut rester sur une LUN de baie.




 a| 
Avec des commutateurs et des ponts FC-SAS
 a| 
Des ponts FC-SAS sont nécessaires dans des configurations à quatre nœuds et des configurations FAS à deux nœuds pour connecter les systèmes ONTAP aux tiroirs disques par le biais de commutateurs.

Vous devez utiliser les mêmes commutateurs pour vous connecter aux baies de stockage et aux ponts FC-SAS.



 a| 
Utilisation des ports initiateurs FC
 a| 
Les ports initiateurs utilisés pour la connexion à un pont FC-SAS doivent être différents des ports utilisés pour la connexion aux commutateurs, qui se connectent aux baies de stockage.

Un minimum de huit ports initiateurs est nécessaire pour connecter un système ONTAP à la fois aux disques et aux LUN de la baie.

|===
.Informations associées
* Les procédures et les commandes de configuration des commutateurs sont différentes, selon le fournisseur du commutateur.
+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuration manuelle des commutateurs Brocade FC"]

+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configuration manuelle des commutateurs Cisco FC"]

* Lors de l'ajout d'un stockage à la configuration, vous installez et câblez les ponts ATTO FibreBridge et les tiroirs disques SAS.
+
link:task_fb_new_install.html["Installation de ponts FC-SAS et de tiroirs disques SAS"]

* La segmentation des commutateurs définit les chemins entre les nœuds connectés. La configuration du zoning permet de définir les LUN de baie pouvant être visualisées par un système ONTAP spécifique.
+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de commutateur dans une configuration MetroCluster à quatre nœuds avec des LUN de baie"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de commutateur dans une configuration MetroCluster à huit nœuds avec des LUN de baie"]

* https://["NetApp Hardware Universe"]

