---
permalink: install-fc/concept_fcsw_brocade_reviewing_brocade_license_requirements.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, review, brocade, license, requirements 
summary: Vous avez besoin de certaines licences pour les commutateurs dans une configuration MetroCluster. Vous devez installer ces licences sur les quatre commutateurs. 
---
= Révision des besoins en licences Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous avez besoin de certaines licences pour les commutateurs dans une configuration MetroCluster. Vous devez installer ces licences sur les quatre commutateurs.

La configuration MetroCluster a les exigences suivantes en matière de licence Brocade :

* Licence d'agrégation pour les systèmes utilisant plusieurs liens ISL, comme recommandé.
* Licence Extended Fabric (pour des distances ISL de plus de 6 km)
* Licence Enterprise pour les sites avec plus d'un ISL et une distance ISL supérieure à 6 km
+
La licence Enterprise inclut Brocade Network Advisor et toutes les licences à l'exception des licences de port supplémentaires.



Vous pouvez vérifier que les licences sont installées à l'aide du `licenseshow` commande. Si vous ne disposez pas de ces licences, contactez votre représentant commercial avant de continuer.
