---
permalink: install-fc/concept_considerations_when_removing_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, remove, configuration, disk connectivity, interconnects, adjust 
summary: 'Vous pouvez supprimer la configuration MetroCluster de tous les nœuds de la configuration MetroCluster ou de tous les nœuds d"un groupe de reprise après incident \(DR\).' 
---
= Considérations relatives à la suppression des configurations MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer la configuration MetroCluster de tous les nœuds de la configuration MetroCluster ou de tous les nœuds d'un groupe de reprise après incident. Après avoir supprimé la configuration MetroCluster, tous les paramètres de connectivité et d'interconnexion de disque doivent être ajustés pour qu'ils soient pris en charge. Si vous devez supprimer la configuration MetroCluster, contactez le support technique.


IMPORTANT: Vous ne pouvez pas inverser la déconfiguration de MetroCluster. Ce processus ne doit être effectué qu'en collaboration avec le support technique. Veuillez contacter le support technique NetApp et consulter le guide approprié pour votre configuration depuis le link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_remove_nodes_from_a_MetroCluster_configuration_-_Resolution_Guide["Comment supprimer des nœuds d'une configuration MetroCluster - Guide de résolution."^]
