---
permalink: install-fc/concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, example, eight, node, array, luns, mcc 
summary: La segmentation des commutateurs définit les chemins entre les nœuds connectés. La configuration du zoning permet de définir les LUN de baie pouvant être visualisées par des systèmes ONTAP spécifiques. 
---
= Exemple de segmentation de commutateur dans une configuration MetroCluster à huit nœuds avec des LUN de baie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La segmentation des commutateurs définit les chemins entre les nœuds connectés. La configuration du zoning permet de définir les LUN de baie pouvant être visualisées par des systèmes ONTAP spécifiques.

Une configuration MetroCluster à huit nœuds se compose de deux groupes de reprise après incident à quatre nœuds. Le premier groupe DR comprend les nœuds suivants :

* Controller_A_1
* Contrôleur_A_2
* Contrôleur_B_1
* Contrôleur_B_2


Le second groupe DR comprend les nœuds suivants :

* Controller_A_3
* Controller_A_4
* Contrôleur_B_3
* Contrôleur_B_4


Pour configurer la segmentation des commutateurs, vous pouvez utiliser les exemples de zoning pour une configuration MetroCluster à quatre nœuds pour le premier groupe DR.

link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de commutateur dans une configuration MetroCluster à quatre nœuds avec des LUN de baie"]

Pour configurer la segmentation du second groupe DR, suivez les mêmes exemples et conditions pour les ports initiateurs FC et les LUN de baie appartenant aux contrôleurs du second groupe DR.

.Informations associées
* La segmentation des commutateurs définit les chemins entre les nœuds connectés. La configuration du zoning permet de définir les LUN de baie pouvant être visualisées par des systèmes ONTAP spécifiques.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de switch dans une configuration MetroCluster à deux nœuds avec des LUN de baie"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de commutateur dans une configuration MetroCluster à quatre nœuds avec des LUN de baie"]

* Lors de l'utilisation de la segmentation de commutateurs dans une configuration MetroCluster avec des LUN de baie, vous devez vous assurer que certaines exigences de base sont respectées.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["Conditions requises pour la segmentation des commutateurs dans une configuration MetroCluster avec des LUN de baie"]


