---
permalink: install-fc/concept_considerations_7mt.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 'Lorsque vous préparez l"installation de MetroCluster, vous devez comprendre l"architecture matérielle et les composants requis de MetroCluster.' 
---
= À prendre en compte lors de la transition de 7-mode vers ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La nouvelle configuration MetroCluster doit être entièrement configurée et opérationnelle avant d'utiliser les outils de transition pour déplacer les données d'une configuration MetroCluster 7-mode vers une configuration ONTAP. Si la configuration 7-mode utilise des switchs Brocade 6510, la nouvelle configuration peut partager les structures existantes afin de réduire les exigences matérielles.

Si vous utilisez des commutateurs Brocade 6510 et que vous prévoyez de partager les structures de commutateurs entre le Fabric 7-mode et le MetroCluster sous ONTAP, vous devez suivre la procédure spécifique de configuration des composants MetroCluster MetroCluster.

link:task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html["Configuration du matériel MetroCluster pour partager une structure FC Brocade 6510 7-mode lors de la transition"]
