---
permalink: install-fc/concept_switch_ports_required_for_a_eight_node_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: ontap, metrocluster, 
summary: Lorsque vous connectez les systèmes ONTAP à des commutateurs FC pour configurer une configuration MetroCluster avec des LUN de baies, vous devez connecter les ports FC-VI et HBA de chaque contrôleur à des ports de commutateurs spécifiques. 
---
= Les ports de commutation sont requis pour une configuration MetroCluster avec des LUN de baie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous connectez les systèmes ONTAP à des commutateurs FC pour configurer une configuration MetroCluster avec des LUN de baies, vous devez connecter les ports FC-VI et HBA de chaque contrôleur à des ports de commutateurs spécifiques.

Si vous utilisez à la fois des LUN de matrice et des disques dans la configuration MetroCluster, vous devez vous assurer que les ports de contrôleur sont connectés aux ports de commutateur recommandés pour la configuration avec des disques, puis utiliser les ports restants pour la configuration avec des LUN de matrice.

Le tableau suivant répertorie les différents ports de commutateur FC auxquels vous devez connecter les différents ports de contrôleur dans une configuration MetroCluster à huit nœuds avec des LUN de baie.



== Instructions générales de câblage avec les LUN de baies

Lors de l'utilisation des tables de câblage, il est important de connaître les consignes suivantes :

* Les commutateurs Brocade et Cisco utilisent une numérotation de port différente :
+
** Sur les commutateurs Brocade, le premier port est numéroté 0.
** Sur les commutateurs Cisco, le premier port est numéroté 1.


* Le câblage est le même pour chaque commutateur FC dans la structure du commutateur.
* Vous pouvez commander les systèmes de stockage FAS8200 avec l'une des deux options de connectivité FC-VI :
+
** Ports intégrés 0e et 0f configurés en mode FC-VI.
** Ports 1a et 1b sur une carte FC-VI dans l'emplacement 1.


* Les systèmes de stockage FAS9000 requièrent quatre ports FC-VI. Les tableaux suivants présentent le câblage des commutateurs FC avec quatre ports FC-VI sur chaque contrôleur.
+
Pour les autres systèmes de stockage, utilisez le câblage indiqué dans les tableaux, mais ignorez le câblage des ports FC-VI c et d.

+
Vous pouvez laisser ces ports vides.





== Utilisation des ports Brocade pour les contrôleurs dans une configuration MetroCluster

Les tableaux suivants indiquent l'utilisation des ports sur les commutateurs Brocade. Les tableaux présentent la configuration maximale prise en charge, avec huit modules de contrôleur dans deux groupes DR. Pour les configurations plus petites, ignorez les lignes des modules de contrôleur supplémentaires. Notez que huit liens ISL sont pris en charge sur les commutateurs Brocade 6510 et G620.


NOTE: L'utilisation des ports pour le commutateur Brocade 6505 dans une configuration MetroCluster à huit nœuds n'est pas illustrée. En raison du nombre limité de ports, les attributions de ports doivent être effectuées site par site, selon le modèle de module de contrôleur et le nombre de liens ISL et de paires de ponts utilisés.

Le tableau suivant présente le câblage pour le premier groupe DR :

|===


2+|  2+| Brocade 6520, 6510, 6505, G620, G610, ou 7840 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* 


.8+| controller_x_1  a| 
Port FC-VI a
 a| 
0
 a| 



 a| 
Port FC-VI b
 a| 
-
 a| 
0



 a| 
Port c FC-VI
 a| 
1
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
1



 a| 
Port a du HBA
 a| 
2
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
2



 a| 
Port c de l'adaptateur HBA
 a| 
3
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
3



.8+| controller_x_2  a| 
Port FC-VI a
 a| 
4
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
4



 a| 
Port c FC-VI
 a| 
5
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
5



 a| 
Port a du HBA
 a| 
6
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
6



 a| 
Port c de l'adaptateur HBA
 a| 
7
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
7

|===
Le tableau suivant présente le câblage pour le second groupe de reprise sur incident :

|===


2+|  2+| Brocade 6510 2+| Brocade 6520 2+| Brocade G620 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* | *Commutateur 1* | *Commutateur 2* | *Commutateur 1* | *Commutateur 2* 


.8+| controller_x_3  a| 
Port FC-VI a
 a| 
24
 a| 
-
 a| 
48
 a| 
-
 a| 
18
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
24
 a| 
-
 a| 
48
 a| 
-
 a| 
18



 a| 
Port c FC-VI
 a| 
25
 a| 
-
 a| 
49
 a| 
-
 a| 
19
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
25
 a| 
-
 a| 
49
 a| 
-
 a| 
19



 a| 
Port a du HBA
 a| 
26
 a| 
-
 a| 
50
 a| 
-
 a| 
24
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
26
 a| 
-
 a| 
50
 a| 
-
 a| 
24



 a| 
Port c de l'adaptateur HBA
 a| 
27
 a| 
-
 a| 
51
 a| 
-
 a| 
25
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
27
 a| 
-
 a| 
51
 a| 
-
 a| 
25



.8+| controller_x_4  a| 
Port FC-VI a
 a| 
28
 a| 
-
 a| 
52
 a| 
-
 a| 
22
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
28
 a| 
-
 a| 
52
 a| 
-
 a| 
22



 a| 
Port c FC-VI
 a| 
29
 a| 
-
 a| 
53
 a| 
-
 a| 
23
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
29
 a| 
-
 a| 
53
 a| 
-
 a| 
23



 a| 
Port a du HBA
 a| 
30
 a| 
-
 a| 
54
 a| 
-
 a| 
28
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
30
 a| 
-
 a| 
54
 a| 
-
 a| 
28



 a| 
Port c de l'adaptateur HBA
 a| 
31
 a| 
-
 a| 
55
 a| 
-
 a| 
29
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
31
 a| 
-
 a| 
55
 a| 
-
 a| 
29



8+| *Liens ISL* 


 a| 
ISL 1
 a| 
40
 a| 
40
 a| 
23
 a| 
23
 a| 
40
 a| 
40



 a| 
ISL 2
 a| 
41
 a| 
41
 a| 
47
 a| 
47
 a| 
41
 a| 
41



 a| 
ISL 3
 a| 
42
 a| 
42
 a| 
71
 a| 
71
 a| 
42
 a| 
42



 a| 
ISL 4
 a| 
43
 a| 
43
 a| 
95
 a| 
95
 a| 
43
 a| 
43



 a| 
ISL 5
 a| 
44
 a| 
44
2.4+| Non pris en charge  a| 
44
 a| 
44



 a| 
ISL 6
 a| 
45
 a| 
45
 a| 
45
 a| 
45



 a| 
ISL 7
 a| 
46
 a| 
46
 a| 
46
 a| 
46



 a| 
ISL 8
 a| 
47
 a| 
47
 a| 
47
 a| 
47

|===


== Utilisation des ports Cisco pour les contrôleurs dans une configuration MetroCluster exécutant ONTAP 9.4 ou une version ultérieure

Les tableaux présentent la configuration maximale prise en charge, avec huit modules de contrôleur dans deux groupes DR. Pour les configurations plus petites, ignorez les lignes des modules de contrôleur supplémentaires.



=== Utilisation du port Cisco 9396S

|===


4+| Cisco 9396S 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* 


.8+| controller_x_1  a| 
Port FC-VI a
 a| 
1
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
1



 a| 
Port c FC-VI
 a| 
2
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
2



 a| 
Port a du HBA
 a| 
3
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
3



 a| 
Port c de l'adaptateur HBA
 a| 
4
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
4



.8+| controller_x_2  a| 
Port FC-VI a
 a| 
5
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
5



 a| 
Port c FC-VI
 a| 
6
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
6



 a| 
Port a du HBA
 a| 
7
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
7



 a| 
Port c de l'adaptateur HBA
 a| 
8
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
8



.8+| controller_x_3  a| 
Port FC-VI a
 a| 
49
 a| 



 a| 
Port FC-VI b
 a| 
-
 a| 
49



 a| 
Port c FC-VI
 a| 
50
 a| 



 a| 
Port FC-VI d
 a| 
-
 a| 
50



 a| 
Port a du HBA
 a| 
51
 a| 



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
51



 a| 
Port c de l'adaptateur HBA
 a| 
52
 a| 



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
52



.8+| controller_x_4  a| 
Port FC-VI a
 a| 
53
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
53



 a| 
Port c FC-VI
 a| 
54
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
54



 a| 
Port a du HBA
 a| 
55
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
55



 a| 
Port c de l'adaptateur HBA
 a| 
56
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
56

|===


=== Utilisation du port Cisco 9148S

|===


4+| Cisco 9148S 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* 


.8+| controller_x_1  a| 
Port FC-VI a
 a| 
1
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
1



 a| 
Port c FC-VI
 a| 
2
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
2



 a| 
Port a du HBA
 a| 
3
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
3



 a| 
Port c de l'adaptateur HBA
 a| 
4
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
4



.8+| controller_x_2  a| 
Port FC-VI a
 a| 
5
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
5



 a| 
Port c FC-VI
 a| 
6
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
6



 a| 
Port a du HBA
 a| 
7
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
7



 a| 
Port c de l'adaptateur HBA
 a| 
8
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
8



.8+| controller_x_3  a| 
Port FC-VI a
 a| 
25
 a| 



 a| 
Port FC-VI b
 a| 
-
 a| 
25



 a| 
Port c FC-VI
 a| 
26
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
26



 a| 
Port a du HBA
 a| 
27
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
27



 a| 
Port c de l'adaptateur HBA
 a| 
28
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
28



.8+| controller_x_4  a| 
Port FC-VI a
 a| 
29
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
29



 a| 
Port c FC-VI
 a| 
30
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
30



 a| 
Port a du HBA
 a| 
31
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
31



 a| 
Port c de l'adaptateur HBA
 a| 
32
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
32

|===


=== Utilisation du port Cisco 9132T

|===


4+| Cisco 9132T 


4+| Module MDS 1 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* 


.8+| controller_x_1  a| 
Port FC-VI a
 a| 
1
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
1



 a| 
Port c FC-VI
 a| 
2
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
2



 a| 
Port a du HBA
 a| 
3
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
3



 a| 
Port c de l'adaptateur HBA
 a| 
4
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
4



.8+| controller_x_2  a| 
Port FC-VI a
 a| 
5
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
5



 a| 
Port c FC-VI
 a| 
6
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
6



 a| 
Port a du HBA
 a| 
7
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
7



 a| 
Port c de l'adaptateur HBA
 a| 
8
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
8



4+| *Module MDS 2* 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* 


.8+| controller_x_3  a| 
Port FC-VI a
 a| 
1
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
1



 a| 
Port c FC-VI
 a| 
2
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
2



 a| 
Port a du HBA
 a| 
3
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
3



 a| 
Port c de l'adaptateur HBA
 a| 
4
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
4



.8+| controller_x_4  a| 
Port FC-VI a
 a| 
5
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
5



 a| 
Port c FC-VI
 a| 
6
 a| 
-



 a| 
Port FC-VI d
 a| 
-
 a| 
6



 a| 
Port a du HBA
 a| 
7
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
7



 a| 
Port c de l'adaptateur HBA
 a| 
8
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
8

|===


=== Utilisation du port Cisco 9250

--

NOTE: Le tableau suivant montre les systèmes équipés de deux ports FC-VI. Les systèmes AFF A700 et FAS9000 disposent de quatre ports FC-VI (a, b, c et d). Si vous utilisez un système AFF A700 ou FAS9000, les attributions de ports se déplacent d'une position à l'autre. Par exemple, les ports FC-VI c et d passent au port de commutateur 2 et aux ports d'adaptateur HBA a et b, puis au port de commutateur 3.

--
|===


4+| Cisco 9250i 


4+| Le commutateur Cisco 9250i n'est pas pris en charge dans les configurations MetroCluster à huit nœuds. 


| *Composant* | *Port* | *Commutateur 1* | *Commutateur 2* 


.6+| controller_x_1  a| 
Port FC-VI a
 a| 
1
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
1



 a| 
Port a du HBA
 a| 
2
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
2



 a| 
Port c de l'adaptateur HBA
 a| 
3
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
3



.6+| controller_x_2  a| 
Port FC-VI a
 a| 
4
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
4



 a| 
Port a du HBA
 a| 
5
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
5



 a| 
Port c de l'adaptateur HBA
 a| 
6
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
6



.6+| controller_x_3  a| 
Port FC-VI a
 a| 
7
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
7



 a| 
Port a du HBA
 a| 
8
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
8



 a| 
Port c de l'adaptateur HBA
 a| 
9
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
9



.6+| controller_x_4  a| 
Port FC-VI a
 a| 
10
 a| 
-



 a| 
Port FC-VI b
 a| 
-
 a| 
10



 a| 
Port a du HBA
 a| 
11
 a| 
-



 a| 
Port b de l'adaptateur HBA
 a| 
-
 a| 
11



 a| 
Port c de l'adaptateur HBA
 a| 
13
 a| 
-



 a| 
Port d de l'adaptateur HBA
 a| 
-
 a| 
13

|===


== Initiateur et prise en charge des cibles partagées pour la configuration de MetroCluster avec des LUN de baies

La possibilité de partager un port FC d'initiateur ou de cible donné est particulièrement utile pour les entreprises qui souhaitent minimiser le nombre de ports initiateurs ou cibles utilisés. Par exemple, une entreprise s'attend à une faible utilisation d'E/S sur un port FC initiateur ou sur des ports cibles à partager le port FC initiator ou les ports cibles au lieu de dédier chaque port FC initiateur à un seul port cible.

Cependant, le partage des ports initiateurs ou cibles peut nuire aux performances.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_support_Shared_Initiator_and_Shared_Target_configuration_with_Array_LUNs_in_a_MetroCluster_environment["Comment prendre en charge la configuration de l'initiateur partagé et de la cible partagée avec des LUN de baie dans un environnement MetroCluster"]
