---
permalink: install-fc/reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, switch, zoning, array, luns, requirements 
summary: 'Lors de l"utilisation de la segmentation de commutateurs dans une configuration MetroCluster avec des LUN de baie, vous devez vous assurer que certaines exigences de base sont respectées.' 
---
= Conditions requises pour la segmentation des commutateurs dans une configuration MetroCluster avec des LUN de baie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de l'utilisation de la segmentation de commutateurs dans une configuration MetroCluster avec des LUN de baie, vous devez vous assurer que certaines exigences de base sont respectées.

Les exigences relatives à la segmentation des commutateurs dans une configuration MetroCluster avec des LUN de baie sont les suivantes :

* La configuration MetroCluster doit suivre le schéma de segmentation single-initiator to single-target.
+
Initiateur unique jusqu'à la segmentation à cible unique limite chaque zone à un seul port FC initiator et à un seul port cible.

* Les ports FC-VI doivent être zonés de bout en bout sur l'ensemble de la structure.
* Le partage de plusieurs ports d'initiateur avec un seul port cible peut entraîner des problèmes de performances.
+
De même, le partage de plusieurs ports cibles avec un seul port initiateur peut provoquer des problèmes de performances.

* Vous devez avoir effectué une configuration de base des commutateurs FC utilisés dans la configuration MetroCluster.
+
link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Configuration manuelle des commutateurs FC Cisco ou Brocade"]





== Initiateur et prise en charge des cibles partagées pour la configuration de MetroCluster avec des LUN de baies

La possibilité de partager un port FC d'initiateur ou de cible donné est particulièrement utile pour les entreprises qui souhaitent minimiser le nombre de ports initiateurs ou cibles utilisés. Par exemple, une entreprise s'attend à une faible utilisation d'E/S sur un port FC initiateur ou sur des ports cibles à partager le port FC initiator ou les ports cibles au lieu de dédier chaque port FC initiateur à un seul port cible.

Cependant, le partage des ports initiateurs ou cibles peut nuire aux performances.

.Informations associées
https://["Comment prendre en charge la configuration de l'initiateur partagé et de la cible partagée avec des LUN de baie dans un environnement MetroCluster"]

* La segmentation des commutateurs définit les chemins entre les nœuds connectés. La configuration du zoning permet de définir les LUN de baie pouvant être visualisées par des systèmes ONTAP spécifiques.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de switch dans une configuration MetroCluster à deux nœuds avec des LUN de baie"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de commutateur dans une configuration MetroCluster à quatre nœuds avec des LUN de baie"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Exemple de segmentation de commutateur dans une configuration MetroCluster à huit nœuds avec des LUN de baie"]


