---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: Les systèmes ONTAP, les baies de stockage et les commutateurs FC utilisés dans les configurations MetroCluster doivent respecter les exigences relatives à de tels types de configurations. Vous devez également tenir compte des exigences de SyncMirror pour les configurations MetroCluster avec des LUN de baies. 
---
= Configuration requise pour une MetroCluster avec des LUN de baies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes ONTAP, les baies de stockage et les commutateurs FC utilisés dans les configurations MetroCluster doivent respecter les exigences relatives à de tels types de configurations. Vous devez également tenir compte des exigences de SyncMirror pour les configurations MetroCluster avec des LUN de baies.



== Configuration requise pour les systèmes ONTAP

* Les systèmes ONTAP doivent être identifiés comme pris en charge pour les configurations MetroCluster.
+
Dans le https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp (IMT)"], Vous pouvez utiliser le champ solution de stockage pour sélectionner votre solution MetroCluster. Utilisez *Explorateur de composants* pour sélectionner les composants et la version ONTAP pour affiner votre recherche. Vous pouvez cliquer sur *Afficher les résultats* pour afficher la liste des configurations prises en charge qui correspondent aux critères.

+

NOTE: Vous devez vous reporter aux détails des alertes associées à toute configuration sélectionnée dans la matrice d'interopérabilité.

* Tous les systèmes ONTAP d'une configuration MetroCluster doivent être du même modèle.
* Des adaptateurs FC-VI doivent être installés dans les emplacements appropriés pour chaque système ONTAP, en fonction du modèle.
+
https://hwu.netapp.com["NetApp Hardware Universe"]





== Besoins en baies de stockage

* Les baies de stockage doivent être considérées comme prises en charge dans les configurations MetroCluster.
+
https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

* Les baies de stockage en configuration MetroCluster doivent être symétriques :
+
** Les deux baies de stockage doivent être de la même famille de fournisseurs pris en charge et la même version de micrologiciel doit être installée.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["Implémentation de la virtualisation FlexArray pour le stockage NetApp E-Series"]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["Implémentation de la virtualisation FlexArray pour stockage tiers"]

** Les types de disques (par exemple, SATA, SSD ou SAS) utilisés pour le stockage en miroir doivent être identiques sur les deux baies de stockage.
** Les paramètres de configuration des baies de stockage, tels que le type RAID et le Tiering, doivent être identiques sur les deux sites.






== Conditions requises pour les commutateurs FC

* Le micrologiciel des commutateurs et des commutateurs doit être identifié comme pris en charge dans les configurations MetroCluster.
+
https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

* Chaque structure doit avoir deux commutateurs FC.
* Chaque système ONTAP doit être connecté au stockage par des composants redondants de sorte qu'il existe une redondance en cas de panne des périphériques et des chemins.
* Les systèmes de stockage AFF A700, FAS9000, AFF A900 et FAS9500 prennent en charge jusqu'à huit liens ISL par structure. Les autres modèles de systèmes de stockage prennent en charge jusqu'à quatre liens ISL par structure.
* Les commutateurs doivent utiliser la configuration de base des commutateurs MetroCluster, les paramètres ISL et les configurations FC-VI.
+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configurez manuellement les commutateurs Cisco FC"]

+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurez manuellement les commutateurs Brocade FC"]





== Conditions requises pour le SyncMirror

* SyncMirror est requis pour une configuration MetroCluster.
* Deux baies de stockage distinctes, une sur chaque site, sont requises pour le stockage en miroir.
* Deux jeux de LUN de baie sont requis.
+
Un jeu est nécessaire pour l'agrégat sur la baie de stockage locale (pool0) et un autre ensemble est requis sur la baie de stockage distante pour le miroir de l'agrégat (l'autre plex de l'agrégat, pool1).

+
Pour la mise en miroir de l'agrégat, les LUN de baie doivent être de la même taille.

* Les agrégats non mis en miroir sont également pris en charge dans la configuration MetroCluster.
+
Ils ne sont pas protégés en cas d'incident sur site.




NOTE: Pour optimiser les performances et la disponibilité du stockage, il est recommandé de conserver au moins 20 % d'espace libre pour les agrégats en miroir. Bien que la recommandation soit de 10 % pour les agrégats non mis en miroir, le système de fichiers peut utiliser 10 % d'espace supplémentaire pour absorber les modifications incrémentielles. Les modifications incrémentielles augmentent l'utilisation de l'espace pour les agrégats en miroir grâce à l'architecture Snapshot d'ONTAP basée sur la copie en écriture. Le non-respect de ces meilleures pratiques peut avoir un impact négatif sur les performances.
