---
permalink: install-fc/reference_supported_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, supported, array, luns 
summary: Vous pouvez configurer soit une configuration MetroCluster avec des LUN de baie. Les configurations Stretch et Fabric-Attached sont prises en charge. Les systèmes AFF ne sont pas pris en charge avec les LUN de baies. 
---
= Configuration MetroCluster prise en charge avec des LUN de baies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer soit une configuration MetroCluster avec des LUN de baie. Les configurations Stretch et Fabric-Attached sont prises en charge. Les systèmes AFF ne sont pas pris en charge avec les LUN de baies.

Les fonctionnalités prises en charge par les configurations MetroCluster varient en fonction des types de configuration. Le tableau suivant répertorie les fonctionnalités prises en charge sur les différents types de configurations MetroCluster avec des LUN de baie :

|===


.2+| Fonction 3+| Configurations intégrées à la structure | Configurations Stretch 


| Huit nœuds | Quatre nœuds | Deux nœuds | Deux nœuds 


 a| 
Nombre de contrôleurs
 a| 
Huit
 a| 
Quatre
 a| 
Deux
 a| 
Deux



| Utilise une structure de stockage avec commutateur FC | Oui. | Oui. | Oui. | Oui. 


| Utilise des ponts FC-SAS | Oui. | Oui. | Oui. | Oui. 


| Prend en charge la haute disponibilité locale | Oui. | Oui. | Non | Non 


| Prend en charge le basculement automatique | Oui. | Oui. | Oui. | Oui. 
|===
.Informations associées
link:concept_considerations_differences.html["Différences entre les configurations ONTAP MetroCluster"]
