---
permalink: install-fc/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, additional, information 
summary: 'Pour plus d"informations sur la configuration et le fonctionnement de MetroCluster, consultez la documentation NetApp.' 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster,



== MetroCluster et informations diverses

|===


| Informations | Objet 


 a| 
https://["Documentation ONTAP 9"^]
 a| 
* Toutes les informations relatives aux MetroCluster




| https://["Architecture et conception de la solution NetApp MetroCluster, TR-4705"^]  a| 
* Présentation technique de la configuration et du fonctionnement de MetroCluster FC.
* Meilleures pratiques en matière de configuration MetroCluster FC.




| https://["Architecture et conception de la solution IP MetroCluster, TR-4689"^]  a| 
* Présentation technique de la configuration et du fonctionnement IP de MetroCluster.
* Meilleures pratiques pour la configuration MetroCluster IP.




 a| 
https://["Installation et configuration d'Stretch MetroCluster"]
 a| 
* Architecture MetroCluster extensible
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration de MetroCluster dans ONTAP




 a| 
https://["Installation et configuration IP de MetroCluster : différences entre les configurations ONTAP MetroCluster"]
 a| 
* Architecture de MetroCluster IP
* Câblage de la configuration
* Configuration de MetroCluster dans ONTAP




 a| 
https://["Gestion et reprise après incident MetroCluster"]
 a| 
* Présentation de la configuration MetroCluster
* Basculement, rétablissement et rétablissement
* Reprise après incident




 a| 
https://["Maintenance des composants MetroCluster"]
 a| 
* Instructions relatives à la maintenance dans une configuration MetroCluster FC
* Procédure de remplacement ou de mise à niveau du matériel et de mise à niveau du firmware pour les ponts FC-SAS et les commutateurs FC
* Ajout à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Retrait à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Remplacement du matériel sur un site d'incident dans une configuration MetroCluster FC Stretch ou Fabric-Attached
* Extension d'une configuration MetroCluster FC extensible ou Fabric-Attached à deux nœuds à une configuration MetroCluster à quatre nœuds.
* Extension d'une configuration MetroCluster FC à quatre nœuds (Fabric-Attached ou Stretch FC) à une configuration MetroCluster FC à huit nœuds.




 a| 
https://["Transition de MetroCluster FC à MetroCluster IP"]

https://["Guide de mise à niveau et d'extension de MetroCluster"]
 a| 
* Mise à niveau ou actualisation d'une configuration MetroCluster
* Passer d'une configuration MetroCluster FC à une configuration MetroCluster IP
* Extension d'une configuration MetroCluster par l'ajout de nœuds supplémentaires




 a| 
https://["Installation et configuration du logiciel MetroCluster Tiebreaker"]
 a| 
* Contrôle de la configuration de MetroCluster avec le logiciel MetroCluster Tiebreaker




 a| 
Documentation du conseiller digital Active IQ

https://["Documentation NetApp : guides et ressources produits"^]
 a| 
* Contrôle de la configuration et des performances d'MetroCluster




 a| 
https://["Transition basée sur la copie"^]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster




 a| 
https://["Concepts relatifs à ONTAP"^]
 a| 
* Fonctionnement des agrégats en miroir


|===