---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 'Vous devez vous assurer que les liaisons interswitch \(ISL\) se trouvent dans le même port group et configurer la segmentation pour les configurations MetroCluster afin que ces switchs puissent être partagés correctement.' 
---
= Vérifiez que les liens ISL sont dans le même port group et configurez la segmentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Veillez à ce que les liaisons intercommutateurs (ISL) se trouvent dans le même groupe de ports et configurez la segmentation pour les configurations MetroCluster afin de partager les structures des commutateurs.

.Étapes
. Si les liens ISL ne font pas partie du même port group, déplacez l'un des ports ISL vers le même groupe de ports que l'autre.
+
Vous pouvez utiliser n'importe quel port disponible, sauf 32 à 45, utilisé par la nouvelle configuration MetroCluster. Les ports ISL recommandés sont les ports 46 et 47.

. Suivez les étapes de la section link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuration de la segmentation sur les commutateurs Brocade FC"] Section pour activer la mise en circuit et la zone QoS.
+
Les numéros de port lors du partage de tissus sont différents de ceux affichés dans la section. Lors du partage, utilisez les ports 46 et 47 pour les ports ISL. Si vous avez déplacé vos ports ISL, vous devez utiliser la procédure dans le link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuration des E-ports (ports ISL) sur un commutateur FC Brocade"] section pour configurer les ports.

. [[step3_zones]] Suivez les étapes de la section link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuration des ports non-E sur le commutateur Brocade"] Section pour configurer les ports non-E.
. Ne supprimez pas les zones ou ensembles de zones qui existent déjà dans les commutateurs back-end (pour le MetroCluster de structure 7-mode), à l'exception des zones d'isolation du trafic (TI) dans ,Étape 3.
. Suivez les étapes de la section link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuration des E-ports (ports ISL) sur un commutateur FC Brocade"] Section pour ajouter les zones requises par le nouveau MetroCluster aux ensembles de zones existants.
+
L'exemple suivant montre les commandes et la sortie système pour la création des zones :

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

