---
permalink: install-fc/task_mirror_the_root_aggregates_mcc_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, mirror, root, aggregates 
summary: Pour assurer la protection des données, vous devez mettre en miroir les agrégats racine de votre configuration MetroCluster. 
---
= Mise en miroir des agrégats racine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour assurer la protection des données, vous devez mettre en miroir les agrégats racine de votre configuration MetroCluster.

.Avant de commencer
Vous devez vous assurer que les exigences SyncMirror pour la configuration MetroCluster avec des LUN de baie sont satisfaites. Reportez-vous à la sectionlink:reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html["Configuration requise pour une MetroCluster avec des LUN de baies"].

.Description de la tâche
Vous devez répéter cette tâche pour chaque contrôleur de la configuration MetroCluster.

.Étape
. Mettre en miroir l'agrégat racine sans miroir :
+
`storage aggregate mirror`

+
La commande suivante met en miroir l'agrégat root pour Controller_A_1 :

+
[listing]
----
controller_A_1::> storage aggregate mirror aggr0_controller_A_1
----
+
L'agrégat racine est mis en miroir avec des LUN de baie provenant de pool1.


