---
permalink: install-fc/task_install_the_license_for_us_array_luns_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, license, array, luns, configuration 
summary: 'Vous devez installer la licence V_StorageAttach sur chaque nœud MetroCluster que vous souhaitez utiliser avec les LUN de la baie. Vous ne pouvez pas utiliser de LUN de baies dans un agrégat tant que la licence n"est pas installée.' 
---
= Installation de la licence pour l'utilisation de LUN de baie dans une configuration MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer la licence V_StorageAttach sur chaque nœud MetroCluster que vous souhaitez utiliser avec les LUN de la baie. Vous ne pouvez pas utiliser de LUN de baies dans un agrégat tant que la licence n'est pas installée.

.Avant de commencer
* Le cluster doit être installé.
* Vous devez disposer de la clé de licence pour la licence V_StorageAttach.


Vous devez utiliser une clé de licence distincte pour chaque nœud sur lequel vous souhaitez installer la licence V_StorageAttach.

.Étapes
. Installez la licence V_StorageAttach.
+
`system license add`

+
Répétez cette étape pour chaque noeud du cluster sur lequel vous souhaitez installer la licence.

. Vérifiez que la licence V_StorageAttach est installée sur tous les nœuds requis dans un cluster.
+
`system license show`

+
L'exemple de résultat suivant montre que la licence V_StorageAttach est installée sur les nœuds du cluster_A :

+
[listing]
----

cluster_A::> system license show
Serial Number: nnnnnnnn
Owner: controller_A_1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage


Serial Number: llllllll
Owner: controller_A_2
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage
----

