---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, cisco, fc, switch, nx, software 
summary: 'Vous devez télécharger le fichier du système d"exploitation du switch et le fichier RCF sur chaque commutateur de la configuration MetroCluster Fabric.' 
---
= Téléchargement et installation du logiciel Cisco FC switch NX-OS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez télécharger le fichier du système d'exploitation du switch et le fichier RCF sur chaque commutateur de la configuration MetroCluster Fabric.

.Avant de commencer
Cette tâche nécessite un logiciel de transfert de fichiers, tel que FTP, TFTP, SFTP ou SCP, pour copier les fichiers sur les commutateurs.

.Description de la tâche
Ces étapes doivent être répétées sur chacun des commutateurs FC de la configuration MetroCluster Fabric.

Vous devez utiliser la version du logiciel de commutation prise en charge.

https://hwu.netapp.com["NetApp Hardware Universe"]


NOTE: Les sorties indiquées sont destinées aux commutateurs IP Cisco. Toutefois, ces étapes s'appliquent également aux commutateurs FC Cisco.

.Étapes
. Téléchargez le fichier logiciel NX-OS pris en charge.
+
https://software.cisco.com/download/home["Page de téléchargement Cisco"]

. Copier le logiciel du commutateur sur le commutateur :
+
`copy sftp://root@server-ip-address/tftpboot/NX-OS-file-name bootflash: vrf management`

+
Dans cet exemple, le `nxos.7.0.3.I4.6.bin` Le fichier est copié du serveur SFTP 10.10.99.99 vers le bootflash local :

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. Vérifiez sur chaque commutateur que les fichiers de commutateur NX-OS sont présents dans le répertoire bootflash de chaque commutateur :
+
`dir bootflash`

+
L'exemple suivant montre que les fichiers sont présents sur `IP_switch_A_1`:

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Installez le logiciel du commutateur :
+
`install all system bootflash:nxos.version-number.bin kickstart bootflash:nxos.version-kickstart-number.bin`

+
[listing]
----
IP_switch_A_1#  install all system bootflash:nxos.7.0.3.I4.6.bin kickstart bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "kickstart".
[####################] 100% -- SUCCESS

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "system".
[####################] 100% -- SUCCESS

Performing module support checks.                                                                                                            [####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Extracting "system" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Extracting "kickstart" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS
...
----
+
Le commutateur redémarre automatiquement après l'installation du logiciel du commutateur.

. Attendre que le commutateur se recharge, puis se connecter au commutateur.
+
Une fois le commutateur redémarré, l'invite de connexion s'affiche :

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. Vérifier que le logiciel du commutateur a été installé :
+
`show version`

+
L'exemple suivant montre la sortie :

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. Répétez ces étapes sur les trois commutateurs FC restants dans la configuration de structure MetroCluster.

