---
permalink: install-fc/task_cable_storage_arrays_to_fc_switches_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, storage, arrays, fc, switches, configuration 
summary: Vous devez connecter les baies de stockage aux commutateurs FC, de sorte que les systèmes ONTAP de la configuration MetroCluster puissent accéder à une LUN de baie spécifique via au moins deux chemins. 
---
= Câblage des baies de stockage aux commutateurs FC dans une configuration MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connecter les baies de stockage aux commutateurs FC, de sorte que les systèmes ONTAP de la configuration MetroCluster puissent accéder à une LUN de baie spécifique via au moins deux chemins.

.Avant de commencer
* Les baies de stockage doivent être configurées de façon à présenter des LUN de baie à ONTAP.
* Les contrôleurs ONTAP doivent être connectés aux commutateurs FC.
* Les liens ISL doivent être câblés entre les commutateurs FC sur les sites MetroCluster.
* Vous devez répéter cette tâche pour chaque baie de stockage des deux sites MetroCluster.
* Vous devez connecter les contrôleurs dans une configuration MetroCluster aux baies de stockage via des commutateurs FC.


.Étapes
. Connectez les ports de la matrice de stockage aux ports commutateurs FC.
+
Sur chaque site, connectez les paires de ports redondants de la baie de stockage aux commutateurs FC des autres structures. Cela fournit la redondance dans les chemins d'accès aux LUN de la baie.



.Informations associées
* La configuration de la segmentation de commutateur permet de définir les LUN de baie qui peuvent être affichées par un système ONTAP spécifique dans la configuration MetroCluster.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["Segmentation de commutateur dans une configuration MetroCluster avec des LUN de baie"]

* Dans une configuration MetroCluster avec des LUN de baie, vous devez connecter les ports de baie de stockage qui forment une paire de ports redondante avec d'autres commutateurs FC.
+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_two_node_mcc_configuration.html["Exemple de câblage des ports de la baie de stockage aux commutateurs FC dans une configuration MetroCluster à deux nœuds"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_mcc_configuration.html["Exemple de câblage des ports de la baie de stockage aux commutateurs FC dans une configuration MetroCluster à quatre nœuds"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_mcc_configuration.html["Exemple de câblage des ports de la baie de stockage aux commutateurs FC dans une configuration MetroCluster à huit nœuds"]


