---
permalink: install-fc/task_fcsw_configure_the_fc_switches_with_rcf_files_mcc.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, fc, switches, run, configuration, file 
summary: Si vous souhaitez simplifier le processus de configuration des commutateurs, vous pouvez télécharger et appliquer des fichiers de configuration de référence qui fournissent les paramètres de commutation complets pour certaines configurations. 
---
= Configuration des commutateurs FC en exécutant un fichier de configuration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez simplifier le processus de configuration des commutateurs, vous pouvez télécharger et appliquer des fichiers de configuration de référence qui fournissent les paramètres de commutation complets pour certaines configurations.

Les fichiers de configuration de référence (RCFs) ne prennent pas en charge les configurations via huit liens ISL. Si vous utilisez huit liens ISL, vous devez configurer les commutateurs manuellement.

Les RCFs s'appliquent aux configurations MetroCluster à deux, quatre et huit nœuds. Ces fichiers configurent par défaut le fabric pour la livraison dans l'ordre (IOD).

La page de téléchargement RCF indique le nombre de nœuds pris en charge par les différents modèles de commutateur.
