---
permalink: install-fc/task_rack_the_hardware_components_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, rack, hardware, components, array, luns 
summary: Vous devez vous assurer que les composants matériels nécessaires pour configurer une configuration MetroCluster avec des LUN de baies sont correctement mis en rack. 
---
= Mise en rack des composants matériels dans une configuration MetroCluster avec des LUN de baie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vous assurer que les composants matériels nécessaires pour configurer une configuration MetroCluster avec des LUN de baies sont correctement mis en rack.

.Description de la tâche
Vous devez effectuer cette tâche sur les deux sites MetroCluster.

.Étapes
. Planifiez le positionnement des composants MetroCluster.
+
L'espace rack dépend du modèle de plateforme des contrôleurs de stockage, des types de commutateurs et du nombre de piles de tiroirs disques dans votre configuration.

. Mettez-vous à la terre.
. Installez les contrôleurs de stockage sur le rack ou l'armoire.
+

NOTE: Les systèmes AFF ne sont pas pris en charge avec les LUN de baies.

+
https://["Procédures d'installation de votre système AFF ou FAS"]

. Installez les commutateurs FC sur le rack ou l'armoire.

