---
permalink: install-fc/task_configure_ontap_on_a_system_that_uses_only_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, array luns, ontap 
summary: 'Si vous souhaitez configurer le protocole ONTAP avec les LUN de baie, vous devez configurer l"agrégat racine et le volume racine, réserver de l"espace pour les opérations de diagnostic et de reprise et configurer le cluster.' 
---
= Configuration de ONTAP sur un système qui n'utilise que des LUN de baie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez configurer le protocole ONTAP avec les LUN de baie, vous devez configurer l'agrégat racine et le volume racine, réserver de l'espace pour les opérations de diagnostic et de reprise et configurer le cluster.

.Avant de commencer
* Le système ONTAP doit être connecté à la matrice de stockage.
* L'administrateur de la baie de stockage doit avoir créé des LUN et les présenter à ONTAP.
* L'administrateur de la matrice de stockage doit avoir configuré la sécurité de la LUN.


.Description de la tâche
Vous devez configurer chaque nœud que vous souhaitez utiliser avec des LUN de baie. Si le nœud est dans une paire HA, vous devez terminer le processus de configuration sur un nœud avant de poursuivre la configuration sur le nœud partenaire.

.Étapes
. Mettez le nœud principal sous tension et interrompez le processus de démarrage en appuyant sur Ctrl-C lorsque le message suivant s'affiche sur la console :
+
`Press CTRL-C for special boot menu.`

. Sélectionnez l'option *4 (nettoyer la configuration et initialiser tous les disques)* dans le menu d'amorçage.
+
La liste des LUN de baie mises à disposition de ONTAP s'affiche. En outre, la taille de LUN de baie requise pour la création du volume racine est également spécifiée. La taille requise pour la création du volume root diffère d'un système ONTAP à un autre.

+
** Si aucune LUN de baie n'a été affectée auparavant, ONTAP détecte et affiche les LUN de baie disponibles, comme illustré dans l'exemple suivant :
+
[listing]
----
mcc8040-ams1::> disk show  NET-1.6 -instance
                  Disk: NET-1.6
        Container Type: aggregate
            Owner/Home: mcc8040-ams1-01 / mcc8040-ams1-01
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_INF_1
                Vendor: NETAPP
                 Model: INF-01-00
         Serial Number: 60080E50004317B4000003B158E35974
                   UID: 60080E50:004317B4:000003B1:58E35974:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: 87.50GB
              Position: data
Checksum Compatibility: block
             Aggregate: eseries
                  Plex: plex0
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
mcc8040-ams1-01    2c             0  mccb6505-ams1:16      mccb6505-ams1:18      AO  INU  20330080e54317b4              1   4 Gb/S             0             0
mcc8040-ams1-01    2a             0  mccb6505-ams1:17      mccb6505-ams1:19      ANO RDY  20320080e54317b4              0   4 Gb/S             0             0

Errors:
-
----
** Si des LUN de baie étaient auparavant attribuées, par exemple, en mode maintenance, elles sont marquées comme partenaires ou locaux dans la liste des LUN de baie disponibles, selon que les LUN de baie ont été sélectionnées à partir du nœud sur lequel vous installez ONTAP ou son partenaire haute disponibilité :
+
Dans cet exemple, les LUN de tableau avec les numéros d'index 3 et 6 sont marquées comme étant « locales » car elles avaient été précédemment attribuées à partir de ce nœud particulier :

+
[listing]
----

**********************************************************************
* No disks are owned by this node, but array LUNs are assigned.      *
* You can use the following information to verify connectivity from  *
* HBAs to switch ports.  If the connectivity of HBAs to switch ports *
* does not match your expectations, configure your SAN and rescan.   *
* You can rescan by entering 'r' at the prompt for selecting         *
* array LUNs below.

**********************************************************************
             HBA  HBA WWPN           Switch port      Switch port WWPN
              ---  --------           -----------      ----------------
              0e 500a098001baf8e0  vgbr6510s203:25      20190027f88948dd
              0f 500a098101baf8e0 vgci9710s202:1-17      2011547feeead680
              0g 500a098201baf8e0  vgbr6510s203:27      201b0027f88948dd
              0h 500a098301baf8e0 vgci9710s202:1-18      2012547feeead680


No native disks were detected, but array LUNs were detected.
You will need to select an array LUN to be used to create the root aggregate and root volume.

The array LUNs visible to the system are listed below.  Select one array LUN to be used to
create the root aggregate and root volume.  **The root volume requires 350.0 GB of space.**

 Warning: The contents of the array LUN you select will be erased by ONTAP prior to their use.

Index  Array LUN Name           Model   Vendor    Size    Owner   Checksum  Serial Number
-----  -----------------------  ------  ------  --------  ------  --------  ------------------------
   0   vgci9710s202:2-24.0L19   RAID5   DGC     217.3 GB          Block     6006016083402B0048E576D7
   1   vgbr6510s203:30.126L20   RAID5   DGC     217.3 GB          Block     6006016083402B0049E576D7
   2   vgci9710s202:2-24.0L21   RAID5   DGC     217.3 GB          Block     6006016083402B004AE576D7
   3   vgbr6510s203:30.126L22   RAID5   DGC     405.4 GB  local   Block     6006016083402B004BE576D7
   4   vgci9710s202:2-24.0L23   RAID5   DGC     217.3 GB          Block     6006016083402B004CE576D7
   5   vgbr6510s203:30.126L24   RAID5   DGC     217.3 GB          Block     6006016083402B004DE576D7
   6   vgbr6510s203:30.126L25   RAID5   DGC     423.5 GB  local   Block     6006016083402B003CF93694
   7   vgci9710s202:2-24.0L26   RAID5   DGC     423.5 GB          Block     6006016083402B003DF93694
----


. Sélectionnez le numéro d'index correspondant au LUN de tableau que vous souhaitez attribuer en tant que volume racine.
+
La taille de la LUN de matrice doit être suffisante pour créer le volume racine.

+
La LUN de matrice sélectionnée pour la création du volume racine est marquée "local (root)".

+
Dans l'exemple suivant, la LUN de tableau avec l'index numéro 3 est marquée pour la création du volume racine :

+
[listing]
----

The root volume will be created on switch 0:5.183L33.

**ONTAP requires that 11.0 GB of space be reserved for use in diagnostic and recovery
operations.**  Select one array LUN to be used as spare for diagnostic and recovery operations.

Index Array LUN Name    Model       Vendor    Size   Owner           Checksum  Serial Number
----- ----------------- ----------  ------  -------- --------------  --------  ------------------------
   0  switch0:5.183L1   SYMMETRIX   EMC     266.1 GB                 Block     600604803436313734316631
   1  switch0:5.183L3   SYMMETRIX   EMC     266.1 GB                 Block     600604803436316333353837
   2  switch0:5.183L31  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237643666
   3  switch0:5.183L33  SYMMETRIX   EMC     658.3 GB local  (root)   Block     600604803436316263613066
   4  switch0:7.183L0   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313261356235
   5  switch0:7.183L2   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313438396431
   6  switch0:7.183L4   SYMMETRIX   EMC     658.3 GB                 Block     600604803436313161663031
   7  switch0:7.183L30  SYMMETRIX   EMC     173.6 GB                 Block     600604803436316538353834
   8  switch0:7.183L32  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237353738
   9  switch0:7.183L34  SYMMETRIX   EMC     658.3 GB                 Block     600604803436313737333662
----
. Sélectionnez le numéro d'index correspondant à la LUN de tableau que vous souhaitez attribuer pour une utilisation dans les options de diagnostic et de récupération.
+
La taille de la LUN de matrice doit être suffisante pour être utilisée dans les options de diagnostic et de récupération. Si nécessaire, vous pouvez également sélectionner plusieurs LUN de baie dont la taille combinée est supérieure ou égale à la taille spécifiée. Pour sélectionner plusieurs entrées, vous devez entrer les valeurs séparées par des virgules de tous les numéros d'index correspondant aux LUN de tableau que vous souhaitez sélectionner pour les options de diagnostic et de récupération.

+
L'exemple suivant montre la liste des LUN de baie sélectionnées pour la création du volume racine et pour les options de diagnostic et de restauration :

+
[listing]
----

Here is a list of the selected array LUNs
Index Array LUN Name     Model      Vendor    Size    Owner          Checksum  Serial Number
----- -----------------  ---------  ------  --------  -------------  --------  ------------------------
   2  switch0:5.183L31   SYMMETRIX  EMC     266.1 GB  local          Block     600604803436313237643666
   3  switch0:5.183L33   SYMMETRIX  EMC     658.3 GB  local   (root) Block     600604803436316263613066
   4  switch0:7.183L0    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313261356235
   5  switch0:7.183L2    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313438396431
Do you want to continue (yes|no)?
----
+

NOTE: Si vous sélectionnez « non », la sélection de LUN est effacée.

. Entrez `*y*` lorsque le système vous invite à poursuivre le processus d'installation.
+
L'agrégat root et le volume root sont créés et le reste du processus d'installation continue.

. Entrez les détails requis pour créer l'interface de gestion de nœuds.
+
L'exemple suivant montre l'écran de l'interface de gestion des nœuds avec un message confirmant la création de l'interface de gestion des nœuds :

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
Enter the node management interface IP address: 192.0.2.66

Enter the node management interface netmask: 255.255.255.192
Enter the node management interface default gateway: 192.0.2.7
A node management interface on port e0M with IP address 192.0.2.66 has been created.

This node has its management address assigned and is ready for cluster setup.
----


.Une fois que vous avez terminé
Une fois que vous avez configuré ONTAP sur tous les nœuds que vous souhaitez utiliser avec les LUN de la baie, vous devez terminer l'opérationhttps://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html["Processus de configuration du cluster"]

.Informations associées
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["Conditions requises pour l'installation et référence de la virtualisation FlexArray"]
