---
permalink: install-fc/task_reset_the_cisco_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, cisco, fc, switch, factory, defaults 
summary: 'Avant d"installer une nouvelle version du logiciel et des RCFs, vous devez effacer la configuration du commutateur Cisco et effectuer la configuration de base.' 
---
= Réinitialisation des paramètres d'usine du commutateur Cisco FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer une nouvelle version du logiciel et des RCFs, vous devez effacer la configuration du commutateur Cisco et effectuer la configuration de base.

.Description de la tâche
Vous devez répéter ces étapes sur chacun des commutateurs FC dans la configuration de la structure MetroCluster.


NOTE: Les sorties indiquées sont destinées aux commutateurs IP Cisco. Toutefois, ces étapes s'appliquent également aux commutateurs FC Cisco.

.Étapes
. Rétablir les paramètres d'usine du commutateur :
+
.. Effacez la configuration existante : +
`*write erase*`
.. Recharger le logiciel du contacteur : +
`*reload*`
+
Le système redémarre et entre dans l'assistant de configuration. Au cours du démarrage, si vous recevez l'invite abandonner la mise en service automatique et poursuivre la configuration normale ?(oui/non)[n], vous devez répondre `*yes*` pour continuer.

.. Dans l'assistant de configuration, entrez les paramètres de base du commutateur :
+
*** Mot de passe d'administrateur
*** Nom du commutateur
*** Configuration de gestion hors bande
*** Passerelle par défaut
*** Service SSH (Remote support Agent).
+
Une fois l'assistant de configuration terminé, le commutateur redémarre.



.. Lorsque vous y êtes invité, entrez le nom d'utilisateur et le mot de passe pour vous connecter au commutateur.
+
L'exemple suivant montre les invites et les réponses du système lors de la connexion au commutateur. Les supports d'angle (`*<<<*`) indique où vous saisissez les informations.

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

    Enter the password for "admin": password  **<<<**
  Confirm the password for "admin": password  **<<<**
         ---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus3000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus3000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.
----
.. Saisissez les informations de base dans les invites suivantes, notamment le nom du commutateur, l'adresse de gestion et la passerelle, puis entrez `*rsa*` Pour la clé SSH comme indiqué dans l'exemple :
+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
    Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
    Number of rsa key bits <1024-2048> [1024]:
  Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
  Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
Le jeu d'invites final termine la configuration :

+
[listing]
----
The following configuration will be applied:
  password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
  no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. Enregistrez la configuration :
+
[listing]
----
IP_switch_A_1# copy running-config startup-config
----
. Redémarrez le commutateur et attendez que le commutateur se recharge :
+
[listing]
----
IP_switch_A_1# reload
----
. Répétez les étapes précédentes sur les trois autres commutateurs de la configuration de structure MetroCluster.

