---
permalink: install-fc/task_cable_the_isl_between_the_mcc_sites_fabric_config.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, isl, sites 
summary: 'Vous devez connecter les commutateurs FC sur chaque site via les liaisons intercommutateurs à fibre optique \(ISL\) pour former les structures de commutation qui connectent les composants MetroCluster.' 
---
= Câblage des liens ISL entre les sites MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connecter les commutateurs FC sur chaque site via les liaisons ISL de fibre optique pour former les structures de commutation qui relient les composants MetroCluster.

.Description de la tâche
Cela doit être effectué pour les deux fabriques de commutateurs.

.Étapes
. Connectez les commutateurs FC de chaque site à tous les liens ISL, en utilisant le câblage dans le tableau correspondant à votre configuration et à votre modèle de commutateur.
+
** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Affectation de ports pour les commutateurs FC lors de l'utilisation de ONTAP 9.1 et versions ultérieures"]
** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["Affectation des ports pour les commutateurs FC lors de l'utilisation de ONTAP 9.0"]




.Informations associées
link:concept_considerations_isls_mcfc.html["Considérations relatives aux liens ISL"]
