---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, brocade, fc, switch, rcf, file 
summary: 'Vous devez télécharger le fichier de configuration de référence \(RCF\) sur chaque commutateur de la configuration MetroCluster Fabric.' 
---
= Téléchargez le fichier RCF du commutateur Brocade FC dans une configuration FC MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez télécharger le fichier de configuration de référence (RCF) sur chaque commutateur dans la configuration de la structure MetroCluster.

.Description de la tâche
Pour utiliser ces RCF, le système doit exécuter ONTAP 9.1 ou une version ultérieure et vous devez utiliser la configuration de ports pour ONTAP 9.1 ou une version ultérieure.

Si vous prévoyez d'utiliser un seul des ports FC sur les ponts FibreBridge, configurez manuellement les commutateurs Fibre Channel back-end en suivant les instructions de la section, link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Affectations de ports pour les commutateurs FC"] .

.Étapes
. Consultez le tableau RCF sur la page de téléchargement des RCF de Brocade et identifiez le RCF correct pour chaque commutateur de votre configuration.
+
Les RCF doivent être appliqués aux commutateurs appropriés.

. Téléchargez les fichiers RCF pour les commutateurs depuis la  https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["Téléchargement de MetroCluster RCF"] page.
+
Les fichiers doivent être placés dans un emplacement où ils peuvent être transférés vers le commutateur. Il existe un fichier distinct pour chacun des quatre commutateurs qui constituent la structure à deux commutateurs.

. Répétez ces étapes sur chaque commutateur de la configuration.

