---
permalink: install-fc/task_fmc_mcc_transition_configure_zone_and_qos.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, delete, ti, zoning, tod, settings 
summary: 'Vous devez supprimer le zoning TI existant et reconfigurer les paramètres \(IOD\) de livraison dans l"ordre sur la structure de commutation.' 
---
= Suppression de la segmentation TI et configuration des paramètres IOD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez supprimer le zoning TI existant et reconfigurer les paramètres IOD (In-Order-Delivery) sur la structure de commutation.

.Étapes
. Identifiez les zones TI configurées sur la structure :
+
`zone --show`

+
L'exemple suivant montre la zone FCVI_TI_FAB_2.

+
[listing]
----
Brocade-6510:admin> zone --show
   Defined TI zone configuration:
   TI Zone Name:   FCVI_TI_FAB_2
   Port List:      1,0; 1,3; 2,0; 2,3
   configured Status: Activated / Failover-Disabled
   Enabled Status: Activated / Failover-Disabled
----
. Supprimer les zones TI :
+
`zone --delete _zone-name_`

+
L'exemple suivant montre la suppression de la zone FCVI_TI_FAB_2.

+
[listing]
----
Brocade-6510:admin> zone --delete FCVI_TI_FAB_2
----
. Vérifiez que les zones ont été supprimées :
+
`zone --show`

+
La sortie doit être similaire à ce qui suit :

+
[listing]
----
Brocade-6510:admin> zone -–show

    Defined TI zone configuration:
    no TI zone configuration defined
----
. Enregistrez la configuration :
+
`cfgsave`

. Activer la livraison dans l'ordre :
+
`iodset`

. Sélectionnez la règle APT (Advanced Performance Tuning) 1, la stratégie de routage basée sur le port :
+
`aptpolicy 1`

. Désactiver le partage dynamique de charge (DLS) :
+
`dlsreset`

. Vérifiez les paramètres IOD :
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
La sortie doit être similaire à ce qui suit :

+
[listing]
----
Brocade-6510:admin> iodshow

IOD is set

Brocade-6510:admin> aptpolicy
 Current Policy: 1

 3 : Default Policy
 1: Port Based Routing Policy
 2: Device Based Routing Policy (FICON support only)
 3: Exchange Based Routing Policy
Brocade-6510:admin> dlsshow

DLS is not set
----

