---
permalink: install-fc/task_fmc_mcc_transition_cable_the_new_mcc_controllers_to_the_exist_fc_fabrics.html 
sidebar: sidebar 
keywords: cabling, metrocluster, fabric, installation, fc, controllers 
summary: 'Sur chaque contrôleur de la configuration clustered ONTAP MetroCluster, l"adaptateur FC-VI et les HBA doivent être câblés à des ports spécifiques sur les commutateurs FC existants.' 
---
= Câblage des nouveaux contrôleurs MetroCluster aux structures FC existantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sur chaque contrôleur de la configuration ONTAP MetroCluster, l'adaptateur FC-VI et les HBA doivent être câblés sur des ports spécifiques des commutateurs FC existants.

.Étapes
. Reliez les ports FC-VI et HBA selon le tableau suivant :
+
|===


2+| Site A 2+| Site B 


| Connecter ce site Un composant et un port... | Port FC_Switch_A_1... | Connecter ce composant et le port du site B... | Port FC_Switch_B_1... 


 a| 
Port FC-VI Controller_A_1 1
 a| 
32
 a| 
Port FC-VI Controller_B_1 1
 a| 
32



 a| 
Port 1 de l'adaptateur HBA Controller_A_1
 a| 
33
 a| 
Port 1 de l'adaptateur HBA Controller_B_1
 a| 
33



 a| 
Port 2 de l'adaptateur HBA Controller_A_1
 a| 
34
 a| 
Port 2 de l'adaptateur HBA Controller_B_1
 a| 
34



 a| 
Port FC-VI Controller_A_2 1
 a| 
35
 a| 
Port FC-VI Controller_B_2 1
 a| 
35



 a| 
Carte HBA Controller_A_2 1
 a| 
36
 a| 
Carte HBA contrôleur_B_2 1
 a| 
36



 a| 
Adaptateur bus hôte Controller_A_2 2
 a| 
37
 a| 
HBA contrôleur_B_2 2
 a| 
37

|===
. Reliez chaque pont FC-SAS dans la première structure de commutateurs aux commutateurs FC.
+
Le nombre de ponts varie en fonction du nombre de piles de stockage SAS.

+
|===


2+| Site A 2+| Site B 


| Raccorder ce site À un pont... | Port FC_Switch_A_1... | Raccorder ce pont du site B... | Port FC_Switch_B_1... 


 a| 
Bridge_A_1_38
 a| 
38
 a| 
Bridge_B_1_38
 a| 
38



 a| 
Bridge_A_1_39
 a| 
39
 a| 
Bridge_B_1_39
 a| 
39

|===
. Reliez chaque pont dans le second fabric de commutateur aux commutateurs FC.
+
Le nombre de ponts varie en fonction du nombre de piles de stockage SAS.

+
|===


2+| Site A 2+| Site B 


| Raccorder ce site À un pont... | Port FC_Switch_A_2... | Raccorder ce pont du site B... | Port FC_Switch_B_2... 


 a| 
Bridge_A_2_38
 a| 
38
 a| 
Bridge_B_2_38
 a| 
38



 a| 
Bridge_A_2_39
 a| 
39
 a| 
Bridge_B_2_39
 a| 
39

|===

