---
permalink: install-fc/task_prepare_a_storage_array_for_use_with_ontap_systems.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, prepare, storage, array, systems 
summary: 'Avant de pouvoir commencer à configurer des systèmes ONTAP dans une configuration MetroCluster avec des LUN de baie, l"administrateur de la baie de stockage doit préparer le système de stockage pour une utilisation avec ONTAP.' 
---
= Préparation d'une baie de stockage à l'utilisation avec les systèmes ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir commencer à configurer des systèmes ONTAP dans une configuration MetroCluster avec des LUN de baie, l'administrateur de la baie de stockage doit préparer le système de stockage pour une utilisation avec ONTAP.

Les baies de stockage, les firmwares et les commutateurs que vous prévoyez d'utiliser dans la configuration doivent être pris en charge par la version ONTAP spécifique.

* https://mysupport.netapp.com/NOW/products/interoperability["Interopérabilité NetApp (IMT)"]
+
Dans le IMT, vous pouvez utiliser le champ solution de stockage pour sélectionner votre solution MetroCluster. Utilisez *Explorateur de composants* pour sélectionner les composants et la version ONTAP pour affiner votre recherche. Vous pouvez cliquer sur *Afficher les résultats* pour afficher la liste des configurations prises en charge qui correspondent aux critères.

* https://hwu.netapp.com["NetApp Hardware Universe"]


Vous devez coordonner cette tâche avec l'administrateur de la baie de stockage.

.Étapes
. Créez des LUN sur la baie de stockage en fonction du nombre de nœuds de la configuration MetroCluster.
+
Chaque nœud de la configuration MetroCluster nécessite des LUN de baie pour l'agrégat racine, l'agrégat de données et les Spares.

. Configurez les paramètres de la baie de stockage requis pour fonctionner avec ONTAP.
+
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["Implémentation de la virtualisation FlexArray pour stockage tiers"]
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["Implémentation de la virtualisation FlexArray pour le stockage NetApp E-Series"]



