= 
:allow-uri-read: 


Vous devez créer un agrégat de données en miroir sur chaque nœud du groupe de reprise sur incident.

.Description de la tâche
* Vous devez savoir quels disques seront utilisés dans le nouvel agrégat.
* Si votre système comporte plusieurs types de disques (stockage hétérogène), vous devez comprendre comment vous pouvez vous assurer que le type de disque correct est sélectionné.
* Les disques sont détenus par un nœud spécifique ; lorsque vous créez un agrégat, tous les disques de cet agrégat doivent être détenus par le même nœud, qui devient le nœud de rattachement de cet agrégat.
+
Dans les systèmes utilisant ADP, des agrégats sont créés à l'aide de partitions dans lesquelles chaque disque est partitionné en partitions P1, P2 et P3.

* Les noms d'agrégats doivent être conformes au schéma de nommage que vous avez déterminé lors de la planification de votre configuration MetroCluster.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestion des disques et des agrégats"]

* Les noms des agrégats doivent être uniques sur l'ensemble des MetroCluster sites. Cela signifie que vous ne pouvez pas avoir deux agrégats différents portant le même nom sur le site A et le site B.



NOTE: Il est recommandé de conserver au moins 20 % d'espace libre pour les agrégats en miroir afin d'optimiser les performances et la disponibilité du stockage. Bien que la recommandation soit de 10 % pour les agrégats non en miroir, les 10 % d'espace supplémentaires peuvent être utilisés par le système de fichiers pour absorber les modifications incrémentales. Les modifications incrémentales augmentent l'utilisation de l'espace pour les agrégats en miroir en raison de l'architecture de type copie sur écriture basée sur les snapshots d'ONTAP. Le non-respect de ces bonnes pratiques peut avoir un impact négatif sur les performances.

.Étapes
. Afficher la liste des pièces de rechange disponibles :
+
`storage disk show -spare -owner <node_name>`

. Créer l'agrégat :
+
`storage aggregate create -mirror true`

+
Si vous êtes connecté au cluster sur l'interface de gestion du cluster, vous pouvez créer un agrégat sur n'importe quel nœud du cluster. Pour vérifier que l'agrégat est créé sur un nœud spécifique, utilisez le  `-node` paramètre ou spécifiez des lecteurs qui sont la propriété de ce nœud.

+
Vous pouvez spécifier les options suivantes :

+
** Nœud de rattachement de l'agrégat (c'est-à-dire le nœud qui détient l'agrégat en fonctionnement normal)
** Liste de disques spécifiques à ajouter à l'agrégat
** Nombre de disques à inclure
+

NOTE: Dans la configuration minimale prise en charge, dans laquelle un nombre limité de disques sont disponibles, vous devez utiliser l'option force-petits agrégats pour créer un agrégat RAID-DP à trois disques.

** Style de checksum à utiliser pour l'agrégat
** Type de disques à utiliser
** Taille des disques à utiliser
** Vitesse de conduite à utiliser
** Type RAID des groupes RAID sur l'agrégat
** Nombre maximal de disques pouvant être inclus dans un groupe RAID
** Indique si les disques à régime différent sont autorisés
+
Pour plus d'informations sur ces options, reportez-vous au `storage aggregate create` page de manuel.

+
La commande suivante crée un agrégat en miroir avec 10 disques :

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. Vérifier le groupe RAID et les disques de votre nouvel agrégat :
+
`storage aggregate show-status -aggregate <aggregate-name>`


