= 
:allow-uri-read: 


Certaines plates-formes utilisent un VLAN pour l'interface IP de MetroCluster. Par défaut, chacun des deux ports utilise un VLAN différent : 10 et 20.

+ si pris en charge, vous pouvez également spécifier un VLAN différent (non par défaut) supérieur à 100 (entre 101 et 4095) en utilisant le `-vlan-id` paramètre de la `metrocluster configuration-settings interface create` commande.

+ les plates-formes suivantes ne supportent pas le `-vlan-id` paramètre :

+ ** FAS8200 et AFF A300 ** AFF A320 ** FAS9000 et AFF A700 ** AFF C800, ASA C800, AFF A800 et ASA A800

+ toutes les autres plates-formes supportent le `-vlan-id` paramètre.

+ les affectations VLAN par défaut et valides dépendent de la prise en charge du paramètre par la plate-forme `-vlan-id` :

+

[role="tabbed-block"]
====
.Les plateformes qui prennent en charge <code>-vlan-</code>
--
VLAN par défaut :

* Lorsque le `-vlan-id` paramètre n'est pas spécifié, les interfaces sont créées avec le VLAN 10 pour les ports "A" et le VLAN 20 pour les ports "B".
* Le VLAN spécifié doit correspondre au VLAN sélectionné dans la FCR.


Plages VLAN valides :

* VLAN 10 et 20 par défaut
* VLAN 101 et supérieur (entre 101 et 4095)


--
.Les plateformes qui ne prennent pas en charge <code>-vlan-</code>
--
VLAN par défaut :

* Sans objet L'interface ne nécessite pas la spécification d'un VLAN sur l'interface MetroCluster. Le port du commutateur définit le VLAN utilisé.


Plages VLAN valides :

* Tous les VLAN non explicitement exclus lors de la génération de la FCR. Le RCF vous avertit si le VLAN n'est pas valide.


--
====