---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: De nouvelles fonctionnalités du médiateur ONTAP sont fournies avec chaque version.  Voici les nouveautés. 
---
= Nouveautés de la prise en charge du médiateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De nouvelles améliorations du médiateur ONTAP sont fournies avec chaque version.  Voici les nouveautés.

[cols="75,25"]
|===


| Version/capacité du Mediator ONTAP | Version ONTAP 


 a| 
Le Mediator 1.5 de ONTAP est disponible pour la surveillance des configurations IP de MetroCluster.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installez ou mettez à niveau le service ONTAP Mediator"^]
 a| 
ONTAP 9.12.1



 a| 
La version 1.4 du logiciel Mediator de ONTAP est prise en charge dans les configurations IP de MetroCluster.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installez ou mettez à niveau le service ONTAP Mediator"^]
 a| 
ONTAP 9.11.1



 a| 
Le service ONTAP Mediator peut aider la configuration IP de MetroCluster à effectuer un basculement automatique non planifié en fournissant un référentiel physiquement distinct pour les informations d'état.
Configuration du service médiateur ONTAP pour un basculement automatique non planifié
 a| 
ONTAP 9.7

|===