---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: De nouvelles fonctionnalités du médiateur ONTAP sont fournies avec chaque version.  Voici les nouveautés. 
---
= Nouveautés de la prise en charge du médiateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De nouvelles améliorations du médiateur ONTAP sont fournies avec chaque version.  Voici les nouveautés.

Pour plus de détails sur l'installation ou la mise à niveau du médiateur ONTAP dans votre configuration MetroCluster, rendez-vous sur link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html["Préparez-vous à installer le service ONTAP Mediator"^].

[cols="75,25"]
|===


| Capacité du médiateur ONTAP | Version ONTAP 


 a| 
Le basculement automatique non planifié (MAUSO) assisté par un médiateur est pris en charge en cas d'arrêt de l'environnement.

Si un site s'arrête normalement en raison d'un arrêt environnemental, MAUSO est déclenché.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Prise en charge du protocole ONTAP pour le basculement automatique non planifié"]
 a| 
ONTAP 9.13.1



 a| 
Prise en charge initiale du service Mediator ONTAP dans les configurations IP MetroCluster
 a| 
ONTAP 9.7

|===