---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: De nouvelles fonctionnalités du médiateur ONTAP sont fournies avec chaque version.  Voici les nouveautés. 
---
= Nouveautés de la prise en charge du médiateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De nouvelles améliorations d’ONTAP Mediator sont fournies avec chaque version. Voici les nouveautés.

Pour plus de détails sur l'installation ou la mise à niveau d'ONTAP Mediator dans votre configuration MetroCluster, vous pouvez accéder à link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html["Préparez-vous à installer ONTAP Mediator"^] .

[cols="75,25"]
|===


| Capacité du médiateur ONTAP | Version ONTAP 


 a| 
Le basculement automatique non planifié (MAUSO) assisté par un médiateur est pris en charge en cas d'arrêt de l'environnement.

Si un site s'arrête normalement en raison d'un arrêt environnemental, MAUSO est déclenché.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Comment ONTAP Mediator prend en charge le basculement automatique non planifié"]
 a| 
ONTAP 9.13.1



 a| 
Prise en charge initiale d'ONTAP Mediator dans les configurations IP MetroCluster
 a| 
ONTAP 9.7

|===