---
permalink: releasenotes/mcc-ip-config-platform-support.html 
sidebar: sidebar 
keywords: metrocluster, ip configuration, platform, support 
summary:  
---
= Nouveautés de la prise en charge de la plateforme MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les configurations IP de MetroCluster ne sont pas prises en charge par les LUN de baies.

[cols="2*"]
|===
| Plateformes prises en charge dans les configurations MetroCluster IP | Disponible au début 


 a| 
AFF A150
 a| 
ONTAP 9.13.1 et versions ultérieures de ONTAP

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
AFF C250, AFF C400, AFF C800
 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA et versions ultérieures ONTAP.

[NOTE]
====
Ces plateformes ne sont pas prises en charge avec ONTAP 9.13.1 RC1.

====


 a| 
AFF A900
 a| 
ONTAP 9.10.1



 a| 
AFF A250
 a| 
ONTAP 9.8



 a| 
FAS500f
 a| 
ONTAP 9.8



 a| 
Plateformes des baies SAN 100 % Flash

Dans la documentation MetroCluster, les informations relatives aux modèles AFF s'appliquent au système ASA correspondant. Par exemple, tous les câbles et autres informations du système AFF A400 s'appliquent également au système ASA AFF A400.
 a| 
ONTAP 9.7



 a| 
AFF A320
 a| 
ONTAP 9.6P3



 a| 
AFF A220 ET FAS2750
 a| 
ONTAP 9.6



 a| 
AFF A300 ET FAS8200
 a| 
ONTAP 9.5

|===