---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: De nouvelles fonctionnalités du médiateur ONTAP sont fournies avec chaque version.  Voici les nouveautés. 
---
= Nouveautés concernant la prise en charge ONTAP Mediator pour les adresses IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités et améliorations de MetroCluster IP pour la prise en charge ONTAP Mediator.

Pour plus de détails sur les fonctionnalités et les améliorations de chaque version d' ONTAP Mediator, veuillez consulter :link:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["Nouveautés d' ONTAP Mediator"^] .

[cols="4,2"]
|===
| Capacité du médiateur ONTAP | Disponible au début 


 a| 
Le protocole IPv6 est pris en charge pour ONTAP Mediator 1.11 ou version ultérieure dans les configurations IP de MetroCluster .

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Configurer le médiateur ONTAP pour une configuration IP MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 ajoute la prise en charge de la gestion d'un maximum de dix configurations IP MetroCluster à l'aide d'une seule instance ONTAP Mediator.

link:../install-ip/concept_mediator_requirements.html["Préparez-vous à installer le médiateur ONTAP dans une configuration IP MetroCluster."]
 a| 
ONTAP 9.18.1



 a| 
Le basculement automatique non planifié (MAUSO) assisté par un médiateur est pris en charge en cas d'arrêt de l'environnement.

Si un site s'arrête normalement en raison d'un arrêt environnemental, MAUSO est déclenché.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Comment ONTAP Mediator prend en charge le basculement automatique non planifié"]
 a| 
ONTAP 9.13.1



 a| 
Prise en charge initiale d'ONTAP Mediator dans les configurations IP MetroCluster
 a| 
ONTAP 9.7

|===