---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= Nouveautés des fonctionnalités MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque version du logiciel de gestion des données ONTAP 9 inclut de nouvelles fonctionnalités améliorées qui améliorent les fonctionnalités, la gestion et les performances des configurations ONTAP MetroCluster.

Pour plus d'informations sur les problèmes connus, les limites et les mises en garde de mise à niveau affectant les configurations ONTAP MetroCluster, reportez-vous au https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP 9"^]. Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

[cols="20,65,15"]
|===
| Fonctionnalités prises en charge en configuration MetroCluster | Description et où en savoir plus | Disponible au début 


 a| 
SnapMirror cloud : prise en charge pour MetroCluster FlexGroup volumes
 a| 
SnapMirror cloud prend en charge les opérations de sauvegarde et de restauration pour les volumes FlexGroup dans les configurations MetroCluster.

link:https://docs.netapp.com/us-en/ontap/data-protection/cloud-backup-with-snapmirror-task.html#delete-a-snapmirror-cloud-relationship["Sauvegardez les données dans le cloud à l'aide de ONTAP SnapMirror"^]
 a| 
ONTAP 9.18.1GA



 a| 
Nouvelles combinaisons de mise à niveau prises en charge pour les mises à niveau de contrôleurs IP MetroCluster à l'aide des commandes  `system controller replace`
 a| 
Prise en charge des mises à niveau des systèmes AFF A70 vers AFF A90 et FAS70 vers FAS90 à l'aide des commandes  `system controller replace` dans une configuration IP MetroCluster.

link:../upgrade/upgrade-mcc-ip-system-controller-replace.html["Mise à niveau des contrôleurs dans une configuration MetroCluster IP à quatre nœuds via le basculement et le rétablissement à l'aide des commandes « system Controller replace » (ONTAP 9.13.1 et versions ultérieures)"]
 a| 
ONTAP 9.18.1GA



 a| 
Prise en charge du cache Flash pour les systèmes FAS50 dans les configurations IP MetroCluster
 a| 
La mémoire cache Flash est prise en charge sur les systèmes FAS50 dans les configurations IP MetroCluster .

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["Attribution de disque sur les systèmes FAS50 avec cache Flash"]
 a| 
ONTAP 9.18.1



 a| 
Prise en charge de MetroCluster IP pour un chiffrement de bout en bout
 a| 
Le chiffrement de bout en bout est pris en charge sur les systèmes suivants pour chiffrer le trafic back-end, tel que les données de réplication NVlog et de stockage, entre les sites d'une configuration IP MetroCluster .

* AFF A800, AFF C800
* AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
* AFF A70, AFF A90, AFF A1K, AFF C80
* FAS50, FAS70, FAS90


link:../maintain/task-configure-encryption.html["Configurer le chiffrement de bout en bout dans une configuration MetroCluster IP"]
 a| 
ONTAP 9.17.1



 a| 
Limiter les modifications pour les configurations IP MetroCluster
 a| 
ONTAP 9.17.1 inclut les mises à jour de limites suivantes pour les configurations IP MetroCluster à quatre nœuds :

* Les systèmes AFF C800, AFF A800, AFF A900, AFF A90 et AFF A1K ont les limites mises à jour suivantes :
+
** Limites de FlexVol volume par nœud : 1 250
** Limites SVM : 64 SVM par cluster
** Nombre de LIF : 256 LIF par cluster


* Les systèmes AFF A400, AFF C400, ASA A400, ASA C400, AFF C80, AFF A70 et AFF A50 ont les limites mises à jour suivantes :
+
** Limites de FlexVol volume par agrégat (simple ou multiple) : 625
** Limites de FlexVol volume par nœud : 1 250
** Limites de FlexVol volume par paire haute disponibilité (HA) : 2 500
** Limites de FlexVol volume par cluster : 5 000
** Limites SVM : 64 SVM par cluster
** Nombre de LIF : 256 LIF par cluster




Se référer à la link:https://hwu.netapp.com["Hardware Universe"^] pour plus d'informations.
 a| 
ONTAP 9.17.1



 a| 
Mise à jour du micrologiciel FibreBridge à l'aide des informations d'identification
 a| 
Vous pouvez mettre à jour le micrologiciel sur les ponts FibreBridge à l'aide des informations d'identification si elles sont requises par le serveur pour télécharger le package du micrologiciel.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["Mise à jour du micrologiciel sur un pont FiberBridge"]
 a| 
ONTAP 9.16.1



 a| 
Prise en charge de la mobilité des données SVM pour la migration des configurations MetroCluster
 a| 
ONTAP prend en charge les migrations SVM MetroCluster suivantes :

* Migration d'un SVM entre une paire haute disponibilité non MetroCluster et une configuration MetroCluster IP
* Migration d'un SVM entre deux configurations MetroCluster IP
* Migration d'un SVM entre une configuration FC MetroCluster et une configuration IP MetroCluster


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["Mobilité des données des SVM"^]
 a| 
ONTAP 9.16.1



 a| 
Prise en charge de l'authentification MD5 pour les groupes de pairs BGP
 a| 
ONTAP prend en charge l'authentification MD5 sur les groupes de pairs BGP pour protéger les sessions BGP. Lorsque MD5 est activé, les sessions BGP ne peuvent être établies et traitées que parmi les pairs autorisés, ce qui empêche les interruptions potentielles de la session par un acteur non autorisé.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Configuration des LIF IP virtuelles (VIP"^]
 a| 
ONTAP 9.16.1



 a| 
Prise en charge de MetroCluster IP pour un chiffrement de bout en bout
 a| 
Le chiffrement de bout en bout est pris en charge sur les systèmes AFF A400, AFF C400, FAS8300 et FAS8700 pour chiffrer le trafic back-end, tel que les données NVlog et de réplication de stockage, entre les sites dans une configuration IP MetroCluster .

link:../maintain/task-configure-encryption.html["Configurer le chiffrement de bout en bout dans une configuration MetroCluster IP"]
 a| 
ONTAP 9.15.1



 a| 
Augmentation de la limite du volume pour les configurations MetroCluster IP à quatre nœuds sur les systèmes AFF A800 et AFF C800
 a| 
Dans les configurations MetroCluster IP à quatre nœuds, les limites de volume suivantes pour les systèmes AFF A800 et AFF C800 ont été augmentées :

* Le nombre maximal de volumes FlexVol par agrégat est passé de 200 à 625.
* Le nombre maximal de volumes FlexVol par nœud est passé de 800 à 1250.
* Le nombre maximal de volumes FlexVol par paire HA est passé de 1 600 à 2 500.

 a| 
ONTAP 9.15.1



 a| 
Prise en charge de MetroCluster IP pour NVMe
 a| 
Le protocole hôte frontal NVMe/TCP est pris en charge dans les configurations IP MetroCluster à quatre nœuds.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurations SAN dans un environnement MetroCluster"^]
 a| 
ONTAP 9.15.1



 a| 
Augmentation de la limite du volume pour les configurations IP MetroCluster à quatre nœuds sur les systèmes AFF A900
 a| 
Dans les configurations MetroCluster IP à quatre nœuds, les limites de volume suivantes pour les systèmes AFF A900 ont augmenté :

* Le nombre maximal de volumes FlexVol par agrégat est passé de 200 à 625.
* Le nombre maximal de volumes FlexVol par nœud est passé de 800 à 1250.
* Le nombre maximal de volumes FlexVol par paire HA est passé de 1 600 à 2 500.

 a| 
ONTAP 9.14.1



 a| 
Prise en charge du stockage objet S3 sur les agrégats en miroir et sans miroir
 a| 
Vous pouvez activer un serveur de stockage objet S3 sur une SVM dans un agrégat en miroir ou sans miroir dans des configurations MetroCluster IP et FC.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Prise en charge de S3 avec MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Prise en charge du provisionnement d'un compartiment S3 sur des agrégats en miroir et sans miroir dans un cluster MetroCluster
 a| 
Dans les configurations MetroCluster, vous pouvez créer un compartiment sur un agrégat en miroir ou sans miroir.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["Créez un compartiment ONTAP S3 sur un agrégat en miroir ou sans miroir dans une configuration MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Transition de MetroCluster FC vers MetroCluster IP à l'aide d'un commutateur partagé pour le stockage MetroCluster IP et le stockage connecté Ethernet
 a| 
Vous pouvez passer d'une configuration FC MetroCluster à une configuration IP MetroCluster sans interruption grâce à un commutateur de stockage partagé.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Transition sans interruption d'une configuration MetroCluster FC vers une configuration MetroCluster IP (ONTAP 9.8 et versions ultérieures)"]
 a| 
ONTAP 9.13.1



 a| 
Transitions sans interruption entre une configuration FC MetroCluster à huit nœuds et une configuration IP MetroCluster
 a| 
Vous pouvez migrer vos charges de travail et vos données sans interruption à partir d'une configuration MetroCluster FC à huit nœuds vers une nouvelle configuration MetroCluster IP.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Passez d'une configuration FC MetroCluster à une configuration IP MetroCluster sans interruption"]
 a| 
ONTAP 9.13.1



 a| 
Mise à niveau de la configuration IP MetroCluster à quatre nœuds via le basculement et le rétablissement
 a| 
Vous pouvez mettre à niveau les contrôleurs d'une configuration IP MetroCluster à quatre nœuds en utilisant le basculement et le rétablissement avec `system controller replace` commandes.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["Mise à niveau des contrôleurs dans une configuration IP MetroCluster à quatre nœuds"]
 a| 
ONTAP 9.13.1



 a| 
Le basculement automatique non planifié (MAUSO) assisté par un médiateur est déclenché en cas d'arrêt de l'environnement
 a| 
Si un site s'arrête normalement en raison d'un arrêt environnemental, MAUSO est déclenché.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Prise en charge du protocole ONTAP pour le basculement automatique non planifié"]
 a| 
ONTAP 9.13.1



 a| 
Prise en charge des configurations IP MetroCluster à 8 nœuds
 a| 
Vous pouvez mettre à niveau les contrôleurs et le stockage dans une configuration IP MetroCluster à huit nœuds en développant la configuration pour devenir une configuration temporaire à douze nœuds, puis en supprimant les anciens groupes DR.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["Actualisez une configuration IP MetroCluster à quatre nœuds"]
 a| 
ONTAP 9.13.1



 a| 
Conversion de la configuration IP de MetroCluster en une configuration de commutateur MetroCluster de stockage partagé
 a| 
Vous pouvez convertir une configuration IP MetroCluster en une configuration de commutateur MetroCluster de stockage partagé.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["Remplacez un commutateur IP"]
 a| 
ONTAP 9.13.1



 a| 
Fonction de basculement forcé automatique MetroCluster dans une configuration MetroCluster IP
 a| 
Vous pouvez activer la fonction de basculement automatique forcé MetroCluster dans une configuration MetroCluster IP. Cette fonction est une extension de la fonction de basculement non planifié assisté par un médiateur (MAUSO).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["Limitations du basculement automatique"]
 a| 
ONTAP 9.12.1



 a| 
S3 sur un SVM sur un agrégat sans miroir en configuration MetroCluster IP
 a| 
Vous pouvez activer un serveur de stockage objet ONTAP simple Storage Service (S3) sur un SVM sur un agrégat sans miroir dans une configuration MetroCluster IP.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Prise en charge de S3 avec MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Prise en charge de MetroCluster IP pour NVMe
 a| 
Le protocole NVMe/FC est pris en charge dans les configurations IP MetroCluster à quatre nœuds.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurations SAN dans un environnement MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Prise en charge IPsec du protocole hôte frontal dans les configurations MetroCluster IP et MetroCluster FAS
 a| 
La prise en charge IPSec pour le protocole hôte frontal (tel que NFS et iSCSI) est disponible dans les configurations FAS MetroCluster IP et MetroCluster.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurez la sécurité IP (IPsec) sur le cryptage filaire"^]
 a| 
ONTAP 9.12.1



 a| 
Passage d'une configuration FC MetroCluster à une configuration IP AFF A250 ou FAS500f MetroCluster
 a| 
Vous pouvez passer d'une configuration FC MetroCluster à une configuration IP MetroCluster AFF A250 ou FAS500f.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["Déplacez les connexions locales du cluster"]
 a| 
ONTAP 9.11.1



 a| 
Groupes de cohérence
 a| 
Les groupes de cohérence sont pris en charge dans les configurations MetroCluster.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["Groupes de cohérence dans les configurations MetroCluster"^]
 a| 
ONTAP 9.11.1



 a| 
Mise à niveau simplifiée des nœuds du contrôleur dans une configuration MetroCluster FC
 a| 
La procédure de mise à niveau du processus de mise à niveau via le basculement et le rétablissement a été simplifiée.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Mettez à niveau les contrôleurs d'une configuration MetroCluster FC en utilisant le basculement et le rétablissement"]
 a| 
ONTAP 9.10.1



 a| 
Prise en charge IP de la liaison partagée au niveau de la couche 3
 a| 
Les configurations IP de MetroCluster peuvent être implémentées grâce à des connexions internes routées par IP (couche 3).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["Considérations relatives aux réseaux étendus de couche 3"]
 a| 
ONTAP 9.9.1



 a| 
Prise en charge des configurations MetroCluster à 8 nœuds
 a| 
Les clusters permanents à huit nœuds sont pris en charge dans les configurations IP et MetroCluster FAS.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Installez et câchez les composants MetroCluster"]
 a| 
ONTAP 9.9.1

|===