---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= Nouveautés de la prise en charge de la configuration MetroCluster pour les fonctionnalités ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[cols="20,65,15"]
|===
| Fonctionnalités prises en charge en configuration MetroCluster | Description | Disponible au début 


 a| 
Prise en charge du stockage objet S3 sur les agrégats en miroir et sans miroir
 a| 
Vous pouvez activer un serveur de stockage objet S3 sur une SVM dans un agrégat en miroir ou sans miroir dans des configurations MetroCluster IP et FC.

https://docs.netapp.com/us-en/ontap/s3-config/index.html["Présentation de la configuration S3"]
 a| 
ONTAP 9.14.1



 a| 
Prise en charge du provisionnement d'un compartiment S3 sur des agrégats en miroir et sans miroir dans un cluster MetroCluster
 a| 
Dans les configurations MetroCluster, vous pouvez créer un compartiment sur un agrégat en miroir ou sans miroir.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["Créez un compartiment sur un agrégat en miroir ou sans miroir dans une configuration MetroCluster"]
 a| 
ONTAP 9.14.1



 a| 
ONTAP Mediator 1.5 est pris en charge dans une configuration MetroCluster IP
 a| 
Le Mediator 1.5 de ONTAP est disponible pour la surveillance des configurations IP de MetroCluster.

https://docs.netapp.com/us-en/ontap/mediator/index.html["Installez ou mettez à niveau le service ONTAP Mediator"]
 a| 
ONTAP 9.12.1



 a| 
Prise en charge IPsec du protocole hôte frontal dans les configurations MetroCluster IP et MetroCluster FAS
 a| 
La prise en charge IPSec pour le protocole hôte frontal (tel que NFS et iSCSI) est disponible dans les configurations FAS MetroCluster IP et MetroCluster.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurez la sécurité IP (IPsec) sur le cryptage filaire"]
 a| 
ONTAP 9.12.1



 a| 
Médiateur ONTAP 1.4
 a| 
La version 1.4 du logiciel Mediator de ONTAP est prise en charge dans les configurations IP de MetroCluster.

https://docs.netapp.com/us-en/ontap/mediator/index.html["Installez ou mettez à niveau le service ONTAP Mediator"]
 a| 
ONTAP 9.11.1



 a| 
Groupes de cohérence
 a| 
Les groupes de cohérence sont pris en charge dans les configurations MetroCluster.

https://docs.netapp.com/us-en/ontap/mediator/index.html["Installez ou mettez à niveau le service ONTAP Mediator"]
 a| 
ONTAP 9.11.1



 a| 
Le Mediator ONTAP est pris en charge dans les configurations MetroCluster IP
 a| 
Le service ONTAP Mediator peut aider la configuration IP de MetroCluster à effectuer un basculement automatique non planifié en fournissant un référentiel physiquement distinct pour les informations d'état.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Configuration du service médiateur ONTAP pour un basculement automatique non planifié"]
 a| 
ONTAP 9.7



 a| 
FabricPool est mis en miroir dans les configurations MetroCluster
 a| 
Vous pouvez configurer une FabricPool en miroir sur les configurations MetroCluster pour déplacer les données inactives vers deux zones de défaillance différentes.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["Configuration des magasins d'objets pour FabricPool dans une configuration MetroCluster"]
 a| 
ONTAP 9.7



 a| 
Reprise d'activité de SVM
 a| 
Les machines virtuelles de stockage actives (SVM) dans une configuration MetroCluster peuvent être utilisées comme sources grâce à la fonctionnalité de reprise d'activité SVM de SnapMirror.
 a| 
ONTAP 9.5

|===