---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= Nouveautés de la prise en charge de la configuration MetroCluster pour les fonctionnalités ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque version du logiciel de gestion des données ONTAP 9 inclut de nouvelles fonctionnalités améliorées qui améliorent les fonctionnalités, la gestion et les performances des configurations ONTAP MetroCluster.

Pour plus d'informations sur les problèmes connus, les limites et les mises en garde de mise à niveau affectant les configurations ONTAP MetroCluster, reportez-vous au https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP 9"^]. Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

[cols="20,65,15"]
|===
| Fonctionnalités prises en charge en configuration MetroCluster | Description | Disponible au début 


 a| 
Prise en charge de MetroCluster IP pour NVMe
 a| 
Le protocole hôte frontal NVMe/TCP est pris en charge dans les configurations IP MetroCluster à quatre nœuds.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurations SAN dans un environnement MetroCluster"^]
 a| 
ONTAP 9.15.1



 a| 
Prise en charge du stockage objet S3 sur les agrégats en miroir et sans miroir
 a| 
Vous pouvez activer un serveur de stockage objet S3 sur une SVM dans un agrégat en miroir ou sans miroir dans des configurations MetroCluster IP et FC.

https://docs.netapp.com/us-en/ontap/s3-config/index.html["Présentation de la configuration S3"]
 a| 
ONTAP 9.14.1



 a| 
Prise en charge du provisionnement d'un compartiment S3 sur des agrégats en miroir et sans miroir dans un cluster MetroCluster
 a| 
Dans les configurations MetroCluster, vous pouvez créer un compartiment sur un agrégat en miroir ou sans miroir.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["Créez un compartiment sur un agrégat en miroir ou sans miroir dans une configuration MetroCluster"]
 a| 
ONTAP 9.12.1



 a| 
Prise en charge de MetroCluster IP pour NVMe
 a| 
Le protocole NVMe/FC est pris en charge dans les configurations IP MetroCluster à quatre nœuds.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurations SAN dans un environnement MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Prise en charge IPsec du protocole hôte frontal dans les configurations MetroCluster IP et MetroCluster FAS
 a| 
La prise en charge IPSec pour le protocole hôte frontal (tel que NFS et iSCSI) est disponible dans les configurations FAS MetroCluster IP et MetroCluster.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurez la sécurité IP (IPsec) sur le cryptage filaire"]
 a| 
ONTAP 9.11.1



 a| 
Groupes de cohérence
 a| 
Les groupes de cohérence sont pris en charge dans les configurations MetroCluster.
 a| 
ONTAP 9.7



 a| 
FabricPool est mis en miroir dans les configurations MetroCluster
 a| 
Vous pouvez configurer une FabricPool en miroir sur les configurations MetroCluster pour déplacer les données inactives vers deux zones de défaillance différentes.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["Configuration des magasins d'objets pour FabricPool dans une configuration MetroCluster"]
 a| 
ONTAP 9.7



 a| 
Reprise d'activité de SVM
 a| 
Les machines virtuelles de stockage actives (SVM) dans une configuration MetroCluster peuvent être utilisées comme sources grâce à la fonctionnalité de reprise d'activité SVM de SnapMirror.
 a| 
ONTAP 9.5

|===