---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: Sélectionnez la procédure correcte lorsque vous effectuez des tâches de maintenance matérielle MetroCluster. 
---
= En savoir plus sur la maintenance MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment vous préparer aux tâches de maintenance MetroCluster et choisir la procédure de maintenance adaptée à votre configuration.



== Préparer les tâches de maintenance

Consultez les informations de la section link:enable-console-logging-before-maintenance.html["Préparer la maintenance MetroCluster"] avant d'effectuer toute procédure de maintenance.


NOTE: Vous devez activer la journalisation de la console et supprimer la surveillance ONTAP Mediator ou Tiebreaker avant d'effectuer les tâches de maintenance.



== Procédures de maintenance pour différents types de configurations MetroCluster

* Si vous avez une configuration IP MetroCluster, passez en revue les procédures de la section link:task-modify-ip-netmask-properties.html["Procédures de maintenance pour les configurations MetroCluster IP"].
* Si vous avez une configuration MetroCluster FC, passez en revue les procédures de la section link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["Procédures de maintenance pour les configurations MetroCluster FC"].
* Si vous ne trouvez pas la procédure dans la section spécifique à votre configuration, passez en revue les procédures de la section link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["Procédures de maintenance pour toutes les configurations MetroCluster"].




== Toutes les autres procédures de maintenance

Le tableau suivant fournit des liens vers les procédures relatives à la maintenance MetroCluster qui ne se trouvent pas dans les trois sections énumérées ci-dessus :

|===


| Composant | Type de MetroCluster (FC ou IP) | Tâche | Procédure 


 a| 
Logiciel ONTAP
 a| 
Les deux
 a| 
Mise à niveau du logiciel ONTAP
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["Mise à niveau, rétablissement ou mise à niveau vers une version antérieure"^]



 a| 
Module de contrôleur
 a| 
Les deux
 a| 
Remplacement des FRU (modules de contrôleur, cartes PCIe, carte FC-VI, etc.)


NOTE: Le déplacement d'un module de contrôleur de stockage ou d'une carte NVRAM entre les systèmes de stockage MetroCluster n'est pas pris en charge.
 a| 
https://docs.netapp.com/platstor/index.jsp["Documentation des systèmes matériels ONTAP"^]



 a| 
Mise à niveau et extension
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Mise à niveau et extension de MetroCluster"]



 a| 
Transition de la connectivité FC à la connectivité IP
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["Transition de MetroCluster FC à MetroCluster IP"]



 a| 
Tiroir disque
 a| 
FC
 a| 
Toutes les autres procédures de maintenance des tiroirs. Les procédures standard peuvent être utilisées.
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Maintenance des tiroirs disques DS460C DS224C et DS212C"^]



 a| 
IP
 a| 
Toutes les procédures de maintenance des tiroirs. Les procédures standard peuvent être utilisées.

Si vous ajoutez des tiroirs pour un agrégat non mis en miroir, reportez-vous à la section http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["Considérations relatives à l'utilisation d'agrégats non mis en miroir"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Maintenance des tiroirs disques DS460C DS224C et DS212C"^]



 a| 
Les deux
 a| 
Ajout à chaud de tiroirs IOM12 à une pile de tiroirs IOM6
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Ajout de tiroirs à chaud avec modules IOM12 à une pile de tiroirs avec modules IOM6"^]

|===