---
permalink: maintain/enable-console-logging-before-maintenance.html 
sidebar: sidebar 
keywords: metrocluster, maintain, enable, autosupport, logging, maintenance, service,ip, switch, replacement, rename 
summary: 'Activez la journalisation de la console sur vos périphériques avant d"effectuer des tâches de maintenance.' 
---
= Activez la journalisation de la console avant d'effectuer les tâches de maintenance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Activez la journalisation de la console sur vos périphériques avant d'effectuer des tâches de maintenance.

NetApp vous recommande vivement d'activer la journalisation de la console sur les périphériques que vous utilisez et d'effectuer les actions suivantes avant d'effectuer les procédures de maintenance :

* Laissez AutoSupport activé pendant la maintenance.
* Déclencher un message AutoSupport de maintenance avant et après la maintenance pour désactiver la création de dossiers pendant la durée de l'activité de maintenance.
+
Consultez l'article de la base de connaissances link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Comment supprimer la création automatique de dossier pendant les fenêtres de maintenance planifiées"^].

* Activer la journalisation de session pour toute session CLI. Pour obtenir des instructions sur l'activation de la journalisation des sessions, consultez la section « consignation des sorties de session » de l'article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Comment configurer PuTTY pour une connectivité optimale aux systèmes ONTAP"^].

