---
permalink: maintain/reference_where_to_find_additional_information_mcc_service_guide.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, additional, information 
summary: 'Pour en savoir plus sur la configuration, l"exploitation et le contrôle d"une configuration MetroCluster, consultez la documentation complète de NetApp.' 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous trouverez plus d'informations sur la configuration, l'exploitation et le contrôle d'une configuration MetroCluster dans la documentation complète de NetApp.

|===


| Informations | Objet 


 a| 
link:../index.html["Documentation MetroCluster"]
 a| 
* Toutes les informations relatives aux MetroCluster




 a| 
https://["Architecture et conception de la solution NetApp MetroCluster"^]
 a| 
* Présentation technique de la configuration et du fonctionnement de MetroCluster.
* Bonnes pratiques de configuration MetroCluster.




 a| 
https://["Installation et configuration de la solution Fabric-Attached MetroCluster"]
 a| 
* Architecture Fabric-Attached MetroCluster
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration des commutateurs FC
* Configuration de MetroCluster dans ONTAP




 a| 
https://["Installation et configuration d'Stretch MetroCluster"]
 a| 
* Architecture MetroCluster extensible
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration de MetroCluster dans ONTAP




 a| 
https://["Installation et configuration de MetroCluster IP"]
 a| 
* Architecture de MetroCluster IP
* Câblage de la configuration IP de MetroCluster
* Configuration de MetroCluster dans ONTAP




 a| 
https://["Documentation NetApp : guides et ressources produits"^]
 a| 
* Contrôle de la configuration et des performances d'MetroCluster




 a| 
https://["Installation et configuration du logiciel MetroCluster Tiebreaker"]
 a| 
* Contrôle de la configuration de MetroCluster avec le logiciel MetroCluster Tiebreaker




 a| 
https://["Transition basée sur la copie"]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster


|===