---
permalink: maintain/reference_fb_replace_a_power_supply.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, replacing, failed, power, supply, module 
summary: 'En cas de changement d"état d"un module d"alimentation sur le pont, vous pouvez retirer et installer le module d"alimentation.' 
---
= Remplacement à chaud d'un module d'alimentation défectueux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cas de changement d'état d'un module d'alimentation sur le pont, vous pouvez retirer et installer le module d'alimentation.

Vous pouvez visualiser le changement d'état d'un module d'alimentation par le biais des voyants du pont. Vous pouvez également afficher l'état des modules d'alimentation via l'interface graphique ExpressNAV et l'interface de ligne de commande du pont, via le port série ou via Telnet.

* Cette procédure est SANS interruption (non disruptive) et prend environ 15 minutes.
* Vous avez besoin du mot de passe d'administration et de l'accès à un serveur FTP ou SCP.



NOTE: Le Manuel d'installation et d'utilisation _ATTO FibreBridge_ pour votre pont modèle contient plus d'informations sur les interfaces de gestion.

Pour accéder à ce document et à d'autres contenus sur le site Web ATTO, utilisez le lien fourni sur la page ATTO Fibrebridge Description.
