---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: Mise à niveau du micrologiciel sur les commutateurs IP MetroCluster. 
---
= Mise à niveau du micrologiciel des commutateurs IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être mettre à niveau le micrologiciel d'un commutateur IP MetroCluster.



== Vérifiez que la FCR est prise en charge

Lorsque vous modifiez la version de ONTAP ou de firmware du commutateur, vérifiez que vous disposez d'un fichier RCF pris en charge pour cette version. Si vous utilisez link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"^]l'outil, le fichier RCF correct est généré pour votre configuration.

.Étapes
. Utilisez les commandes suivantes des switchs pour vérifier la version du fichier RCF :
+
[cols="30,70"]
|===


| À partir de ce commutateur... | Exécutez cette commande... 


 a| 
Commutateur Broadcom
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Commutateur Cisco
 a| 
`IP_switch_A_1# show banner motd`



 a| 
Commutateur NVIDIA SN2100
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
Recherchez la ligne dans la sortie de la commande qui indique la version RCF. Par exemple, la sortie suivante d'un commutateur Cisco indique que la version RCF est « v1.80 ».

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. Pour vérifier quels fichiers sont pris en charge pour une version, un commutateur et une plate-forme ONTAP spécifiques, utilisez le link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator pour MetroCluster IP"^]. Si vous pouvez générer le fichier RCF correspondant à la configuration dont vous disposez ou que vous souhaitez mettre à niveau, il est pris en charge.
. Pour vérifier que le micrologiciel du commutateur est pris en charge, reportez-vous aux sections suivantes :
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^]






== Mettez à niveau le micrologiciel du commutateur

.Description de la tâche
Vous devez répéter cette tâche sur chacun des commutateurs successivement.

link:enable-console-logging-before-maintenance.html["Activer la journalisation de la console"] avant d'effectuer cette tâche.

[[step_1_fw_upgrade]]
.Étapes
. Vérifier l'état de santé de la configuration.
+
.. Vérifier que la MetroCluster est configurée et en mode normal sur chaque cluster :
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vérifier que la mise en miroir est activée sur chaque nœud :
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Vérifier que les composants MetroCluster sont sains :
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
L'opération s'exécute en arrière-plan.

.. Après le `metrocluster check run` l'opération se termine, exécutez :
+
`metrocluster check show`

+
Après environ cinq minutes, les résultats suivants s'affichent :

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Vérifier qu'il n'y a pas d'alerte de santé :
+
`system health alert show`



. Installer le logiciel sur le premier commutateur.
+

NOTE: Vous devez installer le logiciel du commutateur sur les commutateurs dans l'ordre suivant : switch_A_1, switch_B_1, switch_A_2, switch_B_2.

+
Suivez les étapes d'installation du logiciel du commutateur dans la rubrique correspondante selon que le type de commutateur est Broadcom, Cisco ou NVIDIA :

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Téléchargez et installez le logiciel EFOS du commutateur Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Téléchargez et installez le logiciel Cisco switch NX-OS"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Téléchargez et installez le logiciel Cumulus du commutateur NVIDIA SN2100"]


. Répéter l'étape précédente pour chacun des commutateurs.
. Recommencez <<step_1_fw_upgrade,Étape 1>> pour vérifier l'état de santé de la configuration.

