---
permalink: maintain/task-modify-ip-netmask-properties.html 
sidebar: sidebar 
keywords: vlan, ip, gateway,netmask, address, network, interface, subnet 
summary: 'Vous pouvez modifier les propriétés suivantes d"une interface IP MetroCluster, d"une adresse IP, d"un masque et d"une passerelle. Vous pouvez utiliser n"importe quelle combinaison de paramètres pour la mise à jour.' 
---
= Modifiez les propriétés d'une interface IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.10.1, vous pouvez modifier les propriétés suivantes d'une interface IP MetroCluster : adresse IP et masque, et passerelle. Vous pouvez utiliser n'importe quelle combinaison de paramètres pour la mise à jour.

Vous devrez peut-être mettre à jour ces propriétés, par exemple si une adresse IP dupliquée est détectée ou si une passerelle doit changer dans le cas d'un réseau de couche 3 en raison de modifications de configuration du routeur.

.Description de la tâche
* Vous ne pouvez modifier qu'une interface à la fois. Cette interface entraînera une perturbation du trafic jusqu'à ce que les autres interfaces soient mises à jour et que les connexions soient reétablies.
* Utilisez le `metrocluster configuration-settings interface modify` Commande permettant de modifier toute propriété d'interface IP MetroCluster.
+

NOTE: Ces commandes permettent de modifier la configuration d'un nœud spécifique pour un port particulier. Pour restaurer la connectivité réseau complète, des commandes similaires sont nécessaires sur d'autres ports. De même, les commutateurs réseau doivent également mettre à jour leur configuration. Par exemple, si la passerelle est mise à jour, elle est idéalement modifiée sur les deux nœuds d'une paire haute disponibilité, car ils sont identiques. De plus, le switch connecté à ces nœuds doit également mettre à jour sa passerelle.

* Utilisez les `metrocluster configuration-settings interface show`commandes , `metrocluster connection check`et `metrocluster connection show` pour vérifier que toutes les connexions fonctionnent dans toutes les interfaces.




== Modifiez l'adresse IP, le masque de réseau et la passerelle

Procédez comme suit pour modifier l'adresse IP, le masque de réseau et la passerelle d'une interface IP MetroCluster.

.Étapes
. Mettez à jour l'adresse IP, le masque de réseau et la passerelle pour un seul nœud et une seule interface :
`metrocluster configuration-settings interface modify`
+
La commande suivante indique comment mettre à jour l'adresse IP, le masque de réseau et la passerelle :

+
[listing]
----
cluster_A::* metrocluster configuration-settings interface modify -cluster-name cluster_A -home-node node_A_1 -home-port e0a-10 -address 192.168.12.101 -gateway 192.168.12.1 -netmask 255.255.254.0
(metrocluster configuration-settings interface modify)
Warning: This operation will disconnect and reconnect iSCSI and RDMA connections used for DR protection through port “e0a-10”. Partner nodes may need modifications for port “e0a-10” in order to completely establish network connectivity.
Do you want to continue?" yes
[Job 28] Setting up iSCSI target configuration. (pass2:iscsi13:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
[Job 28] Establishing iSCSI initiator connections.
(pass6:iscsi14:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
(pass8:iscsi15:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
(pass9:iscsi16:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
[Job 28] Job succeeded: Interface Modify is successful.
cluster_A::*> metrocluster configuration-settings interface modify -cluster-name cluster_A -home-node node_A_2 -home-port e0a-10 -address 192.168.12.201 -gateway 192.168.12.1 -netmask 255.255.254.0
(metrocluster configuration-settings interface modify)
Warning: This operation will disconnect and reconnect iSCSI and RDMA connections used for DR protection through port “e0a-10”. Partner nodes may need modifications for port “e0a-10” in order to completely establish network connectivity.
Do you want to continue?" yes
[Job 28] Job succeeded: Interface Modify is successful
----
. [[step2]]Vérifiez que toute la connectivité fonctionne pour toutes les interfaces :
`metrocluster configuration-settings interface show`
+
La commande suivante indique comment vérifier que toute la connectivité fonctionne pour toutes les interfaces :

+
[listing]
----
cluster_A::*> metrocluster configuration-settings interface show
(metrocluster configuration-settings interface show)                                                 DR              Config
Group Cluster Node    Network Address Netmask         Gateway         State
----- ------- ------- --------------- --------------- --------------- ---------
1     cluster_A node_A_2
                 Home Port: e0a-10
                      192.168.12.201  255.255.254.0   192.168.12.1    completed
                 Home Port: e0b-20
                      192.168.20.200  255.255.255.0   192.168.20.1    completed
                node_A_1
                 Home Port: e0a-10
                      192.168.12.101  255.255.254.0   192.168.12.1    completed
                 Home Port: e0b-20
                      192.168.20.101  255.255.255.0   192.168.20.1    completed
      cluster_B node_B_1
                 Home Port: e0a-10
                      192.168.11.151  255.255.255.0   192.168.11.1    completed
                 Home Port: e0b-20
                      192.168.21.150  255.255.255.0   192.168.21.1    completed
                node_B_2
                 Home Port: e0a-10
                      192.168.11.250  255.255.255.0   192.168.11.1    completed
                 Home Port: e0b-20
                      192.168.21.250  255.255.255.0   192.168.21.1    completed
8 entries were displayed.
----


. [[étape3]]Vérifiez que toutes les connexions fonctionnent :
+
`metrocluster configuration-settings connection show`

+
La commande suivante indique comment vérifier que toutes les connexions fonctionnent :

+
[listing]
----
cluster_A::*> metrocluster configuration-settings connection show
  (metrocluster configuration-settings connection show)
DR                    Source          Destination
Group Cluster Node    Network Address Network Address Partner Type Config State
----- ------- ------- --------------- --------------- ------------ ------------
1     cluster_A node_A_2
                 Home Port: e0a-10
                      192.168.10.200  192.168.10.101  HA Partner   completed
                 Home Port: e0a-10
                      192.168.10.200  192.168.11.250  DR Partner   completed
                 Home Port: e0a-10
                      192.168.10.200  192.168.11.151  DR Auxiliary completed
                 Home Port: e0b-20
                      192.168.20.200  192.168.20.100  HA Partner   completed
                 Home Port: e0b-20
                      192.168.20.200  192.168.21.250  DR Partner   completed
                 Home Port: e0b-20
                      192.168.20.200  192.168.21.150  DR Auxiliary completed
                node_A_1
                 Home Port: e0a-10
                      192.168.10.101  192.168.10.200  HA Partner   completed
                 Home Port: e0a-10
                      192.168.10.101  192.168.11.151  DR Partner   completed
                 Home Port: e0a-10
                      192.168.10.101  192.168.11.250  DR Auxiliary completed
                 Home Port: e0b-20
                      192.168.20.100  192.168.20.200  HA Partner   completed
                 Home Port: e0b-20
                      192.168.20.100  192.168.21.150  DR Partner   completed
                 Home Port: e0b-20
                      192.168.20.100  192.168.21.250  DR Auxiliary completed
----

