---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: Il peut être nécessaire de mettre à niveau un fichier RCF sur un commutateur IP MetroCluster. Par exemple, une mise à niveau de ONTAP ou une mise à niveau du firmware du switch nécessite tous deux un nouveau fichier RCF. 
---
= Mettre à niveau les fichiers RCF sur les commutateurs IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être mettre à niveau un fichier RCF (Reference Configuration File) sur un commutateur IP MetroCluster. Par exemple, si la version du fichier RCF exécutée sur les switchs n'est pas prise en charge par la version ONTAP, la version du firmware du switch ou les deux.

.Avant de commencer
* Si vous installez un nouveau firmware du commutateur, vous devez installer le micrologiciel du commutateur avant de mettre à niveau le fichier RCF.
* Avant de mettre à niveau le fichier RCFlink:task_upgrade_firmware_on_mcc_ip_switches.html["Vérifiez que la FCR est prise en charge"], .
* link:enable-console-logging-before-maintenance.html["Activer la journalisation de la console"] avant d'effectuer cette tâche.


.Description de la tâche
* Cette procédure perturbe le trafic sur le commutateur où le fichier RCF est mis à niveau. Le trafic reprend lorsque le nouveau fichier RCF est appliqué.
* Effectuer les étapes sur un commutateur à la fois, dans l'ordre suivant : Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.


.Étapes
. Vérification de l'état de santé de la configuration.
+
.. Vérifiez que les composants MetroCluster sont sains :
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
L'opération s'exécute en arrière-plan.

+
.. Après le `metrocluster check run` opération terminée, exécution `metrocluster check show` pour afficher les résultats.
+
Après environ cinq minutes, les résultats suivants s'affichent :

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Vérifier l'état de l'opération de vérification MetroCluster en cours :
+
`metrocluster operation history show -job-id 38`

.. Vérifiez qu'il n'y a pas d'alerte de santé :
+
`system health alert show`



. Préparez les commutateurs IP pour l'application des nouveaux fichiers RCF.
+
Suivez les étapes pour votre fournisseur de commutateur :

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Réinitialisez les paramètres par défaut du commutateur IP Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Réinitialisez le commutateur IP Cisco sur les paramètres d'usine par défaut"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Réinitialisez les paramètres par défaut du commutateur NVIDIA IP SN2100"]


. Téléchargez et installez le fichier RCF IP, selon votre fournisseur de commutateur.
+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Téléchargez et installez les fichiers RCF IP Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Téléchargez et installez les fichiers RCF IP Cisco"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Téléchargez et installez les fichiers RCF IP de NVIDIA"]
+

NOTE: Si vous disposez d'une configuration réseau L2 partagée ou L3, il se peut que vous deviez ajuster les ports ISL sur les commutateurs intermédiaire/client. Le mode de port de commutateur peut passer du mode « accès » au mode « réseau ». Ne procédez à la mise à niveau de la deuxième paire de commutateurs (A_2, B_2) que si la connectivité réseau entre les commutateurs A_1 et B_1 est pleinement opérationnelle et que le réseau fonctionne correctement.




