---
permalink: maintain/task_hot_add_a_stack_to_exist_7500n_pair.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, existing, pair, fibrebridge, bridge 
summary: Vous pouvez ajouter à chaud une pile de tiroirs disques SAS à une paire existante de ponts FiberBridge 7500N qui disposent de ports disponibles. 
---
= Ajout à chaud d'une pile de tiroirs disques SAS à une paire existante de ponts FiberBridge 7500N
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter à chaud une pile de tiroirs disques SAS à une paire existante de ponts FiberBridge 7500N qui disposent de ports disponibles.

.Avant de commencer
* Vous devez avoir téléchargé le dernier firmware de disque et de tiroir disque.
* Tous les tiroirs disques de la configuration MetroCluster (tiroirs existants) doivent exécuter la même version de firmware. Si un ou plusieurs des disques ou tiroirs n'utilisent pas la dernière version du micrologiciel, mettez à jour le micrologiciel avant de connecter les nouveaux disques ou tiroirs.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Téléchargements NetApp : firmware de disque"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Téléchargements NetApp : firmware des tiroirs disques"^]

* Les ponts FiberBridge 7500N doivent être connectés et disposent de ports SAS disponibles.


.Description de la tâche
Cette procédure est rédigée avec l'hypothèse que vous utilisez les interfaces de gestion des ponts recommandées : l'interface graphique ATTO ExpressNAV et l'utilitaire ATTO Quickmenu.

Vous pouvez utiliser l'interface graphique ATTO ExpressNAV pour configurer et gérer un pont et mettre à jour le micrologiciel du pont. Vous pouvez utiliser l'utilitaire ATTO Quicknavigation pour configurer le port de gestion Ethernet de pont 1.

Vous pouvez utiliser d'autres interfaces de gestion, si nécessaire. Ces options incluent l'utilisation d'un port série ou Telnet pour configurer et gérer un pont, pour configurer le port Ethernet management 1 et l'utilisation de FTP pour mettre à jour le micrologiciel du pont. Si vous choisissez l'une de ces interfaces de gestion, vous devez satisfaire aux exigences applicables dans link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html["Autres interfaces de gestion des ponts"].


IMPORTANT: Si vous insérez un câble SAS dans le mauvais port, lorsque vous retirez le câble d'un port SAS, vous devez attendre au moins 120 secondes avant de brancher le câble sur un autre port SAS. Si vous ne le faites pas, le système ne reconnaîtra pas que le câble a été déplacé vers un autre port.

.Étapes
. Mettez-vous à la terre.
. Depuis la console d'un autre contrôleur, vérifiez que l'autoassignation des disques est activée sur votre système :
+
`storage disk option show`

+
La colonne affectation automatique indique si l'affectation automatique des disques est activée.

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. Désactivez les ports de commutateur de la nouvelle pile.
. Mettez à jour le micrologiciel FiberBridge sur chaque pont.
+
Si le nouveau pont est du même type que celui de la mise à niveau de pont partenaire vers le même micrologiciel que le pont partenaire. Si le nouveau pont est de type différent du pont partenaire, effectuez une mise à niveau vers le dernier micrologiciel pris en charge par le pont et la version de ONTAP. Voir la section « mise à jour du micrologiciel sur un pont FibreBridge » dans le _MetroCluster Maintenance Guide_.

. Sur chaque pont de la paire, activez le port SAS qui se connectera à la nouvelle pile :
+
`SASPortEnable _port-letter_`

+
Le même port SAS (B, C ou D) doit être utilisé sur les deux ponts.

. Enregistrez la configuration et redémarrez chaque pont :
+
`SaveConfiguration Restart`

. Reliez les tiroirs disques aux ponts :
+
.. Connectez en série les tiroirs disques de chaque pile.
+
Le _Guide d'installation et de maintenance_ de votre modèle de tiroir disque fournit des informations détaillées sur la configuration en série des tiroirs disques.

.. Pour chaque pile de tiroirs disques, reliez le module d'E/S par seconde Au port SAS A du FibreBridge A, puis reliez le module d'E/S par seconde au port SAS A du FibreBridge B
+
link:../install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]

+
link:../install-stretch/concept_considerations_differences.html["Installation et configuration d'Stretch MetroCluster"]

+
Chaque pont dispose d'un chemin vers sa pile de tiroirs disques, le pont A se connecte au côté A de la pile via le premier tiroir et le pont B se connecte au côté B de la pile via le dernier tiroir.

+

NOTE: Le port SAS B du pont est désactivé.



. Vérifiez que chaque pont peut détecter tous les disques durs et les tiroirs disques auxquels le pont est connecté.
+
[cols="30,70"]
|===


| Si vous utilisez... | Alors... 


 a| 
Interface graphique ATTO ExpressNAV
 a| 
.. Dans un navigateur Web pris en charge, entrez l'adresse IP d'un pont dans la zone de navigation.
+
Vous accédez à la page d'accueil du ATTO FibreBridge, qui contient un lien.

.. Cliquez sur le lien, puis entrez votre nom d'utilisateur et le mot de passe que vous avez désignés lors de la configuration du pont.
+
La page d'état ATTO FibreBridge s'affiche avec un menu à gauche.

.. Cliquez sur *Avancé* dans le menu.
.. Afficher les périphériques connectés :
+
`sastargets`

.. Cliquez sur *soumettre*.




 a| 
Connexion du port série
 a| 
Afficher les périphériques connectés :

`sastargets`

|===
+
Le résultat indique les périphériques (disques et tiroirs disques) auxquels le pont est connecté. Les lignes de sortie sont numérotées de façon séquentielle afin que vous puissiez rapidement compter les périphériques.

+

NOTE: Si le texte "rééponse tronquée" apparaît au début de la sortie, vous pouvez utiliser Telnet pour vous connecter au pont, puis afficher toutes les données à l'aide de l' `sastargets` commande.

+
Le résultat suivant indique que 10 disques sont connectés :

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. Vérifiez que le résultat de la commande indique que le pont est connecté à tous les disques et tiroirs disques appropriés de la pile.
+
[cols="30,70"]
|===


| Si la sortie est... | Alors... 


 a| 
Exact
 a| 
Répéter l'étape précédente pour chaque pont restant.



 a| 
Incorrect
 a| 
.. Vérifiez que les câbles SAS sont desserrés ou corrigez le câblage SAS en répétant l'étape permettant de connecter les tiroirs disques aux ponts.
.. Répéter l'étape précédente pour chaque pont restant.


|===
. Mettez à jour le firmware du disque vers la version la plus récente à partir de la console système :
+
`disk_fw_update`

+
Vous devez exécuter cette commande sur les deux contrôleurs.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Téléchargements NetApp : firmware de disque"^]

. Mettez à jour le firmware du tiroir disque vers la version la plus récente en utilisant les instructions du firmware téléchargé.
+
Vous pouvez exécuter les commandes en cours depuis la console système d'un contrôleur.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Téléchargements NetApp : firmware des tiroirs disques"^]

. Si l'affectation automatique des disques n'est pas activée sur votre système, affectez la propriété du lecteur de disque.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestion des disques et des agrégats"^]

+

NOTE: Si vous choisissez de diviser la propriété d'une seule pile de tiroirs disques entre plusieurs contrôleurs, vous devez désactiver l'affectation automatique des disques (`storage disk option modify -autoassign off *` depuis les deux nœuds du cluster) avant d'attribuer la propriété des disques. sinon, lorsque vous attribuez un seul disque, les disques restants peuvent être automatiquement affectés au même contrôleur et au même pool.

+

NOTE: Vous ne devez pas ajouter de disques à des agrégats ou des volumes avant la mise à jour du firmware des disques et des tiroirs disques, et les étapes de vérification ne sont pas terminées.

. Activez les ports de commutateur de la nouvelle pile.
. Vérifier le fonctionnement de la configuration MetroCluster dans ONTAP :
+
.. Vérifier si le système est multipathed :
+
`node run -node _node-name_ sysconfig -a`

.. Vérifier si des alertes d'intégrité sont disponibles sur les deux clusters :
+
`system health alert show`

.. Vérifier la configuration MetroCluster et que le mode opérationnel est normal :
+
`metrocluster show`

.. Effectuer une vérification MetroCluster :
+
`metrocluster check run`

.. Afficher les résultats de la vérification MetroCluster :
+
`metrocluster check show`

.. Vérifier la présence d'alertes d'intégrité sur les commutateurs (le cas échéant) :
+
`storage switch show`

.. Exécutez Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"^]

.. Une fois Config Advisor exécuté, vérifiez les résultats de l'outil et suivez les recommandations fournies dans la sortie pour résoudre tous les problèmes détectés.


. Le cas échéant, répétez cette procédure pour le site du partenaire.

