---
permalink: maintain/task_power_off_an_entire_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, power, off, entire, metrocluster, ip, configuration 
summary: 'Vous devez mettre hors tension la totalité de la configuration IP d"MetroCluster et de tout l"équipement avant le début des opérations de maintenance ou de relocalisation.' 
---
= Mise hors tension de l'intégralité d'une configuration MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez mettre hors tension la totalité de la configuration IP d'MetroCluster et de tout l'équipement avant le début des opérations de maintenance ou de relocalisation.


NOTE: Avec ONTAP 9.8, le `*storage switch*` la commande est remplacée par `*system switch*`. Les étapes suivantes présentent le `*storage switch*` Mais si vous exécutez ONTAP 9.8 ou version ultérieure, le `*system switch*` commande recommandée.

. Vérifier la configuration MetroCluster des deux sites de la configuration MetroCluster.
+
.. Vérifier que la configuration MetroCluster et le mode opérationnel sont normaux. +
`*metrocluster show*`
.. Exécuter la commande suivante : +
`*metrocluster interconnect show*`
.. Vérifier la connectivité sur les disques en saisissant la commande suivante sur l'un des nœuds MetroCluster : +
`*run local sysconfig -v*`
.. Exécuter la commande suivante : +
`*storage port show*`
.. Exécuter la commande suivante : +
`*storage switch show*`
.. Exécuter la commande suivante : +
`*network interface show*`
.. Exécuter la commande suivante : +
`*network port show*`
.. Exécuter la commande suivante : +
`*network device-discovery show*`
.. Effectuer une vérification MetroCluster : +
`*metrocluster check run*`
.. Afficher les résultats de la vérification MetroCluster : +
`*metrocluster check show*`
.. Exécuter la commande suivante : +
`*metrocluster configuration-settings interface show*`


. Si nécessaire, désactivez AUSO en modifiant le domaine de défaillance AUSO sur
+
`*auso-disabled*`

+
[listing]
----
cluster_A_site_A::*>metrocluster modify -auto-switchover-failure-domain auso-disabled
----
+

NOTE: Dans une configuration MetroCluster IP, le domaine de défaillance AUSO est déjà défini sur 'auso-Disabled' à moins que la configuration ne soit configurée avec le médiateur ONTAP.

. Vérifiez la modification à l'aide de la commande
+
`*metrocluster operation show*`

+
[listing]
----

	cluster_A_site_A::*> metrocluster operation show
       Operation: modify
           State: successful
      Start Time: 4/25/2020 20:20:36
        End Time: 4/25/2020 20:20:36
          Errors: -
----
. Arrêter les nœuds :
+
`*halt*`

+
[listing]
----
system node halt -node node1_SiteA -inhibit-takeover true -ignore-quorum-warnings true
----
. Mettez hors tension l'équipement suivant sur le site :
+
** Contrôleurs de stockage
** Commutateurs IP MetroCluster
** Tiroirs de stockage


. Attendez trente minutes, puis mettez tous les tiroirs de stockage, les commutateurs IP MetroCluster et les contrôleurs de stockage sous tension.
. Une fois les contrôleurs mis sous tension, vérifiez la configuration MetroCluster des deux sites.
+
Pour vérifier la configuration, répétez l'étape 1.

. Effectuer des vérifications de cycle d'alimentation.
+
.. Vérifier que tous les SVM source sont en ligne : +
`*vserver show*`
.. Démarrez tous les SVM source de synchronisation qui ne sont pas en ligne : +
`*vserver start*`



