---
permalink: maintain/task_change_speed_of_isl_ports_on_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, speed, isl, ports, cisco, fc, switch 
summary: 'Vous devrez peut-être modifier la vitesse des ports ISL sur un commutateur pour améliorer la qualité de l"ISL. Les liens ISL qui se déplacent sur de plus longues distances peuvent avoir besoin d"une vitesse réduite pour améliorer la qualité.' 
---
= Modification de la vitesse des ports ISL sur un commutateur Cisco FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être modifier la vitesse des ports ISL sur un commutateur pour améliorer la qualité de l'ISL. Les liens ISL qui se déplacent sur de plus longues distances peuvent avoir besoin d'une vitesse réduite pour améliorer la qualité.

Vous devez effectuer toutes les étapes des deux commutateurs pour assurer la connectivité ISL.

. Désactivez les ports ISL des liens ISL que vous souhaitez modifier la vitesse sur les deux commutateurs dans la structure :
+
`*FC_switch_A_1# config t*`

+
Entrez les commandes de configuration, une par ligne. Terminez par CTRL-Z après avoir saisi toutes les commandes de configuration.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. Modifier la vitesse des ports ISL sur les deux commutateurs dans le fabric :
+
`*FC_switch_A_1# config t*`

+
Entrez les commandes de configuration, une par ligne. Terminez par CTRL-Z après avoir saisi toutes les commandes de configuration.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+

NOTE: Les vitesses pour les ports sont de 16 = 16,000 Gbits/s, 8 = 8,000 Gbits/s, 4 = 4,000 Gbits/s.

+
Assurez-vous que ces ports ISL pour votre commutateur sont répertoriés dans le _Fabric-Attached MetroCluster installation and Configuration Guide_.

. Activez tous les ports ISL (si non activés) sur les deux commutateurs dans la structure :
+
`*FC_switch_A_1# config t*`

+
Entrez les commandes de configuration, une par ligne. Terminez par CTRL-Z après avoir saisi toutes les commandes de configuration.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. Vérifiez que les liens ISL sont établis entre les deux commutateurs :
+
`*show topology isl*`

+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----
. Répéter la procédure pour le second commutateur.

