---
permalink: maintain/task_hot_add_a_sas_disk_shelf_in_a_direct_attached_mcc_configuration_us_sas_optical_cables.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, sas, disk, shelf, direct, attached, fc, configuration, optical, cables 
summary: Vous pouvez utiliser les câbles optiques SAS pour ajouter à chaud un tiroir disque SAS à une pile existante de tiroirs disques SAS dans une configuration FC MetroCluster à connexion directe, ou comme nouvelle pile de HBA SAS ou de port SAS intégré du contrôleur. 
---
= Ajout à chaud d'un tiroir disque SAS dans une configuration MetroCluster FC à connexion directe à l'aide de câbles optiques SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les câbles optiques SAS pour ajouter à chaud un tiroir disque SAS à une pile existante de tiroirs disques SAS dans une configuration FC MetroCluster à connexion directe, ou comme nouvelle pile de HBA SAS ou de port SAS intégré du contrôleur.

* Cette procédure ne génère aucune interruption et peut être effectuée en deux heures environ.
* Vous avez besoin du mot de passe d'administration et de l'accès à un serveur FTP ou SCP.
* Si vous ajoutez un tiroir IOM12 à une pile de tiroirs IOM6, reportez-vous à la section link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Ajout de tiroirs IOM12 à chaud à une pile de tiroirs IOM6"].


Cette tâche s'applique à une configuration MetroCluster FC dans laquelle le stockage est directement connecté aux contrôleurs de stockage par des câbles SAS. Elle ne s'applique pas aux configurations FC MetroCluster avec des ponts FC-à-SAS ou des structures de commutateurs FC.

.Étapes
. Suivez les instructions relatives à l'ajout à chaud d'un tiroir disque SAS dans le _Guide d'installation_ pour votre modèle de tiroir disque afin d'effectuer les tâches suivantes pour ajouter à chaud un tiroir disque :
+
.. Installez un tiroir disque pour une ajout à chaud.
.. Allumer les alimentations et définir l'ID de tiroir pour une ajout à chaud.
.. Reliez le tiroir disque ajouté à chaud.
.. Vérifiez la connectivité SAS.



