---
permalink: maintain/task_change_an_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, fc, switch 
summary: 'Vous devrez peut-être changer le fournisseur d"un commutateur FC (Cisco vers Brocade ou inversement), changer le modèle du commutateur, ou les deux.' 
---
= Changement de fournisseur ou de modèle d'un commutateur FC
:allow-uri-read: 


[role="lead"]
Vous devrez peut-être changer le fournisseur d'un commutateur FC de Cisco à Brocade, ou inversement, changer le modèle du commutateur, ou les deux.

.Description de la tâche
* Cette procédure s'applique lorsque vous utilisez des switchs validés NetApp.
* Vous devez effectuer les étapes de cette procédure sur une structure à la fois, pour les deux fabriques de la configuration.


.Étapes
. [[STEP_1,Etape 1]]Vérifiez l'état de santé de la configuration.
+
.. Vérifier que la MetroCluster est configurée et en mode normal sur chaque cluster : `*metrocluster show*`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vérifier que la mise en miroir est activée sur chaque nœud : `*metrocluster node show*`
+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Vérifier que les composants MetroCluster sont sains : `*metrocluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. Vérifier qu'il n'y a pas d'alerte de santé : `*system health alert show*`


. Configurer le nouveau commutateur avant l'installation.
+
Suivez les étapes de la section link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_reset_the_brocade_fc_switch_to_factory_defaults.html["Configuration des commutateurs FC"].

. Débrancher les connexions de l'ancien commutateur en retirant les connexions dans l'ordre suivant :
+
.. Si les interfaces de cluster locales sont connectées à un commutateur :
+
... Déconnectez les interfaces locales du cluster
... Déconnectez les liens ISL locaux du cluster


.. Déconnectez les interfaces MetroCluster FC.
.. Déconnectez les liens ISL MetroCluster.


. Mettez l'ancien commutateur hors tension, retirez les câbles et remplacez physiquement l'ancien commutateur par le nouveau.
. Câbler les contacteurs dans l'ordre suivant :
+
Vous devez suivre les étapes de la section link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_rack_the_hardware_components_mcc_fabric_and_ip.html["Installer et câbler les composants MetroCluster"].

+
.. Reliez les liens ISL au site distant.
.. Reliez les interfaces FC MetroCluster.
.. Reliez les interfaces locales du cluster.
+
Si les interfaces de cluster locales sont connectées à un commutateur :

+
... Reliez les interfaces locales du cluster.
... Reliez les liens ISL du cluster local.




. Mettez le commutateur sous tension.
. Vérifiez que la configuration MetroCluster fonctionne correctement en répétant cette procédure <<Étape 1>>.
. Répétez les étapes 1 à 7 pour la deuxième structure de la configuration.

