---
permalink: maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches, cleanupfiles, cisco 
summary: 'La mise à niveau d"un fichier RCF peut être nécessaire sur un commutateur IP Cisco. Par exemple, une mise à niveau de ONTAP ou une mise à niveau du firmware du switch nécessite tous deux un nouveau fichier RCF.' 
---
= Mettre à niveau les fichiers RCF sur les commutateurs IP Cisco à l'aide de CleanUpFiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pourriez avoir besoin de mettre à niveau un fichier de configuration de référence (RCF) sur un commutateur IP Cisco. Par exemple, une mise à niveau d'ONTAP ou une mise à niveau du microprogramme du commutateur nécessite un nouveau RCF.

.Description de la tâche
* À partir de la version 1.4a de RcfFileGenerator, il existe une nouvelle option permettant de modifier (mise à niveau, rétrogradation ou remplacement) la configuration du commutateur sur les commutateurs IP Cisco sans avoir à effectuer de « effacement d'écriture ».
* link:enable-console-logging-before-maintenance.html["Activer la journalisation de la console"] avant d'effectuer cette tâche.


* Le switch Cisco 9336C-FX2 possède deux types de stockage de switch distincts dont le nom est différent dans le RCF. Utilisez le tableau suivant pour déterminer le type de stockage Cisco 9336C-FX2 adapté à votre configuration :
+
[cols="3*"]
|===
| Si vous connectez le stockage suivant... | Choisissez le type de stockage Cisco 9336C-FX2... | Exemple de bannière RCF/MOTD 


 a| 
** Tiroirs SAS directement connectés
** Tiroirs NVMe directement connectés
** Tiroirs NVMe connectés à des switchs de stockage dédiés

 a| 
9336C-FX2 – stockage direct uniquement
 a| 
`* Switch    : NX9336C (direct storage, L2 Networks, direct ISL)`



 a| 
** Tiroirs SAS directement connectés
** Tiroirs NVMe connectés aux switchs IP MetroCluster



NOTE: Au moins un tiroir NVMe connecté Ethernet est requis
 a| 
9336C-FX2 : stockage SAS et Ethernet
 a| 
`* Switch    : NX9336C (SAS and Ethernet storage, L2 Networks, direct ISL)`

|===


.Avant de commencer
Vous pouvez utiliser cette méthode si votre configuration répond aux exigences suivantes :

* La configuration FCR standard est appliquée.
* Le  https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"] doit pouvoir créer le même RCF que celui appliqué, avec la même version et la même configuration (plateformes, VLANs).
* Le RCF appliqué n'a pas été fourni par NetApp pour une configuration spéciale.
* Le RCF n'a pas été modifié avant son application.
* La procédure de réinitialisation du commutateur aux paramètres d'usine a été suivie avant d'appliquer le RCF actuel.
* Aucune modification n'a été apportée à la configuration du switch(port) après l'application de la FCR.
+
Si vous ne remplissez pas ces conditions, vous ne pouvez pas utiliser les CleanUpFiles qui sont créés lors de la génération des RCFs. Cependant, vous pouvez tirer parti de la fonction pour créer des CleanUpFiles génériques -- le nettoyage à l'aide de cette méthode est dérivé du résultat de  `show running-config` et constitue une bonne pratique.

+

NOTE: Vous devez mettre à jour les commutateurs dans l'ordre suivant : switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2. Vous pouvez également mettre à jour les commutateurs Switch_A_1 et Switch_B_1 en même temps, puis les commutateurs Switch_A_2 et Switch_B_2.



.Étapes
. link:../install-ip/switch-move-cluster-lifs.html["Déplacez les LIF du cluster"]avant de commencer la mise à niveau.
. Déterminez la version RCF actuelle, ainsi que les ports et les VLAN utilisés : `IP_switch_A_1# show banner motd`
+

NOTE: Vous devez obtenir ces informations à partir des quatre commutateurs et remplir le tableau d'information suivant.

+
[listing]
----
* NetApp Reference Configuration File (RCF)
*
* Switch : NX9336C (SAS storage, L2 Networks, direct ISL)
* Filename : NX9336_v1.81_Switch-A1.txt
* Date : Generator version: v1.3c_2022-02-24_001, file creation time: 2021-05-11, 18:20:50
*
* Platforms : MetroCluster 1 : FAS8300, AFF-A400, FAS8700
*              MetroCluster 2 : AFF-A320, FAS9000, AFF-A700, AFF-A800
* Port Usage:
* Ports 1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 111
* Ports 3- 4: Intra-Cluster Node Ports, Cluster: MetroCluster 2, VLAN 151
* Ports 5- 6: Ports not used
* Ports 7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 111, 151
* Ports 9-10: MetroCluster 1, Node Ports, VLAN 119
* Ports 11-12: MetroCluster 2, Node Ports, VLAN 159
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used
*

#
IP_switch_A_1#
----
+
À partir de cette sortie, vous devez collecter les informations présentées dans les deux tableaux suivants.

+
|===


| Informations génériques | MetroCluster | Les données 


| version RCF |  | 1.81 


| Type de commutateur |  | NX9336 


| Typologie de réseau |  | Réseaux L2, liens ISL directs 


| Type de stockage |  | Stockage SAS 


.2+| Plateformes | 1 | AFF A400 


| 2 | FAS9000 
|===
+
|===
| Informations VLAN | Le réseau | Configuration MetroCluster | Ports de commutation | Site A | Site B 


.4+| Cluster local VLAN .2+| Réseau 1 | 1 | 1, 2 | 111 | 222 


| 2 | 3 février 4 | 151 | 251 


.2+| Réseau 2 | 1 | 1, 2 | 111 | 222 


| 2 | 3 février 4 | 151 | 251 


.4+| VLAN MetroCluster .2+| Réseau 1 | 1 | 9 février 10 | 119 | 119 


| 2 | 11 février 12 | 159 | 159 


.2+| Réseau 2 | 1 | 9 février 10 | 219 | 219 


| 2 | 11 février 12 | 259 | 259 
|===
. [[Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles]] Créez les fichiers RCF et CleanUpFiles, ou créez des CleanUpFiles génériques pour la configuration actuelle.
+
Si votre configuration répond aux exigences décrites dans les conditions préalables, sélectionnez *option 1*. Si votre configuration ne répond pas * aux exigences décrites dans les conditions préalables, sélectionnez *option 2*.

+
[role="tabbed-block"]
====
.Option 1 : Créez les RCF et CleanUpFiles
--
Utiliser cette procédure si la configuration répond aux exigences.

.Étapes
.. Utilisez le RcfFileGenerator 1.4a (ou ultérieur) pour créer les RCF avec les informations que vous avez récupérées à l’étape 1. La nouvelle version du RcfFileGenerator crée un ensemble supplémentaire de CleanUpFiles que vous pouvez utiliser pour annuler une configuration et préparer le commutateur à appliquer une nouvelle configuration RCF.
.. Comparez le banner motd avec les RCF actuellement appliqués. Les types de plateforme, de commutateur, de port et d'utilisation de VLAN doivent être identiques.
+

NOTE: Vous devez utiliser le CleanUpFiles de la même version que le RCF et pour exactement la même configuration. Utiliser n'importe quel CleanUpFile ne fonctionnera pas et pourrait nécessiter une réinitialisation complète du commutateur.

+

NOTE: La version d'ONTAP pour laquelle le RCF a été créé n'est pas pertinente. Seule la version du RCF est importante.

+

NOTE: Le fichier RCF (même s'il s'agit de la même version) peut indiquer moins ou plus de plateformes. Assurez-vous que votre plateforme y figure.



--
.Option 2 : création de fichiers génériques CleanUpFiles
--
Utilisez cette procédure si la configuration ne répond pas * à toutes les exigences.

.Étapes
.. Récupérer la sortie de `show running-config` de chaque commutateur.
.. Ouvrez l'outil RcfFileGenerator et cliquez sur 'Create generic CleanUpFiles' en bas de la fenêtre
.. Copiez le résultat que vous avez récupéré à l'étape 1 à partir du commutateur 'un' dans la fenêtre supérieure. Vous pouvez supprimer ou conserver la sortie par défaut.
.. Cliquez sur 'Créer des fichiers CUF'.
.. Copiez la sortie de la fenêtre inférieure dans un fichier texte (ce fichier est le CleanUpFile).
.. Répétez les étapes c, d et e pour tous les commutateurs de la configuration.
+
À la fin de cette procédure, vous devez avoir quatre fichiers texte, un pour chaque commutateur. Vous pouvez utiliser ces fichiers de la même manière que les fichiers CleanUpFiles que vous pouvez créer à l'aide de l'option 1.



--
====
. Créez les « nouveaux » fichiers RCF pour la nouvelle configuration. Créez ces fichiers de la même manière que vous avez créé les fichiers à l'étape précédente, sauf que vous devez choisir la version ONTAP et RCF respective.
+
Une fois cette étape terminée, vous devriez avoir deux ensembles de RCF, chaque ensemble composé de douze fichiers.

. Téléchargez les fichiers sur le bootflash.
+
.. Téléchargez le fichier CleanUpFiles que vous avez créé dans <<Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles,Créez les RCF et CleanUpFiles, ou créez des CleanUpFiles génériques pour la configuration actuelle>>
+

NOTE: Ce CleanUpFile concerne le RCF actuel appliqué et *NON* le nouveau RCF vers lequel vous souhaitez effectuer la mise à niveau.

+
Exemple de fichier CleanUpFile pour Switch-A1 : `Cleanup_NX9336_v1.81_Switch-A1.txt`

.. Téléchargez les « nouveaux » RCF que vous avez créés dans <<Create-the-new-RCF-files-for-the-new-configuration,Créez les « nouveaux » RCF pour la nouvelle configuration.>>
+
Exemple de RCF pour Switch-A1 : `NX9336_v1.90_Switch-A1.txt`

.. Téléchargez le CleanUpFiles que vous avez créé dans <<Create-the-new-RCF-files-for-the-new-configuration,Créez les « nouveaux » RCF pour la nouvelle configuration.>> Cette étape est facultative -- vous pouvez utiliser le fichier à l'avenir pour mettre à jour la configuration du commutateur. Il correspond à la configuration actuellement appliquée.
+
Exemple de fichier CleanUpFile pour Switch-A1 : `Cleanup_NX9336_v1.90_Switch-A1.txt`

+

NOTE: Vous devez utiliser CleanUpFile pour la version FCR correcte (correspondante). Si vous utilisez un CleanUpFile pour une version FCR différente, ou une configuration différente, le nettoyage de la configuration risque de ne pas fonctionner correctement.

+
L'exemple suivant copie les trois fichiers dans le bootflash :

+
[listing]
----
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.81_MetroCluster-IP_L2Direct_A400FAS8700_xxx_xxx_xxx_xxx/Cleanup_NX9336_v1.81_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//NX9336_v1.90_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//Cleanup_NX9336_v1.90_Switch-A1.txt bootflash:
----
+

NOTE: Vous êtes invité à spécifier le routage et le transfert virtuels (VRF).



. Appliquez le CleanUpFile ou le CleanUpFile générique.
+
Une partie de la configuration est rétablie et les ports de commutation sont « hors ligne ».

+
.. Vérifiez qu'aucune modification n'est en attente de la configuration de démarrage : `show running-config diff`
+
[listing]
----
IP_switch_A_1# show running-config diff
IP_switch_A_1#
----


. Si vous voyez la sortie du système, enregistrez la configuration en cours d'exécution dans la configuration de démarrage : `copy running-config startup-config`
+

NOTE: Le résultat du système indique que la configuration de démarrage et la configuration en cours d'exécution sont différentes et en attente de modifications. Si vous n'enregistrez pas les modifications en attente, vous ne pouvez pas revenir en arrière à l'aide d'un rechargement du commutateur.

+
.. Appliquer le fichier CleanUpFile :
+
[listing]
----

IP_switch_A_1# copy bootflash:Cleanup_NX9336_v1.81_Switch-A1.txt running-config

IP_switch_A_1#
----
+

NOTE: Le script peut prendre un certain temps pour revenir à l'invite du commutateur. Aucune sortie n'est attendue.



. Afficher la configuration en cours d'exécution pour vérifier que la configuration est effacée : `show running-config`
+
La configuration actuelle doit indiquer :

+
** Aucun mappage de classe et aucune liste d'accès IP n'est configuré
** Aucun mappage de stratégie n'est configuré
** Aucune stratégie de services n'est configurée
** Aucun profil de port n'est configuré
** Toutes les interfaces Ethernet (à l'exception de mgmt0 qui ne doivent pas afficher de configuration, et seul le VLAN 1 doit être configuré).
+
Si vous constatez que l’un des éléments ci-dessus est configuré, il se peut que vous ne puissiez pas appliquer une nouvelle configuration RCF. Cependant, vous pouvez revenir à la configuration précédente en redémarrant le commutateur *sans* enregistrer la configuration en cours dans la configuration de démarrage. Le commutateur démarrera avec la configuration précédente.



. Appliquez le RCF et vérifiez que les ports sont en ligne.
+
.. Appliquez le RCF.
+
[listing]
----
IP_switch_A_1# copy bootflash:NX9336_v1.90-X2_Switch-A1.txt running-config
----
+

NOTE: Certains messages d'avertissement s'affichent lors de l'application de la configuration. Les messages d'erreur ne sont généralement pas attendus. Toutefois, si vous êtes connecté à l'aide de SSH, vous pouvez recevoir l'erreur suivante : `Error: Can't disable/re-enable ssh:Current user is logged in through ssh`

.. Une fois la configuration appliquée, vérifiez que le cluster et les ports MetroCluster sont mis en ligne à l'aide de l'une des commandes suivantes, `show interface brief`, `show cdp neighbors`, ou `show lldp neighbors`
+

NOTE: Si vous avez modifié le VLAN pour le cluster local et que vous avez mis à niveau le premier commutateur du site, la surveillance de l'état du cluster risque de ne pas indiquer qu'il est « sain », car les VLAN de l'ancienne et des nouvelles configurations ne correspondent pas. Après la mise à jour du second contacteur, l'état doit revenir à l'état sain.

+
Si la configuration n'est pas correctement appliquée ou si vous ne souhaitez pas conserver la configuration, vous pouvez revenir à la configuration précédente en rechargeant le commutateur *sans* enregistrer la configuration en cours dans la configuration de démarrage. Le commutateur s'active avec la configuration précédente.



. Enregistrer la configuration et recharger le commutateur.
+
[listing]
----
IP_switch_A_1# copy running-config startup-config

IP_switch_A_1# reload
----
. Modifiez tous les LIF du cluster pour activer la restauration automatique :
+
.. Réactivez la restauration automatique :
+
`network interface modify -vserver Cluster -lif * -auto-revert true`

+
[listing]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert true

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.

cluster_A::*>
----
.. Rétablir les ports d'origine de toutes les interfaces réseau du cluster qui ne sont pas actuellement connectées à leurs ports d'origine :
+
`network interface revert -vserver Cluster -lif *`

+
Veuillez patienter quelques minutes le temps que les LIF reviennent à leur port d'attache :

.. Confirmez que tous les LIF sont sur leurs ports d'attache :
+
[listing]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      192.168.204.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      192.168.204.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      192.168.204.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      192.168.204.97/18  node_A_2      e4b     true
4 entries were displayed.
----
.. Vérifiez l'état des nœuds MetroCluster :
+
`metrocluster node show`

+
[listing]
----
cluster_A::*> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_B
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.

cluster_A::*>
----



