---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_cisco_fc_switch_mcc.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, cisco, fc, switch 
summary: Pour mettre à niveau ou rétrograder le micrologiciel sur un commutateur FC Cisco, vous devez utiliser les commandes spécifiques à Cisco pour désactiver le commutateur, effectuer et vérifier la mise à niveau, puis redémarrer et réactiver le commutateur. 
---
= Mise à niveau ou rétrogradation du micrologiciel sur un commutateur Cisco FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour mettre à niveau ou rétrograder le micrologiciel sur un commutateur FC Cisco, vous devez utiliser les commandes spécifiques à Cisco pour désactiver le commutateur, effectuer et vérifier la mise à niveau, puis redémarrer et réactiver le commutateur.

.Description de la tâche
Vérifiez que vous avez vérifié et effectué les tâches suivantes pour votre configuration :

* Le système est correctement câblé.
* Tous les chemins d'accès aux tiroirs de stockage sont disponibles.
* Les piles de tiroirs disques sont stables.
* La structure du commutateur FC fonctionne correctement.
* Tous les composants du système sont en bon état.
* Le système fonctionne normalement.
* Vous disposez du mot de passe admin et de l'accès à un serveur FTP ou SCP.
* La journalisation de la console est activée.
+
link:enable-console-logging-before-maintenance.html["Activer la journalisation de la console"]



La structure des commutateurs est désactivée lors de la mise à niveau ou d'une mise à niveau vers une version antérieure du firmware, et la configuration MetroCluster s'appuie sur la deuxième structure pour continuer le fonctionnement.

Vous devez répéter cette tâche successivement sur chacune des matrices de commutation pour vous assurer que tous les commutateurs exécutent la même version de micrologiciel.

Vous devez disposer des fichiers de micrologiciel.


NOTE: Cette procédure ne génère aucune interruption et ne prend qu'une heure.

.Étapes
. Connectez-vous à chacun des commutateurs de la structure.
+
Dans ces exemples, les commutateurs sont appelés FC_Switch_A_1 et FC_Switch_B_1.

. Déterminez s'il y a suffisamment d'espace dans le répertoire bootflash de chaque commutateur :
+
`*dir bootflash*`

+
Si ce n'est pas le cas, supprimez les fichiers de micrologiciel indésirables à l'aide du `delete bootflash:file_name` commande.

. Copiez les fichiers kickstart et système sur les commutateurs :
+
`*copy _source_filetarget_file_*`

+
Dans l'exemple suivant, le fichier kickstart (`m9200-s2ek9-kickstart-mz.5.2.1.bin`) et le fichier système (`m9200-s2ek9-mz.5.2.1.bin`) Sont situés sur le serveur FTP 10.10.10.55 dans le `/firmware/` chemin.

+
L'exemple suivant montre les commandes émises sur FC_Switch_A_1 :

+
[listing]
----
FC_switch_A_1# copy ftp://10.10.10.55/firmware/m9200-s2ek9-kickstart-mz.5.2.1.bin bootflash:m9200-s2ek9-kickstart-mz.5.2.1.bin
FC_switch_A_1# copy ftp://10.10.10.55/firmware/m9200-s2ek9-mz.5.2.1.bin bootflash:m9200-s2ek9-mz.5.2.1.bin
----
. Désactivez tous les SAN virtuels sur les deux commutateurs de cette structure.
+
Pour désactiver les VSAN, procédez comme suit :

+
.. Ouvrez le terminal de configuration :
+
`*config t*`

.. Entrez : `*vsan database*`
.. Vérifier l'état des VSAN:
+
`*show vsan*`

+
Tous les VSAN doivent être actifs.

.. Suspendre les VSAN:
+
`*vsan _vsan-num_ suspend*`

+
*Exemple:* `vsan 10 suspend`

.. Vérifier à nouveau l'état des VSAN:
+
`*show vsan*`+ tous les VSAN doivent être suspendus.

.. Quittez le terminal de configuration :
+
`*end*`

.. Enregistrez la configuration.
+
`*copy running-config startup-config*`

+
L'exemple suivant affiche la sortie pour FC_Switch_A_1 :

+
[listing]
----
FC_switch_A_1# config t
Enter configuration commands, one per line.  End with CNTL/Z.
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 30 information
         name:MC1_FCVI_2_30  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 40 information
         name:MC1_STOR_2_40  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 70 information
         name:MC2_FCVI_2_70  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 80 information
         name:MC2_STOR_2_80  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# vsan 1 suspend
FC_switch_A_1(config-vsan-db)# vsan 30 suspend
FC_switch_A_1(config-vsan-db)# vsan 40 suspend
FC_switch_A_1(config-vsan-db)# vsan 70 suspend
FC_switch_A_1(config-vsan-db)# vsan 80 suspend
FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1#
FC_switch_A_1# show vsan
vsan 1 information
         name:VSAN0001  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 30 information
         name:MC1_FCVI_2_30  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 40 information
         name:MC1_STOR_2_40  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 70 information
         name:MC2_FCVI_2_70  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 80 information
         name:MC2_STOR_2_80  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan
----


. Installez le micrologiciel souhaité sur les commutateurs :
+
`*install all system bootflash:__systemfile_name__ kickstart bootflash:__kickstartfile_name__*`

+
L'exemple suivant montre les commandes émises sur FC_Switch_A_1 :

+
[listing]
----
FC_switch_A_1# install all system bootflash:m9200-s2ek9-mz.5.2.1.bin kickstart bootflash:m9200-s2ek9-kickstart-mz.5.2.1.bin
Enter Yes to confirm the installation.
----
. Vérifiez la version du micrologiciel de chaque commutateur pour vous assurer que la version correcte a été installée :
+
`*show version*`

. Activez tous les SAN virtuels sur les deux commutateurs de cette structure.
+
Utilisez la procédure suivante pour activer les VSAN:

+
.. Ouvrez le terminal de configuration :
+
`*config t*`

.. Entrez : `*vsan database*`
.. Vérifier l'état des VSAN:
+
`*show vsan*`

+
Les VSAN doivent être suspendus.

.. Activer les VSAN:
+
`*no vsan _vsan-num_ suspend*`

+
*Exemple:* `no vsan 10 suspend`

.. Vérifier à nouveau l'état des VSAN:
+
`*show vsan*`

+
Tous les VSAN doivent être actifs.

.. Quittez le terminal de configuration :
+
`*end*`

.. Enregistrez la configuration :
+
`*copy running-config startup-config*`

+
L'exemple suivant affiche la sortie pour FC_Switch_A_1 :

+
[listing]
----
FC_switch_A_1# config t
Enter configuration commands, one per line.  End with CNTL/Z.
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 30 information
         name:MC1_FCVI_2_30  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 40 information
         name:MC1_STOR_2_40  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 70 information
         name:MC2_FCVI_2_70  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 80 information
         name:MC2_STOR_2_80  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# no vsan 1 suspend
FC_switch_A_1(config-vsan-db)# no vsan 30 suspend
FC_switch_A_1(config-vsan-db)# no vsan 40 suspend
FC_switch_A_1(config-vsan-db)# no vsan 70 suspend
FC_switch_A_1(config-vsan-db)# no vsan 80 suspend
FC_switch_A_1(config-vsan-db)#
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 30 information
         name:MC1_FCVI_2_30  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 40 information
         name:MC1_STOR_2_40  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 70 information
         name:MC2_FCVI_2_70  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 80 information
         name:MC2_STOR_2_80  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1#
----


. Vérifier le fonctionnement de la configuration MetroCluster dans ONTAP :
+
.. Vérifier si le système est multipathed :
+
`*node run -node _node-name_ sysconfig -a*`

.. Vérifier si des alertes d'intégrité sont disponibles sur les deux clusters :
+
`*system health alert show*`

.. Vérifier la configuration MetroCluster et que le mode opérationnel est normal :
+
`*metrocluster show*`

.. Effectuer une vérification MetroCluster :
+
`*metrocluster check run*`

.. Afficher les résultats de la vérification MetroCluster :
+
`*metrocluster check show*`

.. Vérifier la présence d'alertes d'intégrité sur les commutateurs (le cas échéant) :
+
`*storage switch show*`

.. Exécutez Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"]

.. Une fois Config Advisor exécuté, vérifiez les résultats de l'outil et suivez les recommandations fournies dans la sortie pour résoudre tous les problèmes détectés.


. Répéter cette procédure pour le second commutateur.

