---
permalink: maintain/task_disable_encryption_on_brocade_fc_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, disable, encryption, brocade, fc, switch 
summary: 'Il peut s"avérer nécessaire de désactiver le cryptage sur les commutateurs Brocade FC.' 
---
= Désactivation du cryptage sur les commutateurs Brocade FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il peut s'avérer nécessaire de désactiver le cryptage sur les commutateurs Brocade FC.

.Étapes
. Envoyer un message AutoSupport des deux sites indiquant le début de la maintenance.
+
[listing]
----
cluster_A::> autosupport invoke -node * -type all -message MAINT=4h
----
+
[listing]
----
cluster_B::> autosupport invoke -node * -type all -message MAINT=4h
----
. Vérifiez le fonctionnement de la configuration MetroCluster depuis le Cluster A.
+
.. Vérifier la configuration MetroCluster et que le mode opérationnel est normal : +
`*metrocluster show*`
+
[listing]
----
cluster_A::> metrocluster show
----
.. Effectuer une vérification MetroCluster : +
`*metrocluster check run*`
+
[source, nolinebreak]
----
cluster_A::> metrocluster check run
----
.. Afficher les résultats de la vérification MetroCluster : +
`*metrocluster check show*`
+
[source, nolinebreak]
----
cluster_A::> metrocluster check show
----


. Vérifier l'état des deux commutateurs :
+
`*fabric show*`

+
[listing]
----
switch_A_1:admin> fabric show
----
+
[listing]
----
switch_B_1:admin> fabric show
----
. Désactiver les deux commutateurs :
+
`*switchdisable*`

+
[listing]
----
switch_A_1:admin> switchdisable
----
+
[listing]
----
switch_B_1:admin> switchdisable
----
. Vérifier les chemins disponibles des nœuds sur chaque cluster :
+
`*sysconfig*`

+
[listing]
----
cluster_A::> system node run -node node-name -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node node-name -command sysconfig -a
----
+
Lorsque la structure du commutateur est maintenant désactivée, la configuration du stockage système doit être la haute disponibilité à chemin unique.

. Vérifier l'état de l'agrégat pour les deux clusters.
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
Le résultat du système doit afficher que les agrégats sont en miroir et que la normale pour les deux clusters :

+
[listing]
----
mirrored,normal
----
. Répétez les sous-étapes suivantes à partir de l'invite d'administration sur les deux commutateurs.
+
.. Indique les ports chiffrés : +
`*portenccompshow*`
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. Désactiver le cryptage sur les ports chiffrés : +
`*portcfgencrypt – disable _port-number_*`
+
[listing]
----
switch_A_1:admin> portcfgencrypt --disable 40
switch_A_1:admin> portcfgencrypt --disable 41
switch_A_1:admin> portcfgencrypt --disable 42
switch_A_1:admin> portcfgencrypt --disable 43
----
.. Définissez le type d'authentification sur tous :
+
`*authUtil --set -a all*`

+
[listing]
----
switch_A_1:admin> authUtil --set -a all
----
.. Définissez la stratégie d'authentification sur le commutateur. pour désactiver : +
`*authutil --policy -sw off*`
+
[listing]
----
switch_A_1:admin> authutil --policy -sw off
----
.. Définissez le groupe Diffie-Hellman d'authentification sur +*+ : +
`*authutil --set -g **`
+
[listing]
----
switch_A_1:admin> authUtil --set -g *
----
.. Supprimez la base de données de clés secrètes : +
`*secAuthSecret --remove -all*`
+
[listing]
----
switch_A_1:admin> secAuthSecret --remove -all
----
.. Vérifiez que le chiffrement est désactivé sur les ports : +
`*portenccompshow*`
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. Activer le commutateur : +
`*switchenable*`
+
[listing]
----
switch_A_1:admin> switchenable
----
.. Confirmez le statut des liens ISL : +
`*islshow*`
+
[listing]
----
switch_A_1:admin> islshow
----


. Vérifier les chemins disponibles des nœuds sur chaque cluster :
+
`*sysconfig*`

+
[listing]
----
cluster_A::> system node run -node * -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node * -command sysconfig -a
----
+
La sortie système doit indiquer que la configuration du stockage système est repassée en configuration HA à quatre chemins.

. Vérifier l'état de l'agrégat pour les deux clusters.
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
Le système doit afficher que les agrégats sont en miroir et normaux pour les deux clusters, comme indiqué dans la sortie du système suivante :

+
[listing]
----
mirrored,normal
----
. Vérifiez le fonctionnement de la configuration MetroCluster depuis le Cluster A.
+
.. Effectuer une vérification MetroCluster : +
`*metrocluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run
----
.. Afficher les résultats de la vérification MetroCluster : +
`*metrocluster check show*`
+
[listing]
----
cluster_A::> metrocluster check show
----


. Envoyer un message AutoSupport des deux sites indiquant la fin de la maintenance.
+
[listing]
----
cluster_A::> autosupport invoke -node node-name -type all -message MAINT=END
----
+
[listing]
----
cluster_B::> autosupport invoke -node node-name -type all -message MAINT=END
----

