---
permalink: maintain/task_change_an_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, fc, switch 
summary: 'Vous devrez peut-être changer le fournisseur d"un commutateur FC (Cisco vers Brocade ou inversement), changer le modèle du commutateur, ou les deux.' 
---
= Changement de fournisseur ou de modèle des commutateurs FC
:allow-uri-read: 


[role="lead"]
Vous devrez peut-être changer de fournisseur pour les commutateurs FC de Cisco à Brocade, ou inversement, changer de modèle de commutateur, ou modifier les deux.

.Description de la tâche
* Cette procédure s'applique lorsque vous utilisez des switchs validés NetApp.
* Vous devez effectuer les étapes de cette procédure sur une structure à la fois, pour les deux fabriques de la configuration.


.Étapes
. [[STEP_1,Etape 1]]Vérifiez l'état de santé de la configuration.
+
.. Vérifier que la MetroCluster est configurée et en mode normal sur chaque cluster : `*metrocluster show*`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vérifier que la mise en miroir est activée sur chaque nœud : `*metrocluster node show*`
+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Vérifier que les composants MetroCluster sont sains : `*metrocluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. Vérifier qu'il n'y a pas d'alerte de santé : `*system health alert show*`


. Configurez les nouveaux commutateurs avant l'installation.
+
Suivez les étapes de la section link:../install-fc/concept-configure-fc-switches.html["Configuration des commutateurs FC"].

. Débrancher les connexions des anciens commutateurs en retirant les connexions dans l'ordre suivant :
+
.. Débrancher les interfaces MetroCluster FC et FCVI.
.. Débrancher les ponts FibreBridge ATTO.
.. Déconnectez les liens ISL MetroCluster.


. Mettez les anciens commutateurs hors tension, retirez les câbles et remplacez physiquement les anciens par le nouveau commutateur.
. Câbler les contacteurs dans l'ordre suivant :
+
Vous devez suivre les étapes de la section link:../install-fc/task_configure_the_mcc_hardware_components_fabric.html["Câblage d'une configuration MetroCluster Fabric-Attached"].

+
.. Reliez les liens ISL au site distant.
.. Câblez les ponts FibreBridge ATTO.
.. Câblez les interfaces MetroCluster FC et FCVI.


. Mettez les commutateurs sous tension.
. Vérifiez que la configuration MetroCluster fonctionne correctement en répétant cette procédure <<Étape 1>>.
. Répétez les étapes 1 à 7 pour la deuxième structure de la configuration.

