---
permalink: install-stretch/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, additional, information 
summary: 'Pour plus d"informations sur la configuration et le fonctionnement de MetroCluster, consultez la documentation NetApp.' 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster,



== MetroCluster et informations diverses

|===


| Informations | Objet 


 a| 
https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP 9"^]
 a| 
* Tous les guides MetroCluster




 a| 
 a| 
* Présentation technique de la configuration et du fonctionnement de MetroCluster FC.
* Meilleures pratiques en matière de configuration MetroCluster FC.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]
 a| 
* Architecture Fabric-Attached MetroCluster
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration des commutateurs FC
* Configuration de MetroCluster dans ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["Installation et configuration IP de MetroCluster : différences entre les configurations ONTAP MetroCluster"]
 a| 
* Architecture de MetroCluster IP
* Câblage de la configuration
* Configuration de MetroCluster dans ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html["Gestion et reprise après incident MetroCluster"]
 a| 
* Présentation de la configuration MetroCluster
* Basculement, rétablissement et rétablissement
* Reprise après incident




 a| 
link:../maintain/index.html["Gérer les composants MetroCluster"]
 a| 
* Instructions relatives à la maintenance dans une configuration MetroCluster FC
* Remplacement ou mise à niveau du matériel. Procédure de mise à niveau de firmware pour les ponts FC-à-SAS et les commutateurs FC
* Ajout à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Retrait à chaud d'un tiroir disque dans une configuration FC MetroCluster étendue ou FAS
* Remplacement du matériel sur un site de reprise sur incident dans une configuration MetroCluster FC Fabric-Attached ou Stretch
* Extension d'une configuration MetroCluster FC extensible ou Fabric-Attached à deux nœuds à une configuration MetroCluster à quatre nœuds.
* Extension d'une configuration MetroCluster FC à quatre nœuds (Fabric-Attached ou Stretch FC) à une configuration MetroCluster FC à huit nœuds.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html["Transition de MetroCluster FC à MetroCluster IP"]

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Guide de mise à niveau et d'extension de MetroCluster"]
 a| 
* Mise à niveau ou actualisation d'une configuration MetroCluster
* Passer d'une configuration MetroCluster FC à une configuration MetroCluster IP
* Extension d'une configuration MetroCluster par l'ajout de nœuds supplémentaires




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html["Installation et configuration du logiciel MetroCluster Tiebreaker"]
 a| 
* Contrôle de la configuration de MetroCluster avec le logiciel MetroCluster Tiebreaker




 a| 
Documentation Active IQ Unified Manager

https://www.netapp.com/support-and-training/documentation/["Documentation NetApp : guides et ressources produits"^]
 a| 
* Contrôle de la configuration et des performances d'MetroCluster




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Transition basée sur la copie"]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["Concepts relatifs à ONTAP"]
 a| 
* Fonctionnement des agrégats en miroir


|===