---
permalink: install-stretch/reference_information_gathering_worksheet_for_fc_to_sas_bridges_2_node_atto.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, worksheet, fc, sas, bridges, information 
summary: Vous devez collecter les informations de configuration requises avant de commencer à configurer les sites MetroCluster. 
---
= Fiche technique pour la collecte d'informations sur les ponts FC-SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez collecter les informations de configuration requises avant de commencer à configurer les sites MetroCluster.



== Site A, pont FC-to-SAS 1 (FC_Bridge_A_1a)

Chaque pile SAS requiert au moins deux ponts FC-SAS.

Chaque pont se connecte au Controller_A_1_``__port-number__`` Et Controller_B_1_``__port-number__``.

|===


| Site A | Votre valeur 


 a| 
Adresse IP Bridge_A_1a
 a| 



 a| 
Nom d'utilisateur Bridge_A_1a
 a| 



 a| 
Mot de passe Bridge_A_1a
 a| 

|===


== Site A, pont FC-to-SAS 2 (FC_Bridge_A_1b)

Chaque pile SAS requiert au moins deux ponts FC-SAS.

Chaque pont se connecte au Controller_A_1_``__port-number__`` Et Controller_B_1_``__port-number__``.

|===


| Site A | Votre valeur 


 a| 
Adresse IP Bridge_A_1b
 a| 



 a| 
Nom d'utilisateur Bridge_A_1b
 a| 



 a| 
Mot de passe Bridge_A_1b
 a| 

|===


== Site B, pont FC-to-SAS 1 (FC_Bridge_B_1a)

Chaque pile SAS requiert au moins deux ponts FC-SAS.

Chaque pont se connecte au Controller_A_1_`__port-number__` et au Controller_B_1_`__port-number___'.

|===


| Site B | Votre valeur 


 a| 
Adresse IP Bridge_B_1a
 a| 



 a| 
Bridge_B_1a Nom d'utilisateur
 a| 



 a| 
Mot de passe Bridge_B_1a
 a| 

|===


== Site B, pont FC-to-SAS 2 (FC_Bridge_B_1b)

Chaque pile SAS requiert au moins deux ponts FC-SAS.

Chaque pont se connecte au Controller_A_1_`__port-number__` et au Controller_B_1_`__port-number___'.

|===


| Site B | Votre valeur 


 a| 
Adresse IP Bridge_B_1b
 a| 



 a| 
Bridge_B_1b Nom d'utilisateur
 a| 



 a| 
Mot de passe Bridge_B_1b
 a| 

|===