---
permalink: install-stretch/reference_sas_optical_mc_configuring_a_stretch_mcc_system_with_sas_disk_shelves_and_sas_optical_cables.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, install, cable, components, two, node, sas, stretch, attached, configuration 
summary: Les contrôleurs de stockage doivent être reliés au support de stockage et reliés entre eux. Les contrôleurs de stockage doivent également être câblés au réseau de données et de gestion. 
---
= Installation et câblage des composants MetroCluster pour les configurations Stretch SAS-Attached à deux nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les contrôleurs de stockage doivent être reliés au support de stockage et reliés entre eux. Les contrôleurs de stockage doivent également être câblés au réseau de données et de gestion.



== Avant de commencer une procédure dans ce document

Les exigences générales suivantes doivent être respectées avant d'effectuer cette tâche :

* Avant l'installation, vous devez vous familiariser avec les considérations et les meilleures pratiques d'installation et de câblage des tiroirs disques pour votre modèle de tiroir disque.
* Tous les composants MetroCluster doivent être pris en charge.
+
https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

+
Dans le IMT, vous pouvez utiliser le champ solution de stockage pour sélectionner votre solution MetroCluster. Utilisez *Explorateur de composants* pour sélectionner les composants et la version ONTAP pour affiner votre recherche. Vous pouvez cliquer sur *Afficher les résultats* pour afficher la liste des configurations prises en charge qui correspondent aux critères.





== Description de la tâche

* Les termes « nœud » et « contrôleur » sont utilisés de manière interchangeable.

