---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html 
sidebar: sidebar 
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, additional, information, miscellaneous, guide 
summary: Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster, consultez la documentation complète de NetApp. 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur la configuration et le fonctionnement de MetroCluster,



== MetroCluster et informations diverses

|===


| Informations | Objet 


 a| 
link:../index.html["Documentation MetroCluster"]
 a| 
* Toutes les informations relatives aux MetroCluster




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["Rapport technique de NetApp 4375 : NetApp MetroCluster pour ONTAP 9.3"^]
 a| 
* Présentation technique de la configuration et du fonctionnement de MetroCluster.
* Bonnes pratiques de configuration MetroCluster.




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html["Installation et configuration de la solution Fabric-Attached MetroCluster"]
 a| 
* Architecture Fabric-Attached MetroCluster
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration des commutateurs FC
* Configuration de MetroCluster dans ONTAP




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html["Installation et configuration d'Stretch MetroCluster"]
 a| 
* Architecture MetroCluster extensible
* Câblage de la configuration
* Configuration des ponts FC-SAS
* Configuration de MetroCluster dans ONTAP




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html["Installation et configuration de MetroCluster IP"]
 a| 
* Architecture de MetroCluster IP
* Câblage de la configuration
* Configuration de MetroCluster dans ONTAP




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation et configuration du logiciel MetroCluster Tiebreaker 1.21"]
 a| 
* Contrôle de la configuration de MetroCluster avec le logiciel MetroCluster Tiebreaker




 a| 
Documentation Active IQ Unified Manager https://www.netapp.com/support-and-training/documentation/["Documentation NetApp : guides et ressources produits"^]
 a| 
* Contrôle de la configuration et des performances d'MetroCluster




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transition basée sur la copie"]
 a| 
* Transition des données depuis les systèmes de stockage 7-mode vers les systèmes de stockage en cluster


|===