---
permalink: manage/task_perform_a_negotiated_switchover.html 
sidebar: sidebar 
keywords: negotiate, switchover, clean, shut, down, partner, site, operation, metrocluster, perform 
summary: Un basculement négocié arrête clairement les processus sur le site partenaire, puis bascule les opérations sur le site partenaire. Vous pouvez utiliser un basculement négocié pour réaliser des opérations de maintenance sur un site MetroCluster ou tester la fonctionnalité de basculement. 
---
= Effectuer un basculement négocié
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un basculement négocié arrête clairement les processus sur le site partenaire, puis bascule les opérations sur le site partenaire. Vous pouvez utiliser un basculement négocié pour réaliser des opérations de maintenance sur un site MetroCluster ou tester la fonctionnalité de basculement.

* Toutes les modifications de la configuration précédente doivent être effectuées avant d'effectuer une opération de rétablissement.
+
Cette approche permet d'éviter la concurrence avec l'opération de basculement ou de rétablissement négociée.

* Tous les nœuds qui étaient auparavant en panne doivent être démarrés et dans le quorum du cluster.
+
Le _System Administration Reference_ contient plus d'informations sur le quorum du cluster dans la section « comprendre le quorum et l'epsilon ».

+
https://["Administration du système"]

* Le réseau de peering de cluster doit être disponible depuis les deux sites.
* Tous les nœuds de la configuration MetroCluster doivent exécuter la même version du logiciel ONTAP.
* L'option Replication.create_Data_protection_rels.enable doit être défini sur ON des deux sites de configuration MetroCluster avant de créer une nouvelle relation SnapMirror.
* Dans le cas d'une configuration MetroCluster à deux nœuds, une nouvelle relation SnapMirror ne doit pas être créée lors de la mise à niveau si les versions d'ONTAP entre les sites ne correspondent pas.
* Dans le cas d'une configuration MetroCluster à quatre nœuds, les versions de ONTAP non correspondantes ne sont pas prises en charge.


Le site de restauration peut se rétablissement en quelques heures.

La commande MetroCluster switchover permet de basculer sur les nœuds de tous les groupes DR dans la configuration MetroCluster. Par exemple, dans une configuration MetroCluster à 8 nœuds, il bascule les nœuds sur les deux groupes de reprise après incident.

Lors de la préparation et de l'exécution d'un basculement négocié, vous ne devez pas modifier la configuration dans un cluster, ni effectuer des opérations de basculement ou de rétablissement.

Pour les configurations MetroCluster FC :

* Les agrégats en miroir resteront dans un état normal en cas d'accès au stockage distant.
* En cas de perte de l'accès au stockage distant, les agrégats en miroir sont dégradés après le basculement négocié.
* En cas de perte de l'accès au stockage distant, les agrégats non mis en miroir qui se trouvent sur le site de reprise après incident deviennent indisponibles. Cela peut entraîner une panne du contrôleur.


Pour les configurations MetroCluster IP :


NOTE: Avant d'effectuer des tâches de maintenance, vous devez supprimer la surveillance si la configuration MetroCluster est surveillée à l'aide de l'utilitaire Tiebreaker ou Mediator.link:../maintain/concept_remove_mediator_or_tiebreaker_when_performing_maintenance_tasks.html["Retirez le programme de surveillance du médiateur ONTAP ou du disjoncteur d'attache avant d'effectuer des tâches de maintenance"]

* Pour ONTAP 9.4 et versions antérieures :
+
** Les agrégats en miroir seront dégradés après le basculement négocié.


* Pour ONTAP 9.5 et versions ultérieures :
+
** Les agrégats en miroir resteront dans un état normal en cas d'accès au stockage distant.
** En cas de perte de l'accès au stockage distant, les agrégats en miroir sont dégradés après le basculement négocié.


* Pour ONTAP 9.8 et versions ultérieures :
+
** En cas de perte de l'accès au stockage distant, les agrégats non mis en miroir qui se trouvent sur le site de reprise après incident deviennent indisponibles. Cela peut entraîner une panne du contrôleur.
+
... Utilisez les commandes MetroCluster check run, MetroCluster check show et MetroCluster check config-réplication show pour vérifier qu'aucune mise à jour de configuration n'est en cours ou en attente. Exécutez ces commandes depuis le site qui resteront opérationnelles.
... Depuis le site qui restera opérationnel, mettez en œuvre le basculement : `metrocluster switchover`
+
L'opération peut prendre plusieurs minutes.

... Surveiller la fin du basculement : `metrocluster operation show`
+
[listing]
----
cluster_A::*> metrocluster operation show
  Operation: Switchover
 Start time: 10/4/2012 19:04:13
      State: in-progress
   End time: -
     Errors:

cluster_A::*> metrocluster operation show
  Operation: Switchover
 Start time: 10/4/2012 19:04:13
      State: successful
   End time: 10/4/2012 19:04:22
     Errors: -
----
... Rétablir toutes les configurations SnapMirror ou SnapVault.





